### ISSUE TITLE
Cannot assign tableData when using axios.

### ISSUE THREAD

**Issue by pwnz22** [ratiw/vuetable-2#105]
Hi all!

When im switching to axios from this commit [`fd91517`](https://github.com/ratiw/vuetable-2/commit/fd91517de6844e2b3822750fee7d2752910ea19d). The request is 200 and receiving the data it's all ok, but my table isn't rendering and the `data `in `tableData `is null. 

I want to integrate vuetable-2 to [Vue Admin](https://github.com/vue-bulma/vue-admin).

Can please anyone help! 
Thanks.

**Comment by ratiw** [comment]
@pwnz22 Everything seems fine to me. It's really hard to tell what went wrong unless you can show me the code.

**Comment by pwnz22** [comment]
Okay, here is my code.
```
<template>
  <div>
    <vuetable ref="vuetable"
              api-url="http://yurist-api.ils-team.ru/api/admin/questions"
              :fields="fields"
    ></vuetable>
  </div>
</template>

<script>
  import Vuetable from 'vuetable-2/src/components/Vuetable'

  export default {
    name: 'questions',
    components: {
      Vuetable
    },

    data () {
      return {
        apiUrl: allQuestionsURL,
        fields: [
          {
            name: 'title',
            title: 'Заголовок'
          }
        ]
      }
    }
  }
</script>
```

**Comment by coderabsolute** [comment]
Wondering is it possible to completely ignore the VueResource but use Axios instead, can vuetable work with Axios alone?

**Comment by ratiw** [comment]
@coderabsolute Vuetable is going to switch to axios in the next release. You can check out the develop branch if you wish to learn more.

@pwnz22 Are you sure you're using the code from `develop` branch?

**Comment by pwnz22** [comment]
@ratiw No, i just switched to axios manually. Then i will try the `develop `branch.

**Comment by coderabsolute** [comment]
It would also be nice to allow us to pass the object really and then render that if that all make sense..

**Comment by ratiw** [comment]
@coderabsolute It's in there as well, but with limited functionality.

**Comment by pwnz22** [comment]
@coderabsolute I think you must read documentation and see code.

**Comment by ratiw** [comment]
@pwnz22 @coderabsolute Sorry for the documentation. I'm trying my best to put something up within a week or so.

**Comment by pwnz22** [comment]
@ratiw I tried develop branch. But it doesnt make sense. 
![img](https://i.gyazo.com/08bd7ed48d10cd8b71e1b37b3f4f84f7.png) . Maybe i have the **OPTIONS** request?)

**Comment by ratiw** [comment]
@pwnz22 What doesn't make sense?

**Comment by pwnz22** [comment]
@ratiw I mean the request status is 200 but tableData is null :(

**Comment by ratiw** [comment]
Yeah, doesn't make sense. Did you make any other change to the code? Do you use vue-router?

**Comment by pwnz22** [comment]
@ratiw No, i didn't change the code. Yes, i'm using vue-router.

**Comment by ratiw** [comment]
Can you test without vue-router? I've heard some problems with vue-router, not sure if they're applicable to your case.

**Comment by pwnz22** [comment]
@ratiw Unfortunately without vue-router it did not worked :(

**Comment by ratiw** [comment]
That's really strange. If you could put the relevant code on github, maybe I can look into it.

**Comment by pwnz22** [comment]
@ratiw Okay, here is where i put [vuetable-2](https://github.com/pwnz22/yurist_admin/blob/master/client/components/layout/AppMain.vue)

**Comment by ratiw** [comment]
Looking at your `packages.json`, it's still pulling from the `master` branch. Did you replace the code in `node_modules` directory with the one from `develop` branch?

**Comment by pwnz22** [comment]
@ratiw Of course, i have completely deleted files from `node_modules` and cloned the `vuetable-2` repository, after that  run `git checkout develop` command.

**Comment by ratiw** [comment]
@pwnz22 VueDevtool has captured `load-error` event. The console dump of the error is like this
```
load-error TypeError: Cannot read property 'token' of undefined
    at Auth.response (eval at <anonymous> (app.js:622), <anonymous>:51:27)
    at Auth._responseIntercept (eval at <anonymous> (app.js:470), <anonymous>:115:44)
    at eval (eval at <anonymous> (app.js:458), <anonymous>:20:13)
```

**Comment by ratiw** [comment]
@pwnz22 You can use this in `package.json` to make yarn fetch the develop branch

```json
    "vuetable-2": "git://github.com/ratiw/vuetable-2.git#develop",
```

**Comment by pwnz22** [comment]
@ratiw I did so, but nothing changes :(.

**Comment by ratiw** [comment]
Please see the previous post about the error from `Auth` object regarding `token of undefined`

**Comment by pwnz22** [comment]
@ratiw So strange, but it worked. When i comment the [websanova/vue-auth](https://github.com/websanova/vue-auth). Any ideas how can i use `vuetable-2` with this package?)

**Comment by ratiw** [comment]
@pwnz22 Not really, sorry. Try inspecting the object that you reference the `token` to find out why it is `undefined`.

**Comment by pwnz22** [comment]
@ratiw Okay, many thanks for helping)
