### ISSUE TITLE
error on ie11 / method forEach

### ISSUE THREAD

**Issue by jagDanJu** [ratiw/vuetable-2#107]
Hey,

i am getting the following error at IE11...
At Chrome & FF everything works fine.

![image](https://cloud.githubusercontent.com/assets/3613218/24966977/cf413770-1fa8-11e7-881b-812be3eba6de.png)

Can anyone help me?

Thanks.

**Comment by ratiw** [comment]
@jagDanJu The fix has already been submitted [here](https://github.com/ratiw/vuetable-2/pull/66) and already applied in `develop` branch.

**Comment by jagDanJu** [comment]
@ratiw Nice! It works. Thanks.
