### ISSUE TITLE
How to I refresh the Data within Vuetable?

### ISSUE THREAD

**Issue by coderabsolute** [ratiw/vuetable-2#114]
Here is my gist, am calling the fetchData function but the Vuetable doesn't refresh the data. Not sure what is missing over here?

https://gist.github.com/coderabsolute/a75a32b1237994f4ad708df90f3585d9

**Comment by cristijora** [comment]
For retrieving data it should be sufficient to have the api url only.
Do you have issues when deleting/editing items?
You can use `this.$refs.vuetable.refresh()` to force trigger an api call. that will returned the new items or access the tableData within the component and delete/edit your element based on some index.

**Comment by coderabsolute** [comment]
`this.$refs.vuetable.refresh()` has solved the issue. Thanks!

**Comment by DominusKelvin** [comment]
Thanks. This would be solving a problem I had

**Comment by goarun112** [comment]
`this.$refs.vuetable.refresh()` is not working for me I'm using graphql endpoint to the data table.how to `reload()` or `refresh()` the data table
