### ISSUE TITLE
hi, this project is very nice

### ISSUE THREAD

**Issue by imagine10255** [ratiw/vuetable-2#12]
Hi, This project is very nice.
I just started learning vue js, Beginning with version 2.

the vuetable (by vue1) is full, but vuetable-2 not package ( in vuetable.js).
will I need to encapsulate him ?
I hope this can get better and better

this is my exercise project, this your package
https://github.com/imagine10255/laravel53-vuejs2-jwt-auth/blob/master/resources/assets/js/components/VuetableDemo1.vue

thinks.

**Comment by ratiw** [comment]
@imagine10255 Thanks. 

The best way to install vuetable-2 at the moment is via NPM. I still haven't decided whether to package it as js library as in version 1.

**Comment by imagine10255** [comment]
thank you for your reply

**Comment by gmsa** [comment]
why not package it? whats the downside?

**Comment by ratiw** [comment]
@gmsa I don't really see any downside. I just don't how to do it yet and have not enough time to research on how to do it. If you can help, it'd really be appreciated.

**Comment by syshex** [comment]
@ratiw so this is not happening anytime soon, right? not having a packaged version, is a total dealbreaker for me. Was using vuetable1 which has compat issues with ie11, which were not mentioned on the README.md at the time I grabbed it .

**Comment by ratiw** [comment]
@syshex I think so. Unless someone is willing to help on that. I did the best I could for the time I have, sorry.
