### ISSUE TITLE
Pagination css.icon problem

### ISSUE THREAD

**Issue by digitalmind** [ratiw/vuetable-2#124]
I have been trying to use the vuetable-2 with my laravel 5.4 project. I have managed to get and display the data via rest api. However when it tries to use pagination I get 

> [Vue warn]: Error in render function: 
(found in <VuetablePagination> at /Users/username/Sites/akademi/node_modules/vuetable-2/src/components/VuetablePagination.vue)

> app.js:6919 TypeError: Cannot read property 'first' of undefined

I traced the error back to the 
`<i v-if="css.icons.first != ''" :class="[css.icons.first]"></i>
        <span v-else>&laquo;</span>` 
and similar lines with css.icons object within the VuetablePagination.vue and when I remove those lines it works perfectly without the glyphicons. 
What am I missing?

**Comment by ratiw** [comment]
@digitalmind There are some changes in the `css` prop in v1.6.0 that might cause the problem to your existing code prior to v1.6.0. Please check out the [release note](https://github.com/ratiw/vuetable-2/releases/tag/v1.6.0). And see the example on using Bootstrap CSS with Vuetable-2 in [this jsfiddle](https://jsfiddle.net/ratiw/wzk251aq/1/).

**Comment by digitalmind** [comment]
Thanks a lot, when I followed the jsfiddle it worked perfectly.

**Comment by NicksonYap** [comment]
It took me a long time to realise, the `icons` prop should be inside the `pagination` prop which is inside the `css` prop.

```
css: {
    ...
    pagination: {
        ...
        icons: {
        }
    }
}
```
