### ISSUE TITLE
Add new item to every props 

### ISSUE THREAD

**Issue by leonfather** [ratiw/vuetable-2#128]
Hello Ratiw, I don't know how to add new item to the existing props in slot?

What i have now :
`{ "rowData": { "field1": "Content1",   "field2": "Content2",   "field3": "Content3" }, "rowIndex": 0 }
`
What i want : 
`{ "rowData": { "field1": "Content1",   "field2": "Content2",   "field3": "Content3" }, "rowIndex": 0, "action": "show" }
`
I need to add new item ("action": "show") to every props object because i need this item to show or hide action. How can i do this?

**Comment by leonfather** [comment]
I try to move forward while waiting for you to answer me and I met another problem,
First i have a vuetable for products and i need to show details so for each row i use "rowIndex" inside of "action" (Until you give me solution for that).
I will explain more :
I create a slot named details and for each row i get this object from props object from my slot :
`{ "rowData": { "field1": "Content1", "field2": "Content2", "field3": "Content3" }, "rowIndex": 0 }`
My slot (MyVuetable.vue):
```
<template slot="details" scope="props">
    <div>
        <a v-if="props.rowIndex == "more" @click="showDetails(props)">Show</a>
        <a v-if="props.rowIndex == "less" @click="showDetails(props)">Less</a>
        {{ props }}
        <p v-for="product in products">
            <span v-for="prod in product[props.rowData.product_id]">
                {{ prod.name }} : {{ prod.price }} <br />
            </span>
        </p>
    </div>
</template>
```
In my methods i create this method to show details :
```
showDetails(props){
    if(props.rowIndex == 'more'){
        delete this.products[props.rowData.inventory_id]
        props["rowIndex"] = 'less'
        console.log(props)
        this.$http.post('/api/details', {id: props.rowData.product_id}).then((response) => {
            this.products.push({[props.rowData.product_id] : response.data})
        });
    }else if(this.rowIndex == 'less'){
        // Here i will delete details row from products
    }
}
```
So Probleme that i face are: 
1-  how can i set rowIndex to more for all rows when vuetable mounted, Or how can i add "action": "more" to props.
2- When i'm affecting less to rowIndex by props["rowIndex"] = 'less', It does not apply. Or when i show {{ props }} in my slot i get the old value.

Ratiw I appreciate all kind of hepl, Thank you in advance

**Comment by ratiw** [comment]
@leonfather 

You "cannot" add anything to the `props`. The `props` is where Vuetable passes its row data and row index to the slot/component. So, trying to manipulate or change the `rowIndex` value will not work as well. The `rowIndex` is the index number of the row in the data and you should not be able to manipulate it.

You should consider using [Detail Row](https://github.com/ratiw/vuetable-2/wiki/Detail-Row) instead of trying to use slot because that is what it is designed for. See the tutorial [here](https://github.com/ratiw/vuetable-2-tutorial/blob/master/doc/lesson-12.md).

**Comment by leonfather** [comment]
Thank you so much for your answer, I tried to use detail row but i get this warning in my console: 

`You need to define unique row identifier in order for detail-row feature to work. Use `track-by` prop to define one!`

```
<vuetable
            ref="vuetable"
            api-url="/api/inventory/history"
            :fields="fields"
            pagination-path=""
            :css="css.table"
            :sort-order="sortOrder"
            :multi-sort="true"
            :per-page="perPage"
            detail-row-="inventoryDetails"
            detail-row-component="my-detail-row"
            :append-params="moreParams"
            @vuetable:cell-clicked="onCellClicked"
            @vuetable:pagination-data="onPaginationData"
        >
```

**Comment by ratiw** [comment]
If your data do not contain `id` column, you need to use `track-by` prop to set the name of the column that can uniquely identify each row.

Please see the tutorial [here](https://github.com/ratiw/vuetable-2-tutorial/blob/master/doc/lesson-12.md).

**Comment by leonfather** [comment]
Thank you
