### ISSUE TITLE
Filter is not contextually limited to one instance of Vuetable

### ISSUE THREAD

**Issue by OleVik** [ratiw/vuetable-2#129]
I followed the [tutorial](https://github.com/ratiw/vuetable-2-tutorial/tree/master/doc) and set up two Vuetables with their own separate API-endpoints, each with full configuration including pagination, sorting, and filtering. However, when both are included on the same page their methods conflict:

```
onFilterSet(filterText) {
  this.moreParams.filter = filterText
  Vue.nextTick(() => this.$refs.vuetable.refresh())
},
onFilterReset() {
  delete this.moreParams.filter
  Vue.nextTick(() => this.$refs.vuetable.refresh())
}
```

Each component, in its separate .vue-file, applies these methods, but filtering in one Vuetable applies the filter to both tables, despite `refresh()` being applied through `this`. Sorting and pagination is not affected by the conflict, so I assume this is because of `Vue.nextTick()`. Can `nextTick()` be applied within the context of the component?

**Comment by ratiw** [comment]
@OleVik The tutorial is just to demonstrate how the filtering can be applied. If my guess is right, it is possible that you use `FilterBar.vue` for both of the Vuetable instances. 

`FilterBar` emits `filter-set` event to the interested parties (those who listen to this event) to notify that it just got a `filterText`and anyone who is interested should take it and do something.

So, if both of your component listen to `filter-set` event (via `this.$events.$on('filter-set'...)`), it will get the same `filterText` no matter which instance it came from.

The easiest fix is to use different event name for each Vuetable instance, e.g. `filter-set-one` and `filter-set-two`. The same is true for `filter-reset` event as well.

**Comment by OleVik** [comment]
I see, I got it working by implementing the contents of `FilterBar.vue` into `MyVuetable.vue` and renaming `filter-set` and `filter-reset` for all the filter-methods. Thanks for clarifying.

**Comment by clemsontiger** [comment]
@OleVik do you have a jsfiddle of it working? or at least some sample code? I'm having the same issue.

**Comment by OleVik** [comment]
I do not unfortunately, as I am using it in a project that is not currently online. To get it working I adjusted the emitted events to be `filter-set-first`, `filter-set-second`, and the same for reset, so that the filters have unique events to listen for.
