### ISSUE TITLE
how to use vuetable-2 at local JSON file ?

### ISSUE THREAD

**Issue by kawamataryo** [ratiw/vuetable-2#130]
Hello.

I want to use it at local JSON file.
I try this code.

```
<template>
  <vuetable ref="vuetable"
      api-url="../assets/test.json"
    :fields="fields"
  ></vuetable>
</template>

<script>
import Vuetable from 'vuetable-2/src/components/Vuetable'

export default {
  components: {
    Vuetable
  },
  data () {
    return {
      fields: [
        'name', 'email', 'birthdate',
        'address.line1', 'address.line2', 'address.zipcode'
      ]
    }
  }
}
</script>

```
file file structure.
<img width="370" alt="2017-05-05 9 37 09" src="https://cloud.githubusercontent.com/assets/11070996/25730330/c5466102-3176-11e7-8c20-ddbf0e8ff243.png">

Bad out this error.

<img width="1269" alt="2017-05-05 9 44 24" src="https://cloud.githubusercontent.com/assets/11070996/25730441/b9c09432-3177-11e7-82c2-ec582bb230bb.png">

please tell me how to use it at local JSON file.

thank you.

**Comment by cristijora** [comment]
If you want to use assets in vue-cli the best idea is to place them in the `static` folder. Move your json into `static` folder and request it with `/static/test.json`

**Comment by ratiw** [comment]
@kawamataryo You will have to use Data mode by setting `api-mode` to `false`, then supply your own local data via `data` prop. See this [codepen](https://codepen.io/ratiw/pen/LyLpow). 

You can also combine with what @cristijora has suggested to make your code cleaner.

Please be aware, though, that sorting, paging, and page sizing are not yet work in this mode.

```html
<vuetable
  :api-mode="false"
  :data="localData"
></vuetable>
```

**Comment by kawamataryo** [comment]
@ratiw @cristijora  Thank you so much. I'll try it.
