### ISSUE TITLE
How to change the text "No relevant data"

### ISSUE THREAD

**Issue by LiveLikeCounter** [ratiw/vuetable-2#132]
Hi, I would like to change the default text "No relevant data" on loading the table.
I've looked in the Wiki (https://github.com/ratiw/vuetable-2/wiki/), but I could not find it.

If it is'nt possible to change the detail-text, do you have tip to change it my own with javascript?

**Comment by cristijora** [comment]
Use `noDataTemplate` prop for `VuetablePaginationInfo` component 
https://github.com/ratiw/vuetable-2/blob/master/src/components/VuetablePaginationInfoMixin.vue

**Comment by LiveLikeCounter** [comment]
Thanks! This works now.
