### ISSUE TITLE
undefinedlinks and undefineddata error

### ISSUE THREAD

**Issue by LiveLikeCounter** [ratiw/vuetable-2#137]
I got my vuetable working except the pagination.
In order to make this work I changed the API result to the following requirements: https://github.com/ratiw/vue-table/wiki/Data-Format-(JSON)
But when done so, I've got some errors:
![vuetable-2 error](https://cloud.githubusercontent.com/assets/24720382/25916181/101e254c-35c4-11e7-9b8f-08303ede875e.jpg)

My HTML Vuetable code:
 <div class="row gutter-sm">

      <div class="col-md-12">
        <div class="vuetable-pagination ui basic segment grid">
          <vuetable-pagination-info ref="paginationInfoTop" noDataTemplate="Loading Facebook posts..."></vuetable-pagination-info>
          <vuetable-pagination ref="paginationTop" @vuetable-pagination:change-page="onChangePage"></vuetable-pagination>
        </div>
        <vuetable
          ref="vuetable"
          api-url="https://us-central1-amazings10s-145405.cloudfunctions.net/getFacebookPagePostsInfo?uid=vct8Mq7EF1Qzmcf3IWQO8cDiWcH3&fbpageid=674600022698736"
          :per-page="100"
          :fields="fields"
          data-path = ""
          pagination-path=""
          @vuetable:pagination-data="onPaginationData"
          @vuetable:cell-clicked="onCellClicked">
          <template slot="actions" scope="props">
            <div class="custom-actions">
              <button class="btn btn-primary btn-icon sq-24" @click="onAction('goto-item', props.rowData, props.rowIndex)"><span class="icon icon-external-link"></span></button>
              <button class="btn btn-primary btn-icon sq-24" @click="onAction('view-item', props.rowData, props.rowIndex)"><span class="icon icon-info"></span></button>
              <button class="btn btn-info btn-icon sq-24" @click="onAction('edit-item', props.rowData, props.rowIndex)"><span class="icon icon-edit"></span></button>
              <button class="btn btn-danger btn-icon sq-24" @click="onAction('delete-item', props.rowData, props.rowIndex)"><span class="icon icon-times"></span></button>
            </div>
          </template>
        </vuetable>
        <div class="vuetable-pagination ui basic segment grid">
          <vuetable-pagination-info ref="paginationInfo" noDataTemplate="Loading Facebook posts..."></vuetable-pagination-info>
          <vuetable-pagination ref="pagination" @vuetable-pagination:change-page="onChangePage"></vuetable-pagination>
        </div>
      </div>

    </div>

Do you have an idea?

**Comment by ratiw** [comment]
@LiveLikeCounter Check your console for error. Also, check `onPaginationData` as it is the place where components binding occurs.

**Comment by LiveLikeCounter** [comment]
@ratiw, thanks for your response.
I  checked it, no console-errors. The data is passing to the function:
![onpaginationdata](https://cloud.githubusercontent.com/assets/24720382/25933063/6cda00f2-3615-11e7-8ea8-407d4041622a.jpg)

When I pass the data as:
`[{
	"id": "674600022698736_791098314382239",
	"name": "Speedo shy",
	"created_time": "2017-05-11T04:01:00+0000",
	...
},
{
	"id": "674600022698736_788766651282072",
	"name": "Jake Boys",
	"created_time": "2017-05-06T21:50:00+0000",
	...
},
{
  ...
}]`

The data will show up:
![pure data](https://cloud.githubusercontent.com/assets/24720382/25933587/1d497b64-3618-11e7-8a41-0382d00b23cc.jpg)

But now I pass the data like:
`{
	"links": {
		"pagination": {
			"total": 500,
			"per_page": 100,
			"current_page": 1,
			"last_page": 5,
			"from": 1,
			"to": 100
		}
	},
	"data": [{
		"id": "674600022698736_791035437721860",
		"name": "Stuggy",
    ...
	},
	{
		"id": "674600022698736_790980594394011",
		"name": "Anto Sharp",
		...
	},
  {
    ...
  }]
}`

I got to this situation.
Do you see somethings I do wrong?

**Comment by ratiw** [comment]
When the data structure changes, you have to tell the change to Vuetable as well. In this case, you'll have to set `pagination-path="links.pagination"`. If the data is not at the root of the structure, you have to set `data-path` accordingly as well.

**Comment by LiveLikeCounter** [comment]
Thanks for your tip! It works now.
![result](https://cloud.githubusercontent.com/assets/24720382/25935159/f00bc742-3621-11e7-82a2-ee5ef2b7b460.jpg)
