### ISSUE TITLE
How to add api keys to API end-point headers?

### ISSUE THREAD

**Issue by adavie1** [ratiw/vuetable-2#139]
Hi,
I would like to improve the security of my application- I've got the Larvel backend on a separate server, and all the calls to `XXX.XX/api/v1/YYY` are working fine.

However, I would like to make use of Laravel's user registration etc and that requires that I call the end-point with an API key.

Searched the docs, can't seem to see where to do that. Or is this an axios configuration thing?
Thanks  in advance.
Anthony

**Comment by ratiw** [comment]
@adavie1 It is supposed to be the `axios` thing. In v1.3 that uses vue-resource, this can be done by configuring the interceptor with vue-resource. I believe it should be the same with axios.

**Comment by adavie1** [comment]
Thanks, that's what I susepcted.
