### ISSUE TITLE
Pagination not show v1.6.0

### ISSUE THREAD

**Issue by iulian34** [ratiw/vuetable-2#141]
Hello, 
I was use until now vuetable-2  v1.3.0, I have update to v1.6.0 and pagination is not show any more. 

> <template>
    <div class="panel panel-default">
        <div class="panel-heading">Clients</div>
        <div class="panel-body">
            <filter-bar-clients></filter-bar-clients>
            <vuetable ref="vuetable"
                      api-url="api/clients"
                      :fields="fields"
                      pagination-path=""
                      :css="css.table"
                      :sort-order="sortOrder"
                      :per-page="10"
                      :multi-sort="true"
                      :append-params="moreParams"
                      @vuetable:cell-clicked="onCellClicked"
                      @vuetable:pagination-data="onPaginationData"
            ></vuetable>
            <div class="vuetable-pagination">
                <vuetable-pagination-info ref="paginationInfo"
                                          info-class="pagination-info"
                ></vuetable-pagination-info>
                <vuetable-pagination ref="pagination"
                                     :css="css.pagination"
                                     :icons="css.icons"
                                     @vuetable-pagination:change-page="onChangePage"
                ></vuetable-pagination>
            </div>
        </div>
    </div>
</template>

> <script>
    import accounting from 'accounting'
    import moment from 'moment';
    import ClientsActions from "./ClientActions";
    Vue.component('clients-actions', ClientsActions);
    export default {
        data () {
            return {
                css: {
                    table: {
                        tableClass: 'table table-bordered table-striped table-hover',
                        ascendingIcon: 'glyphicon glyphicon-chevron-up',
                        descendingIcon: 'glyphicon glyphicon-chevron-down'
                    },
                    pagination: {
                        wrapperClass: 'pagination',
                        activeClass: 'active',
                        disabledClass: 'disabled',
                        pageClass: 'page',
                        linkClass: 'link',
                    },
                    icons: {
                        first: 'glyphicon glyphicon-step-backward',
                        prev: 'glyphicon glyphicon-chevron-left',
                        next: 'glyphicon glyphicon-chevron-right',
                        last: 'glyphicon glyphicon-step-forward',
                    },
                },
                fields: [
                    {
                        name: '__sequence',
                        title: '#',
                        titleClass: 'text-right',
                        dataClass: 'text-right'
                    },
                    {
                        name: 'name',
                        title: 'Name',
                        sortField: 'name',
                    },
                    {
                        name: 'email',
                        sortField: 'email'
                    },
                    {
                        name: 'phone',
                        title: 'Phone',
                        sortField: 'phone'
                    },
                    {
                        name: 'birthday',
                        sortField: 'birthday',
                        title: 'Birthday',
                        titleClass: 'text-center',
                        dataClass: 'text-center',
                        callback: 'formatDate|YYYY-MM-DD'
                    },
                    {
                        name: '__component:clients-actions',
                        title: 'Actions',
                        titleClass: 'text-center',
                        dataClass: 'text-center'
                    }
                ],
                sortOrder: [
                    { field: 'id', sortField: 'id', direction: 'desc'}
                ],
                moreParams: {}
            }
        },
        methods: {
            allcap (value) {
                return value.toUpperCase()
            },
            formatNumber (value) {
                return accounting.formatNumber(value, 2)
            },
            formatDate (value, fmt = 'D MMM YYYY') {
                return (value == null)
                    ? ''
                    : moment(value, 'YYYY-MM-DD').format(fmt)
            },
            onPaginationData (paginationData) {
                this.$refs.pagination.setPaginationData(paginationData)
                this.$refs.paginationInfo.setPaginationData(paginationData)
            },
            onChangePage (page) {
                this.$refs.vuetable.changePage(page)
            },
            onCellClicked (data, field, event) {
                console.log('cellClicked: ', field.name)
                this.$refs.vuetable.toggleDetailRow(data.id)
            },
        },
        events: {
            'filter-set-clients' (filterText) {
                this.moreParams = {
                    filter: filterText
                }
                Vue.nextTick( () => this.$refs.vuetable.refresh() )
            },
            'filter-reset-clients' () {
                this.moreParams = {}
                Vue.nextTick( () => this.$refs.vuetable.refresh() )
            }
        }
    }
</script>

> <style>
    .pagination {
        margin: 0;
        float: right;
    }
    .pagination a.page {
        border: 1px solid lightgray;
        border-radius: 3px;
        padding: 5px 10px;
        margin-right: 2px;
    }
    .pagination a.page.active {
        color: white;
        background-color: #337ab7;
        border: 1px solid lightgray;
        border-radius: 3px;
        padding: 5px 10px;
        margin-right: 2px;
    }
    .pagination a.btn-nav {
        border: 1px solid lightgray;
        border-radius: 3px;
        padding: 5px 7px;
        margin-right: 2px;
    }
    .pagination a.btn-nav.disabled {
        color: lightgray;
        border: 1px solid lightgray;
        border-radius: 3px;
        padding: 5px 7px;
        margin-right: 2px;
        cursor: not-allowed;
    }
    .pagination-info {
        float: left;
    }
</style>

**Comment by DBroquin** [comment]
Hello ! 

The css prop has changed in 1.6.0, see the Breaking changes in the readme to know how to update your code ;)

**Comment by iulian34** [comment]
Hello @DBroquin ,
Yes you are right. 
Thank you
