### ISSUE TITLE
[Question] Can I dynamically change the dataClass of each row and column?

### ISSUE THREAD

**Issue by larryu** [ratiw/vuetable-2#148]
Hi @ratiw I wanna change the background color of the column based on some conditions, the callback method can be used to do some format, is there any way to change the dataClass or to bind class outside the vuetable?

**Comment by ratiw** [comment]
@larryu You might be able to do that, but it wouldn't be easy.

In the callback function, you need to search `tableFields` for the column index, then use that to change the `dataClass` to whatever according to your condition. Or you could write a component to do that.

```javascript
columnACallback (value) {
  // since you already knew which column this is
  // you should be able to loop/filter the tableFields to search for the column index
  let idx = this.$refs.vuetable.tableFields.forEach( function(field, index) {
    return (field.name === 'column_a') ? index : -1
  })

  this.$refs.vuetable.tableFields[idx].dataClass = 'css-class-for-something'

  return value
}
``` 

It is not recommended though as it is too much troublesome.

But if you want to change the background color of the row, you can use [`row-class`](https://github.com/ratiw/vuetable-2/wiki/Vuetable-Properties#-row-class) prop to do just that.

**Comment by larryu** [comment]
@ratiw Thanks for the suggestion. I'll give it a short.

**Comment by larryu** [comment]
@ratiw row-class solves my problem. Thanks mate.
