### ISSUE TITLE
Property or method "css" is not defined on the instance but referenced during render

### ISSUE THREAD

**Issue by siarheipashkevich** [ratiw/vuetable-2#15]
Hello, I'm trying the "Property or method "css" is not defined on the instance but referenced during render" when start new vuetable-2 component. 
My settings: 
[http://joxi.ru/5mddy9OSvxMPbm.jpg](http://joxi.ru/5mddy9OSvxMPbm.jpg)
and in the console I get the error:
[http://joxi.ru/8239qYaH6Ekq6r.jpg](http://joxi.ru/8239qYaH6Ekq6r.jpg)

How can I resolve that?
Thanks.

**Comment by herzcthu** [comment]
I have same problem. Do you have any solution?

**Comment by siarheipashkevich** [comment]
I resolved that problem so:
In the rood directory I removed node_modules folder and install the npm packages again.
