### ISSUE TITLE
Possiblity to disable reactive api-url

### ISSUE THREAD

**Issue by kiltec** [ratiw/vuetable-2#152]
First off, thank you very much for vuetable, saved us a ton of time!

But now on to my suggestions:

The api-url being reactive should configurable, for example via a `reactive-api-url` property.
If set to false, the watcher for `apiUrl` will simply return without calling `refresh`.

Unfortunately, it isn't possible to override the watcher by inheriting from/extending vuetable because hooks like `watch` are merged such that they're executed sequentially (I've tried), so the original code still gets executed and thus vuetable refreshed,
The watcher could be overridden, if the code inside the watcher was in a method, since methods _will_ get overriden by child methods.

Here's why we need this:
In our app, we let the user filter the data rendered by vuetable - that is, it's possible to request only data whose column1 contains value `foo` and column2 contains value `bar`.
There's a form which the users completes with the desired filters and then hits a button to apply the filters (or start the search). Those filters are passed to vuetable as `append-params`.

Additionally, in the same form the user can switch the data source and here's the problem, the ID of the data source is a property `dataSourceId` of vuetable's parent which is in turn part of a computed property `apiUrl` of vuetable's parent which is bound to vuetable's `api-url`.

Before version 1.6.0 we would simply call `refresh` on vuetable when the filter button was clicked.
But now this will trigger two requests, one because of our explicit call of `loadData` and one because we set the `dataSourceId` which then changes the computed property which then triggers another automatic loading of the data.
And that's something that we'd like to avoid.

Here's some simplified code to illustrate our use case:
```
<template>
    <!-- filter form omitted for brevity  -->

    <vuetable
            ref="vuetable"
            :api-url="apiUrl"
            :append-params="appendParams">
    </vuetable>
</template>

<script>
    export default {
        data() {
            return {
                // bound to html input elements
                dataSourceId: 1, // if this is changed by the user in the form via a dropdown, vuetable will automatically refresh
                filterColumn1: '',
                filterColumn2: '',
            }
        },

        computed: {
            apiUrl() {
                return `/foo/bar/${this.dataSourceId}`;
            },

            appendParams() {
                return {
                    filterCol1: this.filterColumn1,
                    filterCol2: this.filterColumn2,
                }
            },
        },

        methods: {
            onFilterButtonClicked() {
		// Other things happen here
                this.$refs.vuetable.refresh();
            },
        }
    }
</script>
```

Note that this is a very simplified code example, in our real code the situation is more complicated making it very difficult to take the reactive apiUrl into account.

What do you think?
I'd be more than willing to issue a PR for this, if this gets a go. :)

**Comment by ratiw** [comment]
@kiltec Thanks for explaining it detail. Your point is really valid and I didn't think of that. Please send the PR based on that `develop` branch and I'll look into it. :)

**Comment by kiltec** [comment]
Changed got merged, so closing this issue.

**Comment by mkantautas** [comment]
Just store apiUrl in the `data` property, this way it won't be reactive
