### ISSUE TITLE
dist vuetable-2.js un-minified version?

### ISSUE THREAD

**Issue by clemsontiger** [ratiw/vuetable-2#153]
do you have an expanded vuetable-2.js file you could also make available in the dist folder? thanks!

**Comment by cristijora** [comment]
@ratiw You can conditionally add `plugins` inside webpack.build.config based on an env variable
```
var outputFileName = "vuetable-2.js"
var plugins = [

    new webpack.BannerPlugin(banner, {
        raw: true
    }),
    new ExtractTextPlugin(cssFileName, { allChunks: true }),
    new StatsPlugin("../stats.json", {
        chunkModules: true
        //exclude: [/node_modules[\\\/]react/]
    })
];

if(process.env.minify === "true") {
  outputFileName  = "vuetable0-2,min.js";
    var minifyPlugins = [
        new webpack.DefinePlugin({
            "process.env" : {
                NODE_ENV : JSON.stringify("production")
            }
        }),
        new webpack.optimize.UglifyJsPlugin({
            compress: {
                warnings: false
            }
        }),
        new webpack.optimize.DedupePlugin()
    ];
    
    plugins = plugins.concat(minifyPlugins)

}


//build config
module.exports = [
 //other code
 output:{
  // other code
  filename: outputFileName
 },
 plugins:plugins,
]

```
Usage:
```
"build:bundle": "webpack --progress --config build/webpack.build.config.js",
"build:bundle-min:"cross-env minify=true webpack --progress --config build/webpack.build.config.js"
```

**Comment by ratiw** [comment]
@cristijora Thanks as always. However, is it possible to just run `build:bundle` and it generates both the minify and un-minify version?

**Comment by cristijora** [comment]
```
"build:bundle-simple": "webpack --progress --config build/webpack.build.config.js",
"build:bundle-min:"cross-env minify=true webpack --progress --config build/webpack.build.config.js",
"build:bundle": "npm run build:bundle-simple && npm run build:bundle-min"
```
You can create a new npm task which will run both

**Comment by ratiw** [comment]
@cristijora, Thanks a lot 👍

**Comment by ratiw** [comment]
@cristijora I've updated the webpack config to the one the generated by `vue-cli` v2.8.0 and now the `build:bundle` is no longer working. Can you please help look at it and send a PR for the fix? Sorry, for the trouble.

**Comment by cristijora** [comment]
Shall I use develop branch ?

**Comment by ratiw** [comment]
@cristijora Yes. Thank you.

**Comment by cristijora** [comment]
Ok. The issue is that webpack.build.config.js is using webpack 1 and vue-cli uses webpack 2. I will make the necessary changes to port that config to webpack 2 also.

**Comment by ratiw** [comment]
Thank you so much. Hope I didn't mess things up too much.

**Comment by clemsontiger** [comment]
closing as I see you have [vuetable-2-full.js](https://github.com/ratiw/vuetable-2/blob/master/dist/vuetable-2-full.js) now. thanks.
