### ISSUE TITLE
:row-class question

### ISSUE THREAD

**Issue by clemsontiger** [ratiw/vuetable-2#154]
Based on [documentation](https://github.com/ratiw/vuetable-2/wiki/Vuetable-Properties#-row-class), I was understanding that I could simply pass :row-class a class name (string) and not a method/function? 

I can only get it to work if I define a method to use for row-class.

here's a jsfiddle: [http://jsfiddle.net/clemsontiger/9cnaoy0t/4/](http://jsfiddle.net/clemsontiger/9cnaoy0t/4/)

**Comment by ratiw** [comment]
@clemsontiger To pass in a string, you must not use `v-bind`. 

```html
<vuetable
  row-class="my-css-class"
></vuetable>
```
> No colon (`:`) in front of `row-class`

**Comment by clemsontiger** [comment]
That did it. What's the difference in properties that use the colon and those that don't?
