### ISSUE TITLE
How to add table footer?

### ISSUE THREAD

**Issue by blackpuppy** [ratiw/vuetable-2#157]
Thanks for creating the vuetable-2 component!

Is there any way to add `<tfoot>` to hold sub totals for the fields?  Or is it possible to put `VuetablePagination` and `VuetablePaginationInfo` inside `<tfoot>`?

Thanks!
Zhu Ming

**Comment by ratiw** [comment]
@blackpuppy Not at the moment. You will have to mimic that using `<div>` and CSS to achieve that look. The reason is that it is hard to achieve the same look and behavior with `tfoot` in different CSS frameworks.

**Comment by blackpuppy** [comment]
No problem.  I will use `<div>` for now.  Thanks!
