### ISSUE TITLE
How do I implement filter in client-side?

### ISSUE THREAD

**Issue by jericopulvera** [ratiw/vuetable-2#165]
How do I implement filter in client-side?

is there any example of this?

**Comment by ratiw** [comment]
@jericopulvera Not at the moment. In the next release, you'll be able to implement your own filter in client-side via `data-manager`. You probably have to use array filter for that.

**Comment by glowens** [comment]
When do you expect the next release?

**Comment by ratiw** [comment]
@glowens Just release [v1.7.0](https://github.com/ratiw/vuetable-2/releases/tag/v1.7.0) today. Please check it out.
