### ISSUE TITLE
Multiple vuetables

### ISSUE THREAD

**Issue by clemsontiger** [ratiw/vuetable-2#171]
can more than 1 vuetable be setup on the same page? if so, how does one be sure loading, sorting, etc get triggered on each individual vuetable instead of on all?

it's probable we'll want to use more than one on a page, i.e. for a dashboard page showing different tables of data. 

note: i'm using the dist .js file for vuetable...

**Comment by ratiw** [comment]
@clemsontiger Technically, you can have more than 1 Vuetable instance on the same page and it should work without interfering with each other if the API endpoint is not the same. However, you will have to `ref` differently and be careful about your logic when interacting with each API endpoint.

I've demonstrated in the previous version of Vuetable [here](https://github.com/ratiw/vue-table/issues/23) which work with Vue 1.x. But the concept is more or less the same, you'll have to try out in a small test project (where the code and be shown). And if you're stuck, I can see the code and give you the advice.

**Comment by cristijora** [comment]
@clemsontiger For example I extracted all vuetable related stuff into one component (sorting, refresh etc) and pass only the table related props to it (columns, api url, sorting data) without having to worry too much about loading/sorting works internally.

**Comment by clemsontiger** [comment]
Thanks all. I'll spend more time on it.. a working example of multiple vuetables along with refreshing and/or searching individually would be awesome if you have the time, but understand if you do not.

**Comment by clemsontiger** [comment]
@cristijora do you have an example showing of how you "... extracted all vuetable related stuff into one component (sorting, refresh etc) and pass only the table related props to it (columns, api url, sorting data) without having to worry too much about loading/sorting works internally."? I'd love to see how to setup independent vuetables this way.

**Comment by cristijora** [comment]
I don't have one but I can make a fiddle I guess

**Comment by clemsontiger** [comment]
@cristijora I'd be very appreciative.

**Comment by cristijora** [comment]
This could be a starting point http://jsfiddle.net/z11fe07p/2074/
Probably extracting the api url as an endpoint would also be a good idea. The main idea is to make a component together with pagination, sorting etc and then to extract the props which are meaningful (fields, api-url etc)

**Comment by clemsontiger** [comment]
Thank you. that's a big help to get me going.

**Comment by clemsontiger** [comment]
@cristijora humor me, but how do I set the a component prop directly instead of hooking it to the parent Vue? Trying to extract the api-url, but doesn't seem to work. http://jsfiddle.net/clemsontiger/g8oseayy/3/

thanks...

**Comment by cristijora** [comment]
You had some typos http://jsfiddle.net/g8oseayy/8/
Use `v-bind:prop="variableName"` if you reference a variable or shorthanded `:prop="variableName"`
`v-bind:api-url="apiUrl"` 
Use `prop="some string value"` if you want to reference a string directly
api-url="https://vuetable.ratiw.net/api/users"

**Comment by clemsontiger** [comment]
ugh, sorry. I'll try to stop bothering you with vue 101 questions. thanks again.

**Comment by cristijora** [comment]
Feel free to write on vuejs gitter channel https://gitter.im/vuejs/vue#utm_source=notification&utm_medium=email&utm_campaign=unread-notifications

Since these are more general vue related questions rather than vue-table. You can get a faster response there if you have a fiddle with you :)

**Comment by clemsontiger** [comment]
doing pretty good now, but can't seem to get it right to be able to define special fields via slots.  I followed the documentation at:  https://vuejs.org/v2/guide/components.html#Scoped-Slots and https://ratiw.github.io/vuetable-2/#/Special-Fields?id=-__slot

here's the fiddle that's not working: http://jsfiddle.net/clemsontiger/g8oseayy/9/

**Comment by clemsontiger** [comment]
@cristijora also not sure how to refresh the component from the parent Vue... for instance if one has a filter external to the component...

**Comment by ratiw** [comment]
@clemsontiger You cannot simply pass scoped slot down into the underlying component in template based component. You'll have to use render function based component only as pointed out [here](https://forum.vuejs.org/t/passthrough-scoped-slot-to-children-possible/5789).

But there are a few new lesson from [Vuetable Tutorial](https://github.com/ratiw/vuetable-2-tutorial/wiki) that will walk you through the process in [lesson 17](https://github.com/ratiw/vuetable-2-tutorial/wiki/lesson-17). I would suggest you started from lesson 14 so that you don't accidentally miss on anything.

**Comment by clemsontiger** [comment]
@ratiw thanks, this is helpful. one quick thing though, I'm trying to setup the filter with my component wrapper, and on the mounted it calls $on
 `this.$events.$on('filter-set', eventData => this.onFilterSet(eventData));`

 I'm getting a: "Cannot read property '$on' of undefined" Keep in mind i'm using the CDN dist javascript library. Do i have to reference $on some other way?

**Comment by clemsontiger** [comment]
@ratiw Also, in the tutorial you say "As of the current release of Vue 2.3, there is still no way to pass the scoped slot down into the component via template. " Does this mean a future version will alllow to pass scoped slot without the user of render? uses a template is much clearer to understand....

**Comment by ratiw** [comment]
@clemsontiger Did you install [`vue-events`](https://github.com/cklmercer/vue-events) as stated in the tutorial? The `$events` is only made available when you install `vue-events` plugin.

For the scoped slot, that's what I've read the answer from the Vue.js team member in the forum. I also thought that it is possible, but we'll have to wait and see. They might already have their hands full at the moment.

**Comment by clemsontiger** [comment]
@ratiw no, since I'm using the JavaScript vuetable-2.js file, I assumed vue-events was bundled in with it. I'm not sure but I think $emit works with cuetable-2.js, so not sure why $on does not. I guess I'll have to find a JavaScript vue-events.js file as well?

**Comment by ratiw** [comment]
@clemsontiger Please go through [this tutorial](https://github.com/ratiw/vuetable-2-tutorial/wiki/lesson-13).

**Comment by clemsontiger** [comment]
@ratiw, yes I saw this, but again I'm not using webpack to bundle everything, I'm using the standalone vue able-2.js file. I guess I'll have to find a non webpack vueevents.js file to include.... thanks

**Comment by ratiw** [comment]
For the published NPM package, you can almost always use https://unpkg.com/<package_name> to get that. Try [https://unpkg.com/vue-events](https://unpkg.com/vue-events).

Also, if the project exists on GitHub and the repo contains the `dist` file, you can pull those file using the following syntax as well.
```
https://rawgit.com/<username>/<pacakge_name>/<branch>/dist/<file>
```
For example, Vuetable-2
```
https://rawgit.com/ratiw/vuetable-2/master/dist/vuetable-2.css

https://rawgit.com/ratiw/vuetable-2/master/dist/vuetable-2.js

https://rawgit.com/ratiw/vuetable-2/master/dist/vuetable-2-full.js
```

**Comment by clemsontiger** [comment]
didn't know you could do that, thanks! really appreciate all the help.

**Comment by clemsontiger** [comment]
@ratiw great. I've got it all working now for single vuetable. Now just trying to determine how I can have multiple, separate filters for each vuetable.

**Comment by ratiw** [comment]
I think someone had already asked this question. try searching the issues, you might find the answer.

**Comment by clemsontiger** [comment]
@ratiw yes, I found it, thanks. Unfortunately it sounds like he got it to work by building the Filter component directly into his vuetable component, which I'd prefer not to do as we'll be implementing in a variety of way where the filtering content will not always be required and  when it is used, could differ depending on the scenario...

I'll go ahead and close this issue though, as I was successful in being able to setup multiple vuetables on the same page and each have its sorting, paging, and api source independent of the other. Along with getting the slots to work (albeit with using the render function).

Again, thanks for humoring me and helping me out, even though I'm not using vuetables in the typical webpack bundling way...

@cristijora really appreciate all your help as well.
