### ISSUE TITLE
data mode not working

### ISSUE THREAD

**Issue by tbyte80** [ratiw/vuetable-2#176]
Hello,
I am using vuetable-2 v1.6.3 via npm, and data mode seems not to be working in this version. Here is my Code:

`<vuetable ref="vuetable"
                              :api-mode="false"
                              :data="myData"
                              :fields="myFields"
                              pagination-path=""
                    ></vuetable>`

Table headers (myFields) are appearing correctly but the table body says: "No Data Available" . At first I thought I had a configuration mistake but on my research I found this codepen you supplied some time ago. There you can see the same issue:

https://codepen.io/ratiw/pen/LyLpow

Please advise :) .

**Comment by oriske** [comment]
Wie oft muss ich mich noch abmelden?
Der Quark interessiert mich nicht!

**Comment by ratiw** [comment]
@tbyte80 Use this updated [codepen](https://codepen.io/ratiw/project/editor/DzmJnA/) as a guide instead. Still finding time to finish tutorial on using Data mode.

**Comment by ratiw** [comment]
@tbyte80 Also, it appears that Vuetable does not handle the data array correctly. I'll tag this as a bug and work on it later.

**Comment by ratiw** [comment]
Fixed in v1.6.5
