### ISSUE TITLE
How set a global configuration?

### ISSUE THREAD

**Issue by arthurvasconcelos** [ratiw/vuetable-2#181]
So the problem is that I want to use vuetable but I don't want to repeat the right configuration every screen... I look in the issues and the documentation but cant find anything... how can I set a global/default configuration!?

**Comment by lgullestrup** [comment]
export your configuration into a file.

```
//vuetable-settings.js
export default {
    setting1: 'some-setting'
}
```

then anywhere you want to use these 'global settings, import them.

now in your component, you can do this
```
import vsettings from './<insert path here>/vuetable-settings'
export default (){
    data(){
        return {
            tableSettings: vsettings 
        }
    }
}
```

**Comment by arthurvasconcelos** [comment]
I ended up setting a mixin in Vue and this solved my problem. But thanks anyway @lgullestrup.

**Comment by lgullestrup** [comment]
mixins is another good solution :)
