### ISSUE TITLE
http-options doens't work

### ISSUE THREAD

**Issue by arthurvasconcelos** [ratiw/vuetable-2#182]
I'm trying to set a authorization property to my request header but nothing works... I've tried:

```javascript
    <vuetable ref="vuetable"
              :api-url="apiEndPoint('form-template')"
              :http-options="$http.defaults.headers"
              :fields="fields"
    >
```

```javascript
    <vuetable ref="vuetable"
              :api-url="apiEndPoint('form-template')"
              :http-options="$http.defaults.headers.common"
              :fields="fields"
    >
```

```javascript
    <vuetable ref="vuetable"
              :api-url="apiEndPoint('form-template')"
              :http-options="{ get: $http.defaults.headers.common }"
              :fields="fields"
    >
```
Any clue why?

**Comment by lgullestrup** [comment]
try doing :http-options="{ header: <header-options (JSON)> }

vuetables is using axios. the http-options is passes as the config to the request, so the object for http-options should follow the axios config.

https://github.com/mzabriskie/axios

note that the params overwritten before the request is made, so dont include parameters in the httpOptions propery, instead, put parameters in the :appendParams property

**Comment by ratiw** [comment]
@lgullestrup Can you help share your opinion on [this comment](https://github.com/ratiw/vuetable-2/issues/127#issuecomment-308414715)?

**Comment by arthurvasconcelos** [comment]
This worked like a charm! Thank you @lgullestrup!

**Comment by commititup** [comment]
```
<vuetable ref="vuetable"
                    :api-url= "apiurl"
                    http-options= "{headers:{'Authorization', 'Basic <token>'}}"
                    :fields="fields">
 </vuetable>
```
TypeError: "can't assign to property "params" on "{headers:{'Authorization', 'Basic <token>'}}": not an object"

How can i achieve this ?

**Comment by ratiw** [comment]
@onlineexamsystem Shouldn't you have a `:` in front of `http-options`?
