### ISSUE TITLE
using NPM, cannot get this to import.

### ISSUE THREAD

**Issue by jaketoolson** [ratiw/vuetable-2#19]
```
[14:30:26] gulp-notify: Browserify Failed!: Unexpected token

/node_modules/vuetable-2/src/components/Vuetable.vue:1
<template>
```

No matter what I do, whether I require or import, npm doesn't work

**Comment by ratiw** [comment]
@jaketoolson It seems like browserify does not know how to parse `.vue` file. I think it's the problem with configuration file. See [this](https://github.com/ratiw/vue-table/issues/12#issuecomment-216618411), it might help.

**Comment by jaketoolson** [comment]
@ratiw The package I use (vueify) is a wrapper over browserify and is therefore used for .vue files (I use it on all my .vue files).

**Comment by ratiw** [comment]
@jaketoolson But the error shows that it cannot parse `<template>`, which means vueify was not applied to `.vue` file. 

I still think that there is some problems with your configuration file.

**Comment by Dennis-Smurf** [comment]
I have the same problem.    
A small test to see if the vueify wrapper over browserify works:    
I copied the `vuetable.vue` file into my project, used `import Vuetable from './Vuetable.vue'` and then it worked!
![image](https://cloud.githubusercontent.com/assets/4238339/22111396/789d1004-de5f-11e6-846c-15cec92a06be.png)

**Comment by jaketoolson** [comment]
@Dennis-Smurf  @ratiw I had to do the same. This is the only NPM vue package that I still can't get to work.  I use 30 various 3rd party vue components through NPM, not a single problem. This one is still no bueno.

**Comment by ratiw** [comment]
@jaketoolson @Dennis-Smurf I really don't know how to help you guys on this as I do not use vueify myself. I used vue-cli to make this project so that I don't have to mess with webpack configuration. I would really love any suggestion on what is the problem and how to fix this.

**Comment by Dennis-Smurf** [comment]
Could it perhaps be that updates in the vue-cli breaks stuff? My version of vue-loader is `"vue-loader": "^10.0.0"`, yours  `"vue-loader": "8.5.2"`.  I used vue-cli: `vue init webpack`.

**Comment by pajtai** [comment]
I think the issue is that by default, browserify does not run any transforms on things in node_modules.

http://stackoverflow.com/a/16113666/186636

But even after adding browserify.transform, there is an error due to there being no index.js file. If you add an index.js, then the error is that a transform function is expected.

So, not really sure how to solve, but you would definitely have to add vuetable-2 to browserify.transform

https://github.com/substack/node-browserify#browserifytransform

**Comment by pajtai** [comment]
@ratiw I sent a PR that add the needed transforms to the package.json.
