### ISSUE TITLE
Class class based on formatter

### ISSUE THREAD

**Issue by SimplyCorey** [ratiw/vuetable-2#191]
Hello,

Thanks for the great Vue table.  I am trying to format the color of a field by using its value within the callback (format).  The application is for finance, and if the number is negative I would like for that field to become red.  Is this possible?

I also attempted to use the https://github.com/ratiw/vuetable-2/wiki/CSS-Styling#table-column-td but without any luck.  Thanks!

**Comment by lgullestrup** [comment]
you can define a callback in the columns array to style the text
https://github.com/ratiw/vuetable-2/wiki/Callbacks

example:

```
columns: [
    {
          name: finance,
          callback: 'IsinRed'
    }
],
.
.
.
methods: {
    IsinRed(value){
      if(value > 0){
           return '<span class="red-text">'+value+'</span>'
       }
       return value;
   }
}
```

This approach should work, i haven't tested it but it might lead you into the right direction?

**Comment by ratiw** [comment]
@SimplyCorey From the callback formatter, try returning the value inside a `<span>` or `<label>` with a css class, like so.

```javascript
  //...
  formatNumber (value) {
    return (value < 0) 
      ? `<span class="negative-number">${value}</span>` 
      : `<span>${value}</span>`
  }
```
```css
// CSS file

span.negative-number {
  color: red;
}
```

**Comment by SimplyCorey** [comment]
@ratiw @lgullestrup Thanks guys.  I was hoping to not have to hard code the tag in the function, but it will work :)
