### ISSUE TITLE
Custome Table header

### ISSUE THREAD

**Issue by T0miii** [ratiw/vuetable-2#193]
Hi,

is it possible to override the vuetable functions?
For example this one:

```
    renderTitle (field) {
      let title = (typeof field.title === 'undefined') ? field.name.replace('.', ' ') : field.title
      if (title.length > 0 && this.isInCurrentSortGroup(field)) {
        let style = `opacity:${this.sortIconOpacity(field)};position:relative;float:right`
        return title + ' ' + this.renderIconTag(['sort-icon', this.sortIcon(field)], `style="${style}"`)
      }
      return title
    },
```

I would like to make my own custom table headers so i can use custome sort up/down icons.

The HTML structure i need for my icons to show up looks like this:

`<i class="material-icons">arrow_drop_down</i>`

Or could i use the callback to override the html of the `<th>` ?

**Comment by ratiw** [comment]
@T0miii You can use [`render-icon`](https://github.com/ratiw/vuetable-2/wiki/Vuetable-Properties#-render-icon) to do that. Also, read [this lesson](https://github.com/ratiw/vuetable-2-tutorial/wiki/lesson-18) of the tutorial.

**Comment by T0miii** [comment]
Okay i Bookmarked that tutorial git page now, google you faild me again.
Thx for your help @ratiw :)

closing this.
