### ISSUE TITLE
Frontend filter

### ISSUE THREAD

**Issue by phamvanthanh** [ratiw/vuetable-2#199]
Hi @ratiw,
Does it support frontend filter?

**Comment by ratiw** [comment]
You have to implement the filter logic yourself, see the example [here](https://codepen.io/ratiw/project/editor/DzmJnA/). This is done via the `dataManager` function (as shown in `index.js`) specified in `data-manager` prop (as shown in `index.html`).

**Comment by phamvanthanh** [comment]
Many thanks @ratiw
