### ISSUE TITLE
GroupBy a column (enchantment)

### ISSUE THREAD

**Issue by LimitTech** [ratiw/vuetable-2#2]
How could would be if we had a group by column?

Something like this:
https://codepen.io/andrewcourtice/pen/VabXQV/

Thank you for your excellent package.

**Comment by LimitTech** [comment]
I don't know how to do a pull request but there are the changes I've done in your package in order to add groupBy feature (Excuse me because I'm not a vue expert and used something from https://codepen.io/andrewcourtice/pen/VabXQV/): 

Note that I *need* the group by feature, so I haven't added conditionals.

1. Make a computed variable

        filteredTableData: function () {
            var key = 'KEY'; // it could be a prop but I put here to show

            var groups = {
                data: this.tableData
            };

            if (this.tableData) {
                groups = {};
                for (var i = 0; i < this.tableData.length; i++) {
                    var row = this.tableData[i];
                    var cell = this.getObjectValue(row, key);
                    if (!groups.hasOwnProperty(cell)) {
                        groups[cell] = [];
                    }
                    groups[cell].push(row);
                }
            }

            return groups;
        }

2. Change template

         ....
        <tbody v-cloak>
        <template v-for="(groupitem, groupindex) in filteredTableData">
            <tr class='...'>
                {{ groupindex }}
            </tr>
            <tr v-for="(item, index) in groupitem" @click="onRowClicked(item, $event)" :render="onRowChanged(item)"

**Comment by ratiw** [comment]
@LimitTech You should first fork vuetable-2 into your own repo first. Then, use your forked repo in your code and make any change as you see fit. Make it work in your use case, then from your repo will see "New pull request" button showing up. From there, you can send the pull request to me.

**Comment by LimitTech** [comment]
Ok, sorry for changing spaces. I think it was done by PHPStorm automatically.

**Comment by tksumanth1994** [comment]
@LimitTech did you happen to find any workaround for this? I'm stuck at the same place. Need group by feature in vuetable-2.

**Comment by Hintzmann** [comment]
@LimitTech I am also interested in a "group by" feature in vuetable-2.

**Comment by ratiw** [comment]
You can find the link to the code @LimitTech has implemented in the above [Add groupBy feature](https://github.com/ratiw/vuetable-2/pull/5). However, please read through the comment to see its limitation as well.
