### ISSUE TITLE
How to use the method of the event emitted by the custom-action component ?

### ISSUE THREAD

**Issue by maryheng** [ratiw/vuetable-2#209]
Hi all,

I have a CustomActions component and because I want to make the component reusable, i want to invoke the method in another component, E.g. Staff.vue that has the vuetable in it. 

I have a problem where the method **(onActions method)** can't even be called in the Staff.vue.

This is my code in CustomActions.vue:
```
<div class="custom-actions">
  <button class="button is-info" @click="itemAction('action-item', rowData)">Edit</button>
</div>

export default { 
...
  methods: {
    itemAction (action, data) {
      this.$parent.$emit('onBtnClick', {action: action, data: data})
    }
}
```

This is my code in Staff.vue:
```
<my-vuetable
ref="vuetable"
:api-url="apiUrl"
:fields="fields"
@onBtnClick="onActions"
></my-vuetable>

export default { 
...
  methods: {
    onActions (action, data) {
      console.log(data)
    }
  }
}
```

How do I go about fixing this problem? Thanks for your help!

**Comment by alperencaliskan** [comment]
Emitting event to parent's parent should solve the problem. CustomActions -> vuetable -> my-vuetable
```javascript
this.$parent.$parent.$emit('onBtnClick', {action: action, data: data})
```

**Comment by maryheng** [comment]
Hi @alperencaliskan , 

Sorry but I don't really understand... I'm quite new to VueJS 2. 

I have a CustomAction.vue is a component by itself and let's say Staff.vue. CustomAction.vue is the child while the Staff.vue is the parent(?) I have a component which is, MyVueTable.vue which just imports CustomAction and sets it as a component. 

So I don't quite understand who is the parent's parent...

**Comment by maryheng** [comment]
Hi again @alperencaliskan ,

I finally understood what you said about CustomActions -> vuetable -> my-vuetable. Sorry for my lack of knowledge!

But thank you, this works 👍

**Comment by alperencaliskan** [comment]
No worries, i am also new to vuejs. Happened to come across this problem a few hours ago just like you :)
