### ISSUE TITLE
Display multiple objects from a nested json to a cell data in Vuetable

### ISSUE THREAD

**Issue by maryheng** [ratiw/vuetable-2#212]
Hi all,

Is there a way to display multiple objects from a nested json to a cell data in Vuetable?

**Response payload from server:**
![response1](https://user-images.githubusercontent.com/13627091/28498350-b76ae1b2-6fcd-11e7-8cf8-749dbc5ae725.png)

Current behaviour:
<img width="389" alt="screen shot 2017-07-24 at 1 06 12 am" src="https://user-images.githubusercontent.com/13627091/28501334-6005be12-700c-11e7-848e-dc952ae49bec.png">

**Expected result:**
![expected table](https://user-images.githubusercontent.com/13627091/28498324-250a7260-6fcd-11e7-815e-880c072f5dbe.png)

**Update:**
In my Fields property,
I added a callback function:

```
    {
      name: 'SubCategories',
      title: 'SubCategories',
      callback: 'combineSubCat'
    }
```
And, this is my method:

```
  methods: {
    combineSubCat (value) {
      return value.map(d => {
        return {
          subCategories: d.SubCategories.reduce((acc, c) => {
            return acc ? acc + ', ' + c.subCategoryName : c.subCategoryName
          }, '')
        }
      })
    }
  }
```
But it still doesn't work. Any idea why?

**Comment by maryheng** [comment]
In my Fields property,
I added a callback function:

        {
          name: 'SubCategories',
          title: 'SubCategories',
          callback: 'combineSubCat'
        }
And, this is my method:

  methods: {
    combineSubCat (value) {
      return value.map(d => {
        return {
          subCategories: d.SubCategories.reduce((acc, c) => {
            return acc ? acc + ', ' + c.subCategoryName : c.subCategoryName
          }, '')
        }
      })
    }
  }
But it still doesn't work. Any idea why?

**Comment by maj0rr** [comment]
Hey @maryheng,
did you solved this issue? I got exact the same problem..

Please let me know :) thanks!

**Comment by maj0rr** [comment]
see https://github.com/ratiw/vuetable-2/issues/226...
