### ISSUE TITLE
http-options doesn't work

### ISSUE THREAD

**Issue by phuongtailtranminh** [ratiw/vuetable-2#213]
I'm trying to pass the `access token` in order to request the API. But I didn't see it when inspecting it

This is the config:

```
    <vuetable ref="vuetable"
      api-url="https://vuetable.ratiw.net/api/users"
      :fields="fields"
      :css="css.table"
      :append-params="moreParams"
      :per-page="itemPerPage"
      :http-options="headers"
      @vuetable:load-success="onLoadSuccess"
      pagination-path=""
      @vuetable:pagination-data="onPaginationData"    
    ></vuetable>
```

```
  data () {
    return {
      headers: {
        'authorization': `Bearer ${window.store.get('access_token')}`
      },
 }
```
The Inspecting

![image](https://user-images.githubusercontent.com/12473996/28554698-154ff3fa-7125-11e7-8eb7-2a62c5eef5ea.png)

**Comment by eloiletagant** [comment]
Hello! I'm facing exactly the same problem, what was the key ? Was it a server config issue ? Thanks to help me I'm a bit lost on this thing...
