### ISSUE TITLE
Passing Row Data to Callback method

### ISSUE THREAD

**Issue by iamgaurav** [ratiw/vuetable-2#219]
I am looking to format a column with a URL. The URL is something like this
project/id. Is there any way to achieve this? The column that needs to formatted doesn't have the primary ID of the project which needs to be passed as the URL parameter. 

The callback method has to be something like 

`projecturl( value, data ){
    return '<a href="/project/data.id">value</a>';
}`

**Comment by ratiw** [comment]
@iamgaurav Use [`__slot`](https://github.com/ratiw/vuetable-2/wiki/Special-Fields#-__slotname).

**Comment by iamgaurav** [comment]
@ratiw wouldn't that be limited just for actions? I mainly require a Column Modifier that has a hyperlink like this: http://prntscr.com/g3yev4 rather than just plain text like this: http://prntscr.com/g3yefn

This can be done using callbacks however, I'm unsure how __slot would work here to provide the primary ID for the URL

**Comment by ratiw** [comment]
@iamgaurav `__slot` and `__component` are very flexible and can do almost anything, but `__slot` would be simpler in your case as you don't need to register the component.

Please study more about slot and scoped slot in Vue documentation as it is very crucial in successfully using Vue in your project. I also have a follow-along [tutorial for Vuetable-2](https://github.com/ratiw/vuetable-2-tutorial/wiki) that also cover the use of `__component` and `__slot` special fields. Please go through it first, it is not that hard.
