### ISSUE TITLE
Changing API URL

### ISSUE THREAD

**Issue by iamgaurav** [ratiw/vuetable-2#223]
Hey
Is it possible to set the api-url of the vuetable from the Laravel blade template? I tried something like this. 
`<backlinks 
      :api-url="/api/projects/1">
</backlinks>`

**Comment by boomhq** [comment]
Yeah naturally in this case your set a props `{'apiUrl' :'/api/projects/1'}`.
In your components just need to set :api-url where your call vuetable like  : 
`  <vuetable :api-url="apiUrl"
