### ISSUE TITLE
Unable to watch selectedTo prop

### ISSUE THREAD

**Issue by iamgaurav** [ratiw/vuetable-2#228]
Hi

I am trying to watch the selectedTo prop since I need to use the array for bulk actions ( CRUD )
Trying to watch the prop using the following code. 

`  watch : {
          selectedTo: {
             handler(val, oldVal){
                    console.log('Item Changed')
                    console.log(val)
             },
             deep: true
          }
  },
`
This probably is a very noob question. I am still learning Vue and I wasn't able to find a solution to this.

**Comment by ratiw** [comment]
Why not listening to the `vuetable:checkbox-toggled` event instead?

**Comment by iamgaurav** [comment]
Found it easier to perform the bulk remove options using the array. Then listening to the event. 
Since I require all the selected ID's I found watching the selectedTo array perfect for my project.

I was able to achieve this using the below code. 

`mounted () {
      this.$watch(
      	() => {
      		return this.$refs.vuetable.selectedTo
      	},
        (val) => {
               
        }
      )
  },
`
