### ISSUE TITLE
[Question] Individual Column Binding

### ISSUE THREAD

**Issue by iamgaurav** [ratiw/vuetable-2#233]
Hi

So in my Table when some new data gets added, there are 2 columns whose data gets updated in the background and another 2 columns which depend upon that background data to show the right result.

Example
Column 2 - Dependent on Column 4
Column 3 - Dependent on Column 5
Column 4 - Data gets updated in the background until then both have NULL Values
Column 5 - Data gets updated in the background until then both have NULL Values

This is how the plan HTML version of the table looks like 
https://prnt.sc/gcshky 

Now when Column 4 and 5 get updated by the polling server ( Background Jobs ) column 2 and 3 shouldn't show the loading spinner anymore and all the new column values should get updated. 

What would be the most optimum way to do this? Since at any time there can be up to 1000 new rows added by the user.

**Comment by ratiw** [comment]
If you are using Vuetable without using API mode, there is no optimum way to do that in my opinion. You'll have to experiment and see what's acceptable for you. It might or might not work. 

It sounded like you're combining the background work (which should be done on the server) with the front-end work (which should be done on the client side). There should be a middle mechanism to push information/notification from the server side to the client side, e.g. Pusher. 

If the data gets updated, Vue should handle that automatically and Vuetable will also pick up the change, which your field component or slot can then conditionally rendered what's appropriate.
