### ISSUE TITLE
Trouble with data mode

### ISSUE THREAD

**Issue by stevieg83** [ratiw/vuetable-2#235]
My component works as expected render my table headers and `no data available` before I attempt to pass my Laravel variable to the Vue component

However, when I try to do `<user-list my-data="{{ $users }}"></user-list>`

and then in that `user-list` component I do

```
<template>
...
<vuetable ref="vuetable"
		:apiMode="false"
		:data="myData"
		:fields="fields"
		:css="css.table"
		></vuetable>
...
</template>

<script>
...
props: ['myData'],
...
```

Things go wrong
![Image of issue](http://d.pr/i/29EObb+)

and the table component isn't available in the Vue dev tools.

What am I missing?

**Comment by stevieg83** [comment]
Narrowed it down to the way I'm grabbing the data from Laravel itself

`$users = User::paginate(10);` if I change that to `$users = User::get()` then it works (but displaying all users when I want to add my own Laravel based paginator. 

Is this possible?

**Comment by ratiw** [comment]
In Data mode, you'll have to set up the `dataManager` function to return both the data and the pagination information back to Vuetable. Vuetable will not automatically handle that for you.

But since you're using Laravel as a backend, why would you still want to use Data mode? Vuetable was written to work in API mode from the beginning and if you're using Laravel as a backend, it would be easier and more convenient.

**Comment by stevieg83** [comment]
I do like the API but I also like to have my query strings appended as I paginate as it's useful to send URLs in email, Slack etc.

Is there a way to enable that where it would be easier than configuring the `dataManager` function?

**Comment by ratiw** [comment]
Is [this](https://github.com/ratiw/vuetable-2/wiki/Vuetable-Properties#-append-params) what you're looking for?

**Comment by stevieg83** [comment]
@ratiw great - any docs or examples of it in use?

**Comment by ratiw** [comment]
Not really. Didn't have time to finish all the doc. But it is just a key-value pair object which will later be combined into the query string that get send to the server. [This](https://github.com/ratiw/vuetable-2/blob/master/src/components/Vuetable.vue#L495-L506) is the location in the source code where it gets merge into the query string.
