### ISSUE TITLE
[Question] Customize-able Headers

### ISSUE THREAD

**Issue by NickAmbrosio** [ratiw/vuetable-2#237]
Hey All!

I am trying to implement filters and total values to the column headers themselves. 
I see you can provide components within the body cells with in the callback function in the field objects.
However, is there an option to add HTML to the header cells that I am missing?

Example : 

![image](https://user-images.githubusercontent.com/16783483/29845188-ca305b04-8cc6-11e7-9e11-bf516f8c3ba2.png)

**Comment by ratiw** [comment]
Someone has sent [this PR](https://github.com/ratiw/vuetable-2/pull/86). Check to see if that's work for you.

**Comment by NickAmbrosio** [comment]
@ratiw 
Thanks for the reference! This helps put me in the right direction. 
I agree that it definitely is very custom and is difficult to add a generic column filter.
