### ISSUE TITLE
Callback not rendering anything

### ISSUE THREAD

**Issue by RedTn** [ratiw/vuetable-2#242]
I'm following the tutorial here exactly as mentioned: [https://github.com/ratiw/vuetable-2-tutorial/wiki/lesson-06](https://github.com/ratiw/vuetable-2-tutorial/wiki/lesson-06)

For some reason, I'm not getting anything rendered in the nicknames column?
`
data() {

        return {
            name: 'Restaurants',
            fields: [
                {
                    name: 'name',
                    title: 'User'
                },
                'email',
                {
                    name: 'birthdate',
                    titleClass: 'center aligned',
                    dataClass: 'center aligned'
                },
                {
                    name: 'nickname',
                    callback: 'allcap'
                },
                {
                    name: 'gender',
                    titleClass: 'center aligned',
                    dataClass: 'center aligned'
                },
                {
                    name: 'salary',
                    titleClass: 'center aligned',
                    dataClass: 'right aligned'
                }
            ]
        };
    },
    methods: {
        allcap(value) {
            return value;
        }
    }`

**Comment by ratiw** [comment]
Your `allcap` function returns the given `value` without doing anything with it.

In the tutorial, it is supposed to return the value with all uppercase letters using `toUpperCase()` function.

If this is not what you mean, please explain more or put your code in jsfiddle or codepen.

**Comment by RedTn** [comment]
Found the issue, looks like there was something wrong with my node_modules so I cleaned it up

**Comment by enno28** [comment]
i found this issue too, how to solve this problem? i'm tired with it
