### ISSUE TITLE
How to override 'No Data Available'?

### ISSUE THREAD

**Issue by viewplatgh** [ratiw/vuetable-2#243]
The [lesson 8](https://github.com/ratiw/vuetable-2-tutorial/wiki/lesson-08) introduced information text `info-template` and `no-data-template`, but there is another text showing when no data in table: `No Data Available`, which seems not mentioned in wiki?

**Comment by ratiw** [comment]
You can override it using [`no-data-template`](https://github.com/ratiw/vuetable-2/wiki/VuetablePaginationInfoMixin#-no-data-template) property.

**Comment by viewplatgh** [comment]
Thanks, I got it. Need to add `:no-data-template` to `vuetable` tag as well as `vuetable-pagination-info` tag.
