### ISSUE TITLE
No data available flash issue

### ISSUE THREAD

**Issue by viewplatgh** [ratiw/vuetable-2#244]
Before table data shows, `No data available` will flash once, i.e. show and disappear in less than one second. Is there a way to avoid it? Thanks!

**Comment by ratiw** [comment]
I always show loader/spinner during the load of data. But if you prefer to hide it, you can extend `VuetablePaginationInfoMixin` to hide it when `tablePagination` is `null`, or you can modify `VuetablePaginationInfo` template to hide it as well.

**Comment by viewplatgh** [comment]
Many thanks!
