### ISSUE TITLE
Disable __checkbox on load

### ISSUE THREAD

**Issue by Rubemlrm** [ratiw/vuetable-2#246]
Hi there,

I have a little question relative to the usage of **__checkbox**  , its possible set the checkbox as disabled/enabled based on row specific information ?

**Comment by ratiw** [comment]
Yes, you just add or remove the track-by id to/from the `selectedTo`array.

**Comment by Rubemlrm** [comment]
@ratiw hi there sorry for the late reply. I will try that =) but i'm just wondering if i do that the checkbox dont get disabled , instead get a unselected status or i'm wrong ?

**Comment by ratiw** [comment]
@Rubemlrm Yes, you're correct. There is no way to selectively enable/disable each checkbox unless you fork the repo and make some necessary adjustment. But wouldn't that be confusing to the user?

**Comment by Rubemlrm** [comment]
In this case its a needed feature , because the list i'm working on , its a task list and i want disable the checkbox's of tasks already planned to avoid duplicated tasks planning. Maybe i will use a component/slot to emulate this behaviour.

**Comment by Rubemlrm** [comment]
i've implemented the behaviour i wanted using a slot and settings the selectedTo props.
I will close this issue. thanks for the help @ratiw.
