### ISSUE TITLE
Dropwdown Filters

### ISSUE THREAD

**Issue by Rubemlrm** [ratiw/vuetable-2#254]
Hi there,

I have a little question at this moment, in the examples i've seen we only have a text filter , buts its possible to have a row in the table with dropwdown filters for each column ?

**Comment by ratiw** [comment]
I think there are 2 PR submitted regarding this feature. But I don't have any plan to merge it or even implement it at the moment. So, this feature is still not supported at the moment.

**Comment by Rubemlrm** [comment]
I will check those 2 PR to see if i can do what i want. thanks in advance
