### ISSUE TITLE
HTML in slot template

### ISSUE THREAD

**Issue by ligne13** [ratiw/vuetable-2#255]
Hi,  
this is surely a dumb question... I can't figure how to render HTML in my slot template :

`<template slot="status" scope="props">  
{{ props.rowData.status === 1 ? '<i class="fa fa-circle text-success"></i>' : '<i class="fa fa-circle text-danger"></i>' }}  
</template>`

The code above renders like the attached image :
![capture d ecran 2017-09-25 a 09 36 42](https://user-images.githubusercontent.com/81624/30797103-12e4579c-a1d5-11e7-9eb0-0992bb508fc8.png)

I think this is more a VueJS question than a Vuetable one, but maybe I will find some quick help here.

Thanks
Max

**Comment by lfserrra** [comment]
try v-html attribute

**Comment by ligne13** [comment]
Sorry I don't see how to set the v-html attribute to this :
`{{ props.rowData.status === 1 ? '<i class="fa fa-circle text-success"></i>' : '<i class="fa fa-circle text-danger"></i>' }}`
Can you give an example ?

thanks

**Comment by lfserrra** [comment]
Take a look at
https://vuejs.org/v2/api/#v-html

**Comment by ligne13** [comment]
OK so I have to use a component...

thanks

*Maxime Freschard*
ligne13.com
06 71 20 31 23

2017-09-25 11:50 GMT+02:00 lfserrra <notifications@github.com>:

**Comment by cristijora** [comment]
@ligne13 just use conditionals `v-if` Scoped slots are like components which pass you some data. You are free to write any valid vue template inside them
```html
<template slot="status" scope="props">
<i v-if="props.rowData.status===1" class="fa fa-circle text-success"></i>
<i v-else class="fa fa-circle text-danger"></i>
```

**Comment by ligne13** [comment]
@cristijora thanks.
