### ISSUE TITLE
Default sort order wiki

### ISSUE THREAD

**Issue by SimplyCorey** [ratiw/vuetable-2#256]
Thanks again for the great working vue-table :)

I noticed that the wiki to provide a default sort order is currently wrong.  It states to provide the following:
https://github.com/ratiw/vuetable-2/blob/08f453ecfaa6707571bba6fcfc3890dee256304f/docs/Sorting.md#initial-sorting-order

```
sortOrder: [
      {
        field: 'email',
        direction: 'asc'
      }
    ]
```

While this orders the column, it does not put the sorted symbol on the header.  I had to use the following code in order for it to work:

```
sortOrder: [
      {
        field: 'email',
        sortField: 'email',
        direction: 'asc'
      }
    ]
```

**Comment by gmw-web** [comment]
For me, the proposed code does not work. 

I have however found out that the initial sort symbol isn't applied when i'm using a [`__slot:`](https://github.com/ratiw/vuetable-2/wiki/Special-Fields#-__slotname) field. 
For regular column fields the symbol is displayed correctly, even though I did not add the `sortField` that is mentioned by @SimplyCorey

**Comment by ratiw** [comment]
@gmw-web Thanks. Will find time to check it this weekend.

**Comment by nkwinder** [comment]
just found out that if field name is different than sortField value, then you have to specify both of them in the sort-order param, in order for the symbol to show up.
If name and sortField are the same, then only field is enough.

**Comment by lnavimanl** [comment]
bump

**Comment by fabianx02** [comment]
sortField: 'email' debe ponerse en fields y poner el simbolo.

fields: [
                        {
                            name: 'email',
                            sortField: 'email'
                        },
