### ISSUE TITLE
Multiple Callback

### ISSUE THREAD

**Issue by jben0324** [ratiw/vuetable-2#259]
Is it possible to do multiple callback?

callback: [ 'method1', ' 'method2']

i can only use 1 callback per field

**Comment by ratiw** [comment]
Why would you need that?

**Comment by hanxue** [comment]
Why not call `method2` from within `method1`?

```javascript
function method1(value) {
    return "Hello " + method2(value)
}
function method2(value) {
    return value.toUpperCase()
}
```

**Comment by eduardoarandah** [comment]
How to display a field with multiple column data?

fields:[
        {
          name: 'name',
          callback: **< - here send name and url**
        },
        {
          name: 'url',
        },

**Comment by ratiw** [comment]
@eduardoarandah Each field will get only one value from its data. If you need to put more than one column data into a single field, consider using `__slot` special field (v1.7.x) or Field Slot (v2.0).

**Comment by eduardoarandah** [comment]
Thanks! 

I got stuck at tutorial:
https://github.com/ratiw/vuetable-2-tutorial/wiki/lesson-06

A small example there might be very helpful, creating a "link" is common


Question:
what do you think about passing the row as a second argument to callback?

**Comment by ratiw** [comment]
@eduardoarandah Personally, passing row data as to the callback would defeat the purpose and scope of the `callback`. It was meant to be used as a value format function for that column. That's why I renamed it to `formatter` in v2.0. If you need more than a simple formatting of value, `__slot` is more appropriate.
