### ISSUE TITLE
Detailed Fields definition for nested JSON field doesn't render

### ISSUE THREAD

**Issue by gmw-web** [ratiw/vuetable-2#267]
When I use a fields definition for nested JSON field like the following, everything works
`columns: [state.future.date_out]`

However, when I use a more detailed fields definition like the following, the table cell stays empty:
```
columns: [
	{
		name: 'state.future.date_out',
		title: 'Date out',
		titleClass: 'h6',
		callback: 'transformDate'
	}
]
```
A detailed fields definition with `name` refering to a JSON root key/value (like `name: 'id'`) does render normally. 
I have double checked, and the field does really exist in the table data.

**Comment by ratiw** [comment]
I've just re-checked from the example and It is still work as expected in both cases.

Can you setup a jsfiddle or codepen to demonstrate the problem and I'll have a look.

**Comment by gmw-web** [comment]
Here's a JSFiddle of the issue:
https://jsfiddle.net/c9dc5g1m/1/

I've also tried setting `:data="tableData"` combined with `data-path="items"`, but then no data is shown at all. Shouldn't this do the same as `:data="tableData.items"` and `data-path=""`?

**Comment by ratiw** [comment]
@gmw-web `future` is an "array". Vuetable does not support array dereferencing. Even if it is supported, the way you deference it is still incorrect.

**Comment by gmw-web** [comment]
@ratiw You are absolutely right. I had overlooked that completely, stupid of me :expressionless:. 
Thanks for your help!
