### ISSUE TITLE
Transform not firing with APIMODE=false

### ISSUE THREAD

**Issue by Kurab77** [ratiw/vuetable-2#271]
Let me preface this by saying I am quite new to Vue.js and front end development.  Thru the tutorial (copied a bunch of this code) and issues I have come up with the following code: ( I am using VueTable2) and thank you in advance.

My VueTable:

    <div class="container">
        <filter-bar></filter-bar>
    <vuetable ref="vuetable"
    :apiMode=false
    :data=this.spotAwardsData
    :fields="fields"
    :css="css"
    pagination-path=""
    :per-page="25"
    :multi-sort="true"
    multi-sort-key="ctrl"
    :sort-order="sortOrder"
    :append-params="moreParams"
    :render-icon="renderIcon"
    @vuetable:cell-clicked="onCellClicked"
    @vuetable:pagination-data="onPaginationData">

My script code: 

`<script>

    export default{
        props: ['testSpotData'],
        components: {
            Vuetable,
            VuetablePagination,
            VuetablePaginationInfo,
            FilterBar
        },
        data () {
            return {
                css: BootstrapStyle,
                fields: FieldDef,
                sortOrder: [
                    {
                        field: 'spotAwardId',
                        sortField: 'spotAwardId',
                        direction: 'asc'
                    }],
                moreParams: {},
                spotAwardsData: []
            };
        },
        mounted () {
            this.$events.listen('filter-set', filterText => this.onFilterSet(filterText));
            this.$events.listen('filter-reset', () => this.onFilterReset());
        },
        created () {
              axios.get('http://10.50.10.87:7777/spotawards/listspotawards').then(response => { 
                                                                    this.spotAwardsData = response.data; });
        },
        computed: {
            getSpotData () {
                return this.getSpotAwardsData();
            }
        },
        methods: {
            transform: function(data) {
                let transformed = {};

                console.log('TRANSFORM HIT!');

                transformed.pagnation = {
                    total: data.count,
                    per_page: data.per_page,
                    current_page: data.current_page,
                    last_page: data.last_page,
                    next_page_url: data.next_page_url,
                    prev_page_url: data.prev_page_url,
                    from: data.from,
                    to: data.to
                };

                transformed.data = [];

                for (var i = 0; i < data.length; i++) {
                    transformed.data.push({
                        id: data[i].id,
                        spotAwardId: data[i].spotAwardId,
                        nominatedDate: data[i].nominatedDate,
                        giverName: data[i].giverName,
                        giverId: data[i].giverId,
                        recipientName: data[i].recipientName,
                        recipientId: data[i].recipientId,
                        awardReason: data[i].awardReason,
                        amountRequested: data[i].amountRequested,
                        amountApproved: data[i].amountApproved,
                        departmentId: data[i].departmentId,
                        approvedDate: data[i].approvedDate,
                        approvedUserId: data[i].approvedUserId,
                        rejectedDate: data[i].rejectedDate,
                        rejecetionReason: data[i].rejecetionReason,
                        corporateBenefit: data[i].corporateBenefit,
                        awardStatus: data[i].awardStatus,
                        loadDate: data[i].loadDate,
                        budgetId: data[i].budgetId
                    });
                }
                return transformed;
            },
            getSpotAwardsData() {
                axios.get('http://10.50.10.87:7777/spotawards/listspotawards').then(response => { this.spotAwardsData = response.data; });
                return this.spotAwardsData;
            },
            mounted() {

            },
            renderIcon (classes, options) {
                return `<span class="${classes.join(' ')}"></span>`;
            },
            allcap (value) {
                return value.toUpperCase();
            },
            formatNumber (value) {
                return accounting.formatNumber(value, 2);
            },
            formatDate (value, fmt = 'D MMM YYYY') {
                return (value == null)
                    ? ''
                    : moment(value, 'YYYY-MM-DD').format(fmt);
            },
            onPaginationData (paginationData) {
                this.$refs.pagination.setPaginationData(paginationData);
                this.$refs.paginationInfo.setPaginationData(paginationData);
            },
            onChangePage (page) {
                this.$refs.vuetable.changePage(page);
            },
            onCellClicked (data, field, event) {
                console.log('cellClicked: ', field.name);
                this.$refs.vuetable.toggleDetailRow(data.id);
            },
            onAction (action, data, index) {
                console.log('custom-actions: ' + action, data.name, index);
            },
            onFilterSet (filterText) {
                this.moreParams = {
                    'filter': filterText
                };
                Vue.nextTick(() => this.$refs.vuetable.refresh());
            },
            onFilterReset () {
                this.moreParams = {};
                this.$refs.vuetable.refresh();
                Vue.nextTick(() => this.$refs.vuetable.refresh());
            }
        }
    };

</script>`

Any my JSON data:  

	"result": [{
			"spotAwardId": 258,
			"nominatedDate": "2015-01-13T00:00:00.0000000-06:00",
			"giverName": "Tom Cruse",
			"giverId": "tcruse@topgun.com",
			"recipientName": "Iceman McKinley",
			"recipientId": "iceman@topgun.com",
			"awardReason": "Took it upon himself to shoot down a jet.",
			"amountRequested": 25,
			"amountApproved": 25,
			"departmentId": 16,
			"approvedDate": "2015-01-13T00:00:00.0000000-06:00",
			"approvedUserId": "99999",
			"rejectedDate": null,
			"rejecetionReason": null,
			"corporateBenefit": "Customers needs",
			"awardStatus": "Approved",
			"loadDate": "2015-01-15T00:00:00.0000000-06:00",
			"budgetId": 0
		}, {
			"spotAwardId": 259,
			"nominatedDate": "2015-02-03T00:00:00.0000000-06:00",
			"giverName": "Mario Johnson",
			"giverId": "mjohnson@video.com",
			"recipientName": "Larry Byrd",
			"recipientId": "lbyrn@basketball.com",
			"awardReason": "For beig a great guy.",
			"amountRequested": 75,
			"amountApproved": 25,
			"departmentId": 1,
			"approvedDate": "2015-02-03T00:00:00.0000000-06:00",
			"approvedUserId": "99999",
			"rejectedDate": null,
			"rejecetionReason": null,
			"corporateBenefit": "Safety",
			"awardStatus": "Approved",
			"loadDate": "2015-02-13T00:00:00.0000000-06:00",
			"budgetId": 0
		},

When I run the site, by using Fiddler I can see that my call is being made and the data prop has my JASON object in it but the transform method is not running....What am I doing wrong?  Please help - been working on this issue for over a week now.

**Comment by ratiw** [comment]
@Kurab77 That is actually the expected behaviour. 

In default mode (API mode), Vuetable will call `transform` method when the API request is success via the [`loadSuccess` method](https://github.com/ratiw/vuetable-2/blob/master/src/components/Vuetable.vue#L445). 

When you set Vuetable to work on Data mode (aka. `:api-mode="false"`), Vuetable will just call the "data manager" method [right away](https://github.com/ratiw/vuetable-2/blob/master/src/components/Vuetable.vue#L428-L431) without requesting data from the API, so the `loadSuccess` method never gets called and therefore the `transform` method never gets called as well.

In the Data mode, Vuetable expects you to supply the data that it can work with. That also means you should transform your data before passing them to Vuetable. In this can you can transform your data inside the data manager before returning them to Vuetable.

**Comment by Kurab77** [comment]
Thank you for your response!
