### ISSUE TITLE
selectedTo data not reset to empty when use checkbox then go to another page

### ISSUE THREAD

**Issue by jackbbhua** [ratiw/vuetable-2#280]
for example:
i am in 1st page i choose all data 50 results.when i go to another page,i check all data it is 100 results,i am thinking people want be reset and cover 50 results from 1st page and use 50 from 2st page data.because some actions if not clean willl have big trouble.is there has any way to catch change page action?
thank you very much.

**Comment by ratiw** [comment]
You can reset the `selectedTo` variable to an empty array `[]` before or after requesting a new page of data. 

There actually are many ways you can detect/capture that event.

In API mode, 
- `vuetable:loading`
- `vuetable:loaded`
- `vuetable:load-success`

any of these events can be used as it indicates that Vuetable is requesting or getting the 
new page of data.

More appropriately, if you're using VuetablePagination, you can also listen to `vuetable-pagination:change-page` event.

In Data mode, you can clear the `selectedTo` content in your `data-manager` method.

**Comment by jackbbhua** [comment]
it works now.thank you ratiw.
