### ISSUE TITLE
__checkbox limit to one selection and disable based on row props

### ISSUE THREAD

**Issue by kahwooi** [ratiw/vuetable-2#289]
I am using a special column __checkbox, can I do this:

1. Can I hide or disable the checkbox base on the props row data?
2. Can I force user to only select 1 row?

**Comment by ratiw** [comment]
@kahwooi Why not listen to `vuetable:row-clicked` event and manually add/remove item in the `selectedTo` array. Also, use the `row-class` prop callback to style your selected item as well.
