### ISSUE TITLE
Pagination: Sorting

### ISSUE THREAD

**Issue by Romanulus** [ratiw/vuetable-2#290]
I've flown around the documentation and noticed that there isn't enough of a note about setting up your api to serve sorting in pagination. Mind you, I'm using Laravel 5.4 and paginate().

Am I missing something?

**Comment by jordanramstad** [comment]
If you use something like fractal with the serializers, the default serializer works mostly works, I think just some of the default names are not quite right. The array serializer is what I typically use. Though if not using fractal you would need to map it out yourself.

```
<?php

namespace App\Serializers;

use League\Fractal\Pagination\PaginatorInterface;
use League\Fractal\Serializer\ArraySerializer as BaseArraySerializer;
use Illuminate\Contracts\Pagination\LengthAwarePaginator;

class LaravelArraySerializer extends BaseArraySerializer
{
    public function paginator(PaginatorInterface $paginator)
    {
        $currentPage = (int) $paginator->getCurrentPage();
        $lastPage = (int) $paginator->getLastPage();

        $parentPaginator = $paginator->getPaginator();
        if ($parentPaginator instanceof LengthAwarePaginator) {
            $pagination = [
                'total' => (int) $paginator->getTotal(),
                'count' => (int) $paginator->getCount(),
                'per_page' => (int) $paginator->getPerPage(),
                'current_page' => $currentPage,
                'last_page' => $lastPage,
                'next_page_url' => $parentPaginator->nextPageUrl(),
                'prev_page_url' => $parentPaginator->previousPageUrl(),
                'from' => (int) $parentPaginator->firstItem(),
                'to' => (int) $parentPaginator->lastItem()
            ];
        } else {
            $pagination = [
                'total' => (int) $paginator->getTotal(),
                'count' => (int) $paginator->getCount(),
                'per_page' => (int) $paginator->getPerPage(),
                'current_page' => $currentPage,
                'total_pages' => $lastPage,
            ];
        }

        return ['pagination' => $pagination];
    }
}
```
https://ratiw.github.io/vuetable-2/#/Data-Format-JSON 

Is where you can see the structure that vue-table expect and should be able to help build the responses from the api correctly.

**Comment by Romanulus** [comment]
Hey Jordan, thanks for the reply (and especially edit); I read the first part and wen't "huh, did he gloss over sorting?". ;)

Your spot on correct with that, too, because in my search (and failure to find anything), I ended up doing nearly exactly what you did... I'm still a little unsure about the choice of putting a pipe-bound value in the querystring, but this is what we have.

**Comment by ratiw** [comment]
Have you check out this [repo](https://github.com/ratiw/vuetable-sample-api-endpoint)? Specifically [this section](https://github.com/ratiw/vuetable-sample-api-endpoint/blob/master/app/Http/routes.php#L16-L25)
