### ISSUE TITLE
How could i hide the row when some field is empty? 

### ISSUE THREAD

**Issue by paladosss** [ratiw/vuetable-2#293]
Sorry for stupid question, but i cant understand how to do it?

How could i hide the row when some field is empty?

**Comment by ratiw** [comment]
If you're working in API mode, this should be done on the server side by filtering the result. As I see it there is no need to show the data you don't need for displaying.

If you are using in Data mode, filter your data before sending it to Vuetable. 

Unless I missed your point, please explain in more detail.

**Comment by paladosss** [comment]
Thank you, everything is understood!
