### ISSUE TITLE
Allow simple json or object as parameter instead of api url to increase usability

### ISSUE THREAD

**Issue by tatsujb** [ratiw/vuetable-2#294]
If i understand correctly the ONLY way to use this currently is feed vuetable the api url as a vue parameter within the `<vuetable>` dom tag?

Unless I'm getting this wrong?

but that's incredibly restrictive?

I want to process the data a bit before sending it to the table and also this leaves 0 configurability for the user, can't choose between post or get? my api call needs a JWT token for example, from what I understand that not an option.

I'd like to have the choice of just giving it my finalized object and handling REST myself.

couldn't that be an option?

**Comment by ratiw** [comment]
Study the example of Data mode [here](https://codepen.io/ratiw/project/editor/DzmJnA). Use `data-manager` to process the data before sending it to Vuetable. 

`http-method` prop [here](https://ratiw.github.io/vuetable-2/#/Vuetable-Properties?id=-http-method) for specifying the `post` verb.

`http-options` prop [here](https://ratiw.github.io/vuetable-2/#/Vuetable-Properties?id=-http-options) for specifying additional options to the underlying `axios` lib.

[`http-fetch`](https://github.com/ratiw/vuetable-2/blob/develop/docs/Vuetable-Properties.md#-http-fetch-v17) prop is available in the `develop` branch.

**Comment by CharlesOkwuagwu** [comment]
Hi, please, this does not work:
```
computed:{
  httpOptions(){
    return {headers: {'Authorization': 'Bearer my-auth-token'}}
  }
 }
```
