### ISSUE TITLE
Set slot template in parent component

### ISSUE THREAD

**Issue by bernhardh** [ratiw/vuetable-2#310]
Not sure if this is the right place for this question, but lets say I have created some kind of wrapper component for vuetable-2:

```
<template>
    <div class="table-responsive">
		...
		<vuetable
				ref="vuetable"
				:apiUrl="apiUrl"
				:fields="fields"
				:css="css"
				:sortOrder="sortOrder"
				:appendParams="appendParams"
				:detailRowComponent="detailRowComponent"
				:perPage="perPage"
				:multiSort="multiSort"
				paginationPath=""
				@vuetable:cell-clicked="onCellClicked"
				@vuetable:pagination-data="onPaginationData">
		</vuetable>
		...
	</div>
</template>
```

And lets say the fields look like this:

```
[
	{
		name: 'name',
		sortField: 'name',
	}, {
		name: '__slot:actions',
		title: 'Actions',
		dataClass: 'text-center',
	}
]
```

If I wanna use my component, I would have to do the following:

```
<!--App.vue-->
...
<my-table></my-table>
...
```

The question now is, how to define the content of the actions column on the App.vue? I wanna do something like this:

```
<!--App.vue-->
...
<my-table>
	<template slot="actions" slot-scope="props">
		<a>Edit {{ props.rowData.name }}</a>
	</actions>
</my-table>
...
```

**Comment by ratiw** [comment]
Please see Lesson 17 of the [tutorial](https://github.com/ratiw/vuetable-2-tutorial/wiki/). 
However, I would advise starting from the first lesson as each lesson is not so long.

**Comment by bernhardh** [comment]
Thanks for responding!
I have done the tutorial, but that is not answering my question.

Transfered my example to the tutorial example: I want to define the  <template slot="actions" scope="props">....</template>  inside the App.vue and not inside the MyVuetable.vue, so that I can reuse the MyVuetable component and have multiple tables in my app. Something like this:

```
<!--App.vue-->
...
<h1>Book List</h1>
<my-table apiUrl="/api/books">
	<template slot="actions" slot-scope="props">
		<a>Book name {{ props.rowData.name }}</a>
	</actions>
</my-table>
...
<h1>Car List</h1>
<my-table apiUrl="/api/cars">
	<template slot="actions" slot-scope="props">
		<a>Car name {{ props.rowData.name }}</a>
	</actions>
</my-table>
...
```

**Comment by bernhardh** [comment]
Oh sorry. I didn't see that. Thank you. That is what i am looking for!
