### ISSUE TITLE
Hide column?

### ISSUE THREAD

**Issue by mitymarcus** [ratiw/vuetable-2#313]
Hello there!
First off, I just wanted to say that I absolutely adore the software that you all have made, it works really well.

My only issue is that I have 2 modes: admin, and normal user. The only difference is that one column is hidden. Is there any way to dynamically hide a certain column?

Thanks!

**Comment by cristijora** [comment]
Hi @mitymarcus It's possible to do that but there is one caveat
http://jsfiddle.net/z11fe07p/2681/

You have to call a method which re-renders table columns
```js
toggleColumn() {
    this.nicknameColumn.visible = !this.nicknameColumn.visible
    this.$refs.vuetable.normalizeFields()
},
```

**Comment by mitymarcus** [comment]
Wow, you are incredible at supporting the project! Thanks for all the help, it works perfectly!
