### ISSUE TITLE
Select all checkboxes on page and all checkboxes in table

### ISSUE THREAD

**Issue by lrembacz** [ratiw/vuetable-2#314]
Is there a simple way to make a function or there is the function to select all checkboxes on page ( I want to use it on my own button not only with checkbox in TH).
I need also function to select all checkboxes on all pages in table is there a way for this?

**Comment by lrembacz** [comment]
```
            checkboxCheckList () {
                var vuetable = this.$refs.vuetable;
                vuetable.tableData.forEach(function(dataItem) {
                    vuetable.selectId(dataItem['id']);
                });
                this.selected = this.$refs.vuetable.selectedTo.length;
            },
            checkboxUncheckList () {
                var vuetable = this.$refs.vuetable;
                vuetable.tableData.forEach(function(dataItem) {
                    vuetable.unselectId(dataItem['id']);
                });
                this.selected = this.$refs.vuetable.selectedTo.length;
            }
```
Is this correct?

**Comment by cristijora** [comment]
@lrembacz that could be an option. You could also directly call the method inside vuetable
http://jsfiddle.net/z11fe07p/2668/
```js
selectAll(value){
     this.$refs.vuetable.toggleAllCheckboxes('__checkbox', {target: {checked: value}})
},
```

**Comment by lrembacz** [comment]
Nice :) And the second part of the question? Is there way to check all checkboxes on every page?

**Comment by cristijora** [comment]
No that is not quite possible. If you use server side pagination then, you only get X items per page displayed and saved in your app. It's not physically possible to check all items if they do not exist yet in your app

**Comment by lrembacz** [comment]
I would need second query then? Just without pagination? For all of the Ids?

**Comment by cristijora** [comment]
Well that's kind of the whole point of pagination - to not retrieve all the data.
Not sure what's your use case but usually such select-all functionality would affect/select only the items from the current page.

**Comment by lrembacz** [comment]
My case is that when Im using filters, Im getting like 200 records. So in pagination i got like 25-100 records per page and now I want to change all status or some other parameter for all 200 records at once (all records I got after filtering).
