### ISSUE TITLE
Update Header on each request

### ISSUE THREAD

**Issue by Al3xR0** [ratiw/vuetable-2#318]
I'm using Laravel, and Laravel JWT to authenticate users. The jwt is set to refresh on each request, so that means that the previous token will be blacklisted. 

How can I update each vuetable request header with the new token?

Tried to set axios config globally but that doesn`t affect vuetable requests.

I managed to update the token when receiving the request by using the below functionality, but still need to send the new token on each request.

      <ax-vuetable ref="vuetable"
         @vuetable:load-success="loadData"
      >
      ......

      ......
      loadData(success = this.loadSuccess, failed = this.loadFailed) {
          let token = success.headers.authorization;
          token = token.replace("Bearer ", "");
          token = token.trim();

          localStorage.setItem('token', token);
       }
       ......

**Comment by ratiw** [comment]
Have you check out `http-fetch` prop? Will that solve your problem?

**Comment by Al3xR0** [comment]
@ratiw I managed to add a function for `http-fetch` that will update the header with the new token. Thanks!

**Comment by lrembacz** [comment]
Can u please post a code for that? Cuss Im getting same issue and only first call works for vuetable
