### ISSUE TITLE
Content isnt rendered inside Columns

### ISSUE THREAD

**Issue by kayyyy** [ratiw/vuetable-2#33]
Great Work 👍 
I have a Problem, the Content my Table isn`t rendered. The Rows are there but without its Content.

```
<template>
    <vuetable
        api-url="http://seller.dev/api"
        pagination-path=""
        class="zen-table-elem"
        :fields="columns"
    ></vuetable>
</template>

<script>
export default {
  name: 'ArticleTable',
  data () {
    return {
      columns: [
        'Bild',
        'Preis',
        'Ø Sales',
        'Bestand',
        'Kategorie',
        'Rang'
      ],
      articles: {}
    }
  },
  created () {
    this.getAll()
  },
  methods: {
    getAll () {
      this.$http.get('http://seller.dev/api').then(function (response) {
        this.articles = response.data
      }, function (response) {
        console.log(response)
      })
    }
  }
}
</script>
```

My returned JSON Response from my API build with Laravel

![image](https://cloud.githubusercontent.com/assets/8193345/21752620/401bf136-d5dc-11e6-9878-da53d4f8e74f.png)

Vue Devtools shows me the returned Object in the Vuetable Component

![image](https://cloud.githubusercontent.com/assets/8193345/21752634/6f54f11e-d5dc-11e6-9429-f7225ef4a0c3.png)

But there is no Content inside my Columns as you see

![image](https://cloud.githubusercontent.com/assets/8193345/21752636/76ded06c-d5dc-11e6-92c1-0e2cb3f1ac30.png)

And by the Way: How can i remove the blue Color Classes of the Table?

**Comment by kayyyy** [comment]
Okay got it. The Data Name has to be the Key of the Returned Object Key 👍

**Comment by paladosss** [comment]
What does it mean??????
