### ISSUE TITLE
How to sort ??

### ISSUE THREAD

**Issue by nusendra** [ratiw/vuetable-2#347]
I'm using Lumen for API service. When im using vuetable2, i can't sort my table. Until i read this

> **If your API endpoint supports sorting**, Vuetable can also automatically interact with it when you specify which column in the data is sortable.

How to make my endpoint support sorting? I dont know how to get this work. Please help me @ratiw 

Thanks :)

**Comment by ratiw** [comment]
@nusendra Please see [this](https://github.com/ratiw/vuetable-sample-api-endpoint/blob/master/app/Http/routes.php#L10-L54) as an example, then ask what you don't understand. Then, I may be able you to point to the necessary resource.

**Comment by nusendra** [comment]
thanks @ratiw . i'll be back soon :)

**Comment by nusendra** [comment]
sorry, i still confuse with your code. do yo have a simple code that handle only sort? or maybe something?
My code is like this simple

```
return User::orderBy('nama_user','asc')->paginate(5);
```

sort still not working. help me sir @ratiw for this great package

**Comment by ratiw** [comment]
@nusendra How do you request a sorted data from your Lumen API?

**Comment by nusendra** [comment]
im follow in the tutorial page. i don't know how to request a sorted data. sorry for my stupidness

**Comment by ratiw** [comment]
@nusendra You need to build your API to support sorting functionality first. Vuetable only works with your API to supply appropriate key to your API, it does not do the sort for you.

If you do not know about this, you need to learn how to sort your data in Laravel's Eloquent model first. Please do not jump right into working with Vuetable. You need to understand and get the basic stuff on your API working first, do not hurry. Start small, step by step.  Once you understand, things will get a lot easy.

**Comment by nusendra** [comment]
oh, so this sort is depend on my laravel code. Thanks for the direction, i will start to learn it now. Thanks mr. @ratiw

**Comment by nusendra** [comment]
Now i know how to solved this. look at my code below. This works perfectly on Lumen 5.5

```
public function index(Request $request)
    {
        if($request->sort) {
          $sort = explode('|',$request->sort);
          $user = User::orderBy($sort[0],$sort[1]);
        }else {
          $user = User::orderBy('id','asc');
        }
        $per_page = $request->per_page ? (int) $request->per_page : null;
        $model = $user->paginate($per_page);
        return $model;
    }
```
i don't need the multi sort, so i think its enough for me
Thanks mr. @ratiw for the right direction. Great package !!, u rock !! :+1:
