### ISSUE TITLE
Example of transition in detail row working  ?

### ISSUE THREAD

**Issue by wa05** [ratiw/vuetable-2#349]
Hi is there any example of this feature ? I cant make it work...

**Comment by ratiw** [comment]
@wa05 Sorry, `transition` tag was incorrectly placed in the source code. It should be before `<tr>`, not the `<td>`. Will try to find time to fix. I've messed up a few updates in the latest push. Sorry for the inconveniences.

**Comment by ratiw** [comment]
The fix has been pushed to the [`develop`](https://github.com/ratiw/vuetable-2/commit/56a961c70442ddfd6b8b6e84836798861e9cc631) branch.

**Comment by ratiw** [comment]
It is now in v1.7.2.
