### ISSUE TITLE
Row Selected/NotSelected Class

### ISSUE THREAD

**Issue by iamgaurav** [ratiw/vuetable-2#352]
Is there any way to have an active row class for the selected rows? 
What I want to achieve is mainly having a different row color for the selected row elements.

**Comment by ratiw** [comment]
Use `selectedTo` data variable and `row-class` prop.  I think someone has already asked about this, please search in the Issues, both open and closed ones.

**Comment by iamgaurav** [comment]
I checked the opened/closed issues, unfortunately, there isn't really an exact solution mentioned in anyone. 

Can the row-class prop be added only to the selected rows? How exactly can I modify a column's row-class prop?

**Comment by iamgaurav** [comment]
I got the solution. As you said using row-class and the selectedTo prop

**Comment by LeCoupa** [comment]
If this can help someone. (don't forget to add the id property to your data object!)

```javascript
methods: {
  onRowClass(dataItem) {
    let selected = this.$refs.vuetable.selectedTo;
    let result = "c-contacts-index__row";

    if (selected.includes(dataItem.id)) {
      result += " c-contacts-index__row--active";
    }

    return result;
  }
}
```
