### ISSUE TITLE
Header column sequence

### ISSUE THREAD

**Issue by KH-IT** [ratiw/vuetable-2#354]
Hi,
Do you have plans to implement a header column sequence property?
I generate the columns in the backend but in the frontend I want to save setting and let the user chose the column order.

`
let columns = [
  {
    name: 'name',
    sortField: 'name',
    sequence: 1
  },
  {
    name: 'email',
    title: 'Email Address',
    sequence: 3
  },
  {
    name: 'birthdate',
    sortField: 'birthdate',
    sequence: 2
  },
  {
    name: 'gender',
    sortField: 'gender',
    sequence: 4
  }
]
`

**Comment by ratiw** [comment]
Not really. You should be able to do that by just rearranging `tableFields` and use [localStorage](https://www.w3schools.com/html/html5_webstorage.asp) to store the settings.

**Comment by KH-IT** [comment]
Thx for the info then I would rearrange the tableField.
