### ISSUE TITLE
Conditional updating of row template / slot

### ISSUE THREAD

**Issue by hanxue** [ratiw/vuetable-2#364]
I want to make _specific_ rows editable, when a button is clicked. At the moment, I can globally toggle the content of a column by using slot and a "global" variable 

```html
        <template slot="year1" scope="props">
            <div class="edit-field" v-if="editMode">
              <md-field md-inline>
                <md-input 
                  v-model="props.rowData.year1"
                  :name="'year1' + props.rowIndex"
                  :id="'year1' + props.rowIndex">
                </md-input>
              </md-field>
            </div>
            <div v-else>{{props.rowData.year1}}</div>
          </template>
          <template slot="year2" scope="props">
            <div class="edit-field" v-if="editMode">
              <md-field md-inline>
                <md-input 
                  v-model="props.rowData.year2"
                  :name="'year2' + props.rowIndex"
                  :id="'year2' + props.rowIndex">
                </md-input>
              </md-field>
            </div>
            <div v-else>{{props.rowData.year2}}</div>
          </template>
          <!-- more columns -->
          <template slot="update" scope="props">
            <div class="custom-actions">
              <md-button class="md-icon-button md-dense md-raised md-primary"
                  @click="toggleEditMode(props.rowIndex)">
                  <md-icon>mode_edit</md-icon>
                  <md-tooltip>Modify</md-tooltip>
              </md-button>
              <md-button class="md-icon-button md-dense md-raised md-accent"
                  @click="deleteRow(props.rowData, props.rowIndex)">
                  <md-icon>delete_forever</md-icon>
                  <md-tooltip>Delete</md-tooltip>
              </md-button>
            </div>
          </template>

<script>
export default {
  methods: {
    toggleEditMode(rowIndex) {
      this.editMode = !this.editMode
    },
```

By default it is read-only

![image](https://user-images.githubusercontent.com/760008/35085418-9d16c1c8-fc63-11e7-80c4-823f23bff490.png)

When I click on the **Modify** button on row 2, then only the slot for row 2 is changed

![image](https://user-images.githubusercontent.com/760008/35085452-c273671e-fc63-11e7-86aa-b084a0cb09eb.png)

I have tried using `vuetable:row-clicked` or `__checkbox`, but those can only format the content and I cannot swap the content with `<input>`. 

Is there any way I can toggle the slot content for specific row?

**Comment by ratiw** [comment]
You should not think of it that way. As far as Vuetable is concerned, it is just another slot to render. (I personally think you should make it a component instead, so it can be reused)

It is your own component, Vuetable has nothing to do with it. It just renders it as you instructed it to do.

The code in your slot has to determine if it should just render text or input based on something or some events that would trigger it. So, when the user clicks a button, you can trigger a variable or an event that your component can act upon and does its job.
