### ISSUE TITLE
Pagination not working properly

### ISSUE THREAD

**Issue by shameerDPro** [ratiw/vuetable-2#367]
The below shows the pagination issue facing while implementing vuetable-2 using **webpack** in project:

![vuetable-2_display](https://user-images.githubusercontent.com/35690392/35220250-9eb59fb4-ff9b-11e7-8c24-64a31b2371f7.png)

And the following is how implementing:

//app-root.vue
-----------------
```
import { Vuetable, VuetablePagination } from 'vuetable-2'
Vue.component('vuetable', Vuetable)
Vue.component('vuetable-pagination', VuetablePagination)
```

//team.vue(component)
---------------------------
```
<template>
    <div>
        <h3>Teams</h3>
        <vuetable ref="vuetable" api-url="https://vuetable.ratiw.net/api/users" :fields="fields" pagination-path="" @vuetable:pagination-data="onPaginationData"></vuetable>
        <vuetable-pagination ref="pagination" @vuetable-pagination:change-page="onChangePage"></vuetable-pagination>
    </div>
</template>
<script>
    export default {
        data() {
            return {
                fields: ['name', 'email', 'birthdate', 'nickname', 'gender', '__slot:actions']
            }
        },
        mounted: function () {
        },
        methods: {
            onPaginationData(paginationData) {
                console.log('pased here');
                this.$refs.pagination.setPaginationData(paginationData)
            },
            onChangePage(page) {
                this.$refs.vuetable.changePage(page)
            }
        }
    }
</script>
```
please feel free to ask about more information require.

**Comment by ratiw** [comment]
What CSS framework you're using with Vuetable-2?

**Comment by shameerDPro** [comment]
thank you for your response, bootstrap css framework used.

let me know any other things require while using bootstrap, and also please suggest me proper way to use it in project.

In package.json added bootstrap like as follow
```
"dependencies": {
    "bootstrap": "^3.3.7"
  }
```
and imported which is in app-root.vue like as follow
```
import 'bootstrap';
```

**Comment by ratiw** [comment]
Vuetable is using Semantic UI by default. So, if you want to use Boostrap 3, you will need to config the `css` prop to use Bootstrap CSS classes instead. Please have a look at [this codepen](https://codepen.io/ratiw/pen/RxjpQd).

**Comment by shameerDPro** [comment]
thanks for saving my day.
