### ISSUE TITLE
Pagination Info not work

### ISSUE THREAD

**Issue by edgarscr** [ratiw/vuetable-2#370]
i follow the Lesson 8 from the wiki and the display pagination info it;s the same every time. never change to my custom setting:

im testing here https://codepen.io/ratiw/pen/GmJayw with the https://github.com/ratiw/vuetable-2-tutorial/wiki/lesson-08 and with this https://github.com/ratiw/vuetable-2/wiki/VuetablePaginationInfoMixin#-info-template but nothing happend the display it's the same i need to show just the amount

**Comment by ratiw** [comment]
Can you please set up a jsfiddle or codepen to showcase your problem?

**Comment by edgarscr** [comment]
@ratiw https://codepen.io/anon/pen/pavwzZ

**Comment by ratiw** [comment]
@edgarscr You are using prop from version 1 of Vuetable (`pagination-info-template`).

In Vuetable-2, you have to use `info-template` prop of VuetablePaginationInfo instead.
```html
<vuetable-pagination-info 
  ref="paginationInfo"
  info-template="{total} records"
></vuetable-pagination-info>
```

`pagination-info-no-data-template` is also not moved to `no-data-template` prop in VuetablePaginationInfo component.

**Comment by edgarscr** [comment]
@ratiw thanks u worked
