### ISSUE TITLE
Toggle or Detail Row

### ISSUE THREAD

**Issue by edgarscr** [ratiw/vuetable-2#371]
Can i get help to do that?

**Comment by ratiw** [comment]
@edgarscr Clone this repo, and `npm install && npm run dev`. It's better to study the code first, then ask.

**Comment by edgarscr** [comment]
@ratiw i have added alot of code but i get problems, first time i use this. 

i just need to display the DetailRow if i press on the row, i have added modal, delete, link, 

![boceto](https://user-images.githubusercontent.com/33737821/35601175-00bb2dba-0608-11e8-97ff-17853d6507c9.png)

**Comment by ratiw** [comment]
@edgarscr It's impossible for me to know what's wrong without see the behavior and your code. So, please make a jsfiddle or codepen to demonstrate the problem.

**Comment by edgarscr** [comment]
@ratiw check this: https://codepen.io/eCarrera92/pen/pavwzZ

**Comment by ratiw** [comment]
@edgarscr You need to take time to go through the tutorial more carefully. 

The code you put is mostly from my sample code which is already working on its own. But when you just copy and paste it together without really understanding what it does, it is definitely not going to make it work. 

The code clearly shows that you're mixing version 1 (which will only work in Vue 1.x) and version 2 code (which will also only work in Vue 2.x). Furthermore, you just copy and paste some codes from Vuetable source code to use outside by guessing that it will work, which is also "definitely" not going to work.

I'm here to help answer your questions about Vuetable, but I really hope that you care enough to learn more about it before asking questions. 

My suggestion is that you start with [Vuetable Tutorial](https://github.com/ratiw/vuetable-2-tutorial/wiki) again from the beginning, going step by step until the end. And making sure that you understand each lesson. If not, you can ask me the questions about that lesson. I'll be more than happy to help you on that.

**Comment by edgarscr** [comment]
@ratiw i finish to load Detail row, but i wanna ask if it's possible call funtions from out of detail row ? or display a modal with a detail row ?

**Comment by ratiw** [comment]
I don't see why you can't do that but it really depends on how you implement it. So, pick one problem and try it first. The best way to learn is to try it. There is no real best practice.

**Comment by edgarscr** [comment]
i read VueJS and Vuetable 2 and no one have that functions.

**Comment by ratiw** [comment]
I really have no idea what you mean. Can you please explain more what do you want to achieve? What is "that functions"? Try to write more to explain your thought in steps.
