### ISSUE TITLE
Preloader while data loading or refreshed

### ISSUE THREAD

**Issue by bogdan-dubyk** [ratiw/vuetable-2#372]
Hello, vuetable is awesome and really flexible, but I I can't find solution to one of my requirements. 

A want to add preloader while ajax is loaded or table refresh, is there any way to add it?

Thanks!

**Comment by ratiw** [comment]
@bogdan-dubyk You can listen to [`vuetable:loading`](https://ratiw.github.io/vuetable-2/#/Vuetable-Events?id=-vuetableloading) and [`vuetable:loaded`](https://ratiw.github.io/vuetable-2/#/Vuetable-Events?id=-vuetableloaded) event and interact with them accordingly.

`vuetable:loading` is emitted just before the ajax request is made, while `vuetable:loaded` is emitted after the request is either success or failed. You can also listen to `vuetable:load-success` and `vuetable:load-error` events as well. Please see the [doc](https://ratiw.github.io/vuetable-2/#/Vuetable-Events) for more detail.

If you're using Semantic UI, you can study the code in the sample [here](https://github.com/ratiw/vuetable-2/blob/master/index.html#L116-L117) and [here](https://github.com/ratiw/vuetable-2/blob/master/src/main.js#L330-L335). But if you're using other CSS framework, try searching to [issues](https://github.com/ratiw/vuetable-2/issues?utf8=%E2%9C%93&q=is%3Aissue++) and [pull requests](https://github.com/ratiw/vuetable-2/pulls?utf8=%E2%9C%93&q=is%3Apr+). I think someone had already put some samples there.

**Comment by bogdan-dubyk** [comment]
Thank you @ratiw, for some reason I miss this documentation [doc](https://ratiw.github.io/vuetable-2/#/Vuetable-Events)
