### ISSUE TITLE
console.log left in code

### ISSUE THREAD

**Issue by nathanbrizzee** [ratiw/vuetable-2#376]
Hi, I just pulled in your latest changes and a console.log was introduced and left in the production code.  It shows up in my console now a lot.
The function is getDefaultSortParam and it's in Vuetable.vue around line 842.

There's another console.log in the code that hasn't shown up yet in my console but it would be a good idea to comment it out or remove it.  It's also in Vuetable.vue in function callDataManager around line 1209.

**Comment by ratiw** [comment]
@nathanbrizzee Sorry for that. Will find time to remove them or you can help send a PR.

**Comment by ratiw** [comment]
This is fixed in v1.7.5.
