### ISSUE TITLE
  cellspacing

### ISSUE THREAD

**Issue by edgarscr** [ratiw/vuetable-2#378]
how i can add cells spacing?

because when i click on cells he click work on padding and margin, 

then i need to create a empty space betwen cells

**Comment by ratiw** [comment]
You may have to fork the project and add it with a prop to set its value.

**Comment by rribou** [comment]
You can eventually use a workaround like this:
```
mounted() {
    const el = this.$refs.vuetable.$el;
    el.setAttribute('cellspacing', '0');
}
```
