### ISSUE TITLE
Delete Cells

### ISSUE THREAD

**Issue by edgarscr** [ratiw/vuetable-2#380]
Hello @ratiw howdy?

**i have two questions:** 

* If you delete a ticket now, the ticketcell disappears, but can we make a effect like a red overlay while the ticketcell is disappearing?

If we delete a ticket, the ticket cell disappears, that is good but can we let the system appear new tickets live? Its good that we don’t have to reload page complete. Effect like a ticket is delete but backwards it appears live

that can be possible?

**Comment by ratiw** [comment]
@edgarscr I'm not sure. You might have to play around with `row-class` and css transition until you get the effect that you like. I'm not very good at animation with css.
