### ISSUE TITLE
How to add loading icon when load data ?

### ISSUE THREAD

**Issue by lchhieu** [ratiw/vuetable-2#381]
The server returns data that can take a long time. So how to add loading icon when loading data

**Comment by ratiw** [comment]
Basically, you listen to `vuetable:loading` and `vuetable:loaded` events and specify functions to handle adding/removing CSS class to your template. If you are using Semantic UI, you can see the example [`index.html`](https://github.com/ratiw/vuetable-2/blob/master/index.html#L115-L116) and [`main.js`](https://github.com/ratiw/vuetable-2/blob/master/src/main.js#L330-L335).

If you are using other CSS framework, you will have to research how that CSS framework does it.
