### ISSUE TITLE
Add Export Feature

### ISSUE THREAD

**Issue by mailnike** [ratiw/vuetable-2#39]
Hi,

Thanks for the great table code.
It would be really awesome if you add EXPORT to Excel or PDF or list feature. Can you please add this in your requested feature list.

Thanks.

**Comment by ratiw** [comment]
Thanks, @mailnike. But I really don't see the export functionality as the core feature of Vuetable, therefore it should not be (and will not be) implemented as part of Vuetable. 

I think there should be a javascript library doing the export to CSV functionality (which can be use in Excel) already (like [this](https://gist.github.com/adilapapaya/9787842) one). 

Exporting to PDF is actually not very simple and I don't think I'll have time and resource to pull it off easily.

**Comment by bsamadi** [comment]
@ratiw You just need to add the Buttons extension:
https://datatables.net/extensions/buttons/
