### ISSUE TITLE
Unexpected token: operator (>)

### ISSUE THREAD

**Issue by nkwinder** [ratiw/vuetable-2#395]
When running webpack -p (with UglifyJsPlugin configured)

Unexpected token: operator (>) [node_modules/vuetable-2/src/components/Vuetable.vue:330,0]

**Comment by ratiw** [comment]
@nkwinder Sorry, this doesn't help me much in pinpointing the problem. But last time I check everything seems to be working fine. So, I would suggest you look into your webpack config if it's correct, particularly the vue-loader.

**Comment by nkwinder** [comment]
solved my issue

i was using webpack.optimize.UglifyJsPlugin (v0.4.6 version of the uglify plugin)

added the latest one as described here:
https://webpack.js.org/plugins/uglifyjs-webpack-plugin/
