### ISSUE TITLE
How could I use vue-awesome for icons ?

### ISSUE THREAD

**Issue by killua99** [ratiw/vuetable-2#397]
I was testing many thing how could I use https://github.com/Justineo/vue-awesome with this table.

So far I was trying with thing like

```js
        css: {
          table: {
            tableClass: '',
            ascendingIcon: 'chevron-up',
            descendingIcon: 'chevron-down',
            handleIcon: 'ellipsis-v',
            renderIcon: (classes, options) => {
              return `<icon name="${classes[1]}"></icon>`
            }
          }
        }
```

but for obvious reason the render does not compile the component icon.

Thanks in advance for this component!

**Comment by ratiw** [comment]
@killua99 `renderIcon` only works with normal DOM element, so its purpose is to allow you to config Vuetable to work with CSS frameworks other than the default one. 

However, you should be able to use `vue-awesome` inside `__component` and `__slot` special fields.

**Comment by killua99** [comment]
I'm using a __slot for actions, but I'm trying to figure out how to add the __slot inside the th table, and not a data cell.

I'll keep looking the examples but if you have something quick to show me, what I'm trying to achieve.

Again thanks

**Comment by killua99** [comment]
For the way I see it, I could do:

```js
  import Vuetable from '../VuetableCustom'
  import VuetablePagination from '../VuetablePaginationCustom'
  import _ from 'lodash'
  import FilterBar from '../FilterBar'
  import Modal from '../Modal'
```

There I could use vue-awesome without any problem, is that right? then I could do something like `<icon :name="renderIcon" />`

I was trying to understand how could I use __component but I didn't figure out how edit _<thead>_ specially _th_

**Comment by ratiw** [comment]
@killua99 Unfortunately, the current version of Vuetable does not support `__slot` nor `__component` rendering in the `<thead>` and `<th>`.  That would be available only for field component in the next version. 

The only way to render icon in `<th>` in v1.7, you will have to use normal HTML like `<i class="fa fa-xxxx"></i>` instead.

**Comment by killua99** [comment]
Would you like a PR about it, or do you have some roadmap to include these things?

**Comment by ratiw** [comment]
@killua99 It's already in the work. Just need to tidy up things and re-do the tutorial and documentation before I can publish it. Thanks for asking anyway. 👍
