### ISSUE TITLE
Query issue with page number

### ISSUE THREAD

**Issue by baroneddy** [ratiw/vuetable-2#398]
Hi there!

I am using Drupal 8 as backend here with the module [Vuetable](https://www.drupal.org/project/vuetable). It return me a json properly formatted for vuetable. The issue I have is that the first page is page=0. When loading the vuetable, it queries page=1.

I tried to use query-params to ask for page 0, but it break the pagination. I feel like I am missing something here.

How should I approach this, should I rewrite my own VuetablePagination.vue?

Thanks for the help!

**Comment by ratiw** [comment]
@baroneddy Hmm, it never occur to me that there would be a pagination that starts with 0 actually. And yes, I think you would have to rewrite the logic in `VuetablePagination` to make it work because the first page is default to 1. If you look at `VuetablePaginationMixin`, you should be able to modify some logic in there to make it work with page 0.

**Comment by baroneddy** [comment]
I am going to try to alter the source first. That would seems smarter, I saw a lot of people asking for this in the Drupal community.

**Comment by baroneddy** [comment]
So I did manage to make it work on the vuetable side by change this:

`gotoPage (page) {
      if (page != this.currentPage && (page >= 0 && page <= this.tablePagination.last_page)) {
        this.currentPage = page
        this.loadData()
      }
},`

> page >= 0 instead of page > 0

and 

`initialPage: {
    type: Number,
    default: 0
},`

These 2 changes are in Vuetable.vue. I did those change directly in the node-module, so it is not a real solution, is there a way I can simply override those function in a component without having to override the whole thing?

Same for the 2 changes I did in the Mixin, I would like to keep as much as possible the default code but I would just need to override 2 functions.

Thanks for the help!

**Comment by ratiw** [comment]
@baroneddy I can probably introduce another prop for that purpose though.

**Comment by baroneddy** [comment]
That would indeed be awesome :)

**Comment by The-BlackWidow** [comment]
Hi @ratiw,
Have you implemented the new prop yet ?

**Comment by ratiw** [comment]
Not yet. Been very busy to get into the code right now.

**Comment by koapeadu** [comment]
Same problem here working with a Spring Data Rest API.
I tried @heyddi's solution but I had to make some more changes. So I submitted PR #458  with the additions.
Then, a more concise solution occurred to me: just subtracting 1 from the currentPage while building the request query params. See PR #459
