### ISSUE TITLE
Is there a way to add total row at the end of datatable

### ISSUE THREAD

**Issue by bogdan-dubyk** [ratiw/vuetable-2#401]
Hello. I want to add few rows at the end of datatable. 

The first row is a sum of all values per column on the current page
The second row is a sum of all values per column not related to the current page (this information I want to send from backend).

What is the best way to do so? Thanks!

**Comment by bogdan-dubyk** [comment]
I think I can use https://ratiw.github.io/vuetable-2/#/Data-Transformation , but I'm not sure how to link this method with vue table. In docu it mentioned only to **To setup the data transformation function, just create a transform method in the parent instance of Vuetable like so,** and I have 2 tables in the page, but this additional rows I need to show only for one the tables

**Comment by ratiw** [comment]
@bogdan-dubyk I'm not sure why you think the `transform` function would help on that. The purpose of the `transform` function is to transform your API data into the structure that Vuetable can use. It has nothing to do with adding two row at the end of the table.

I think what you can do at the moment is to create a `<div>` underneath Vuetable to display the data that you want, but it will not be in the exact column as it is not part of the `<table>`.

As I said, I'm not quite sure what you want to do with `transform` function, but if you could explain more about your intention with the sample of your data structure, maybe I can help guide you through.

By the way, in v2.0, you'll be able to override the <tfoot> slot.

**Comment by bogdan-dubyk** [comment]
@ratiw  thanks for your replay. 

Response:
```
{
   "current_page":1,
   "data":[
      {
         "date":"2018-03-06",
         "impressionsCount":"147",
         "price":"10.7441"
      },
      {
         "date":"2018-03-07",
         "impressionsCount":"285",
         "price":"20.9696"
      },
      {
         "date":"2018-03-08",
         "impressionsCount":"293",
         "price":"21.0682"
      },
      {
         "date":"2018-03-09",
         "impressionsCount":"277",
         "price":"19.5521"
      },
      {
         "date":"2018-03-10",
         "impressionsCount":"281",
         "price":"20.5475"
      },
      {
         "date":"2018-03-11",
         "impressionsCount":"253",
         "price":"17.7122"
      },
      {
         "date":"2018-03-12",
         "impressionsCount":"262",
         "price":"19.2261"
      },
      {
         "date":"2018-03-13",
         "impressionsCount":"248",
         "price":"17.7644"
      },
      {
         "date":"2018-03-14",
         "impressionsCount":"255",
         "price":"18.6671"
      },
      {
         "date":"2018-03-15",
         "impressionsCount":"237",
         "price":"17.0152"
      },
      {
         "impressionsCount":2538,
         "price":183.2665,
         "date":"Total on page"
      },
      {
         "impressionsCount":4000,
         "price":288.36599999999993,
         "date":"Total"
      }
   ],
   "first_page_url":"\/?page=1",
   "from":1,
   "last_page":2,
   "last_page_url":"\/?page=2",
   "next_page_url":"\/?page=2",
   "path":"\/",
   "per_page":"10",
   "prev_page_url":null,
   "to":10,
   "total":16
}
```

and there are 6 more records in this case for page 2.

So I want to add 2 more rows one to calculate total `impressionsCount` and  `price` per page, and one to calcualte overall  `impressionsCount` and  `price`  

Exmaple:

| First Date    | Amount of impressionsr | Payout   |
| ---------------- | ------------------------------- | ----------- |
| 2018-03-06  | 147                                | 10.7441 |
| 2018-03-07  | 285                                | 20.9696 |
| 2018-03-08  | 293l                               | 21.0682 |
| 2018-03-09  | 277                                | 19.5521 |
| 2018-03-10  | 281                                | 20.5475 |
| 2018-03-11  | 253                                | 17.7122 |
| 2018-03-12  | 262                                | 19.2261 |
| 2018-03-13  | 248                                | 17.7644 |
| 2018-03-14  | 255                                | 18.6671 |
| 2018-03-15  | 237                                | 17.0152 |
| **Page total**    | **2538**                                | **183.2665** | 
| **Overall total** | **4000**                                | **288.36599** |  

I need to add last to rows

About `transform` it was an assumption that maybe I inside  `transform` function I can loop through data and calculate/append that new rows.

**Comment by bogdan-dubyk** [comment]
I made it through the backend. I'm generating that 2  additional rows on the backend and returning 12 rows, not 10 as expected (but as  `per_page` value I'm still using 10  ), but pagination info showing a number of rows with this 2 additional rows. 
For the first page is **Displaying 1 to 12 of 16 items**
For seconds page **Displaying 11 to 18 of 16 items**

I'm assuming that pagination info calculating the number of rows and not using the value returned from backend??

And is there a way to make last two rows bold or somehow highlight them?

**Comment by ratiw** [comment]
@bogdan-dubyk I think you shouldn't do that, it would cost more problem down the road by messing with the actual data. I would instead suggest that you sent those two additional data as meta data (the same as the pagination information)

```json
{
   //...
   "prev_page_url":null,
   "to":10,
   "total":16,
   "page_total": { impressions: 2538, payout: 183.2665 },
   "overall_total": { impressions: 4000, payout: 288.36599 }
}
```

You could then use the `VuetablePaginationInfo` component as a guide to make your own `PaginationInfo` component where you can display those two information. You should also be able to modify the `<div>` style to make it looks attached to the Vuetable itself.

You should also use `VuetablePaginationInfoMixin` mixin in your component, so that it can share the same mechanisim in passing the pagination data from Vuetable to your component. Then, you can link it together like this,

```html
<vuetable ref="vuetable"
  //...
  @vuetable:pagination-data="onPaginationData"
></vuetable>

<total-component ref="totalComponent"
></total-component>

<vuetable-pagination ref="pagination"
></vuetable-pagination>
```
```javascript
  //...
  onPaginationData (tablePagination) {
    //...
    this.$refs.totalComponent.setPaginationData(tablePagination)
  }
```

**Comment by bogdan-dubyk** [comment]
Thank you @ratiw !!

**Comment by Leonidas199x** [comment]
Has anyone been able to achieve this? I am looking to do a similar thing, but am having a real struggle getting the two components to know anything about one another, for it to actually look like a total that applied to the vuetable.

**Comment by THCMAGO** [comment]
Hi, any news???
