### ISSUE TITLE
Header not fixed when row details lead to render a scrollbar

### ISSUE THREAD

**Issue by Mweydert** [ratiw/vuetable-2#404]
Hi, 

First thank you for this awesome lib !

I face what seems to be a bug when openning a detail-row. 
My table has columns width and height fixed so that my header add the 'vuetable-gutter-col' when displaying a large number of items.
Nevertheless the gutter is not added when opening a detail-row (that makes a scrollbar appear).

Is there any reason preventing to call the method [fixHeader](https://github.com/ratiw/vuetable-2/blob/master/src/components/Vuetable.vue#L756) within the [toggleDetailRow](https://github.com/ratiw/vuetable-2/blob/080623e3888014525bb44ade09b013e9eec02d08/src/components/Vuetable.vue#L1151) method ? I think this would solve this problem.

BR,
Michael

**Comment by ratiw** [comment]
@Mweydert What environment are you on? Mac or Windows? Which browser you have experience this? Is it possible to setup a jsfiddle or codepen to demonstrate your problem?

**Comment by Mweydert** [comment]
I am working on Ubuntu 14.04 (trusty), Node.js 6.13.1 and Vuetable-2 1.7.5. 
I experienced this issue on Chrome 59 and Firefox 52.

The API I use is only reachable within my company so it's a bit complicated for me to setup a codepen that demonstrates my situation.
While I am not able to show you the exact problem I described, I set up a [codepen](https://codepen.io/MWeydert/pen/YaVvep) that illustrates my point.

As you can see, when not running vuetable in api-mode, the header is not fixed when the scrollbar appeared (just add a few items to see the scrollbar appear in my codepen).

If I am not mistaking, [FixHeader](https://github.com/ratiw/vuetable-2/blob/080623e3888014525bb44ade09b013e9eec02d08/src/components/Vuetable.vue#L756) creates the glutter within the table header to fix the columns display. 
This method seems to be called only in [setData](https://github.com/ratiw/vuetable-2/blob/080623e3888014525bb44ade09b013e9eec02d08/src/components/Vuetable.vue#L642) and [loadSuccess](https://github.com/ratiw/vuetable-2/blob/080623e3888014525bb44ade09b013e9eec02d08/src/components/Vuetable.vue#L734) : 2 methods related to api-data events.

Thus when making an action that makes a scrollbar appear but is not caused by data loading or data setting (and so are not executing [loadSuccess](https://github.com/ratiw/vuetable-2/blob/080623e3888014525bb44ade09b013e9eec02d08/src/components/Vuetable.vue#L734) or  [setData](https://github.com/ratiw/vuetable-2/blob/080623e3888014525bb44ade09b013e9eec02d08/src/components/Vuetable.vue#L642)), the display is not fixed. 

This is my case when toggling a detail-row: 
1. Data don't change
2. scrollbar appears as the height of table increase
3. header is not adjusted (no glutter added)

This is also what happens the [codepen I provide](https://codepen.io/MWeydert/pen/YaVvep) when adding data without the API.

Hope this helps to understand this issue. Feel free to tell me if some points remain unclear or if a more precise fiddle is needed.

**Comment by ratiw** [comment]
@Mweydert Unfortunately, I'm unable to test it on Ubuntu. But I've looked at the codepen you prepared, the header is still fixed as usual when I added more rows. I've tested this on both Mac (with latest Chrome, Firefox, and Safari) and on Windows 10 (with latest Chrome and Firefox version), they are all worked as it should. Is it possible for you to test this on any other machine?

**Comment by Mweydert** [comment]
@ratiw I have tested the codepen on one of my coworker machine (chrome 61) and still have the issue.
To be sure, you are saying you don't see the small gap between table header columns and table body columns ? 
![vuetable gap columns](https://user-images.githubusercontent.com/14289151/37819795-07999d34-2e7f-11e8-9718-944409f47a97.PNG)

**Comment by ratiw** [comment]
Oh, I see what you mean. I do miss that. I think I've already fixed at for v2.0, but may not port that back to v1.7 yet. Will look into it. Sorry, about that.

**Comment by ratiw** [comment]
It's already in the next version.

**Comment by kingasds** [comment]
I have similar problem as well, and I am already using @next branch already

I am currently using following method to temporary solve the issue.

1. adding a ref to you vuetable
`vuetable ref="vuetable"`

2. when ever you need to update the table, call following method 
`methods: {
    tableUpdate() {
      if (this.$refs.vuetable) {
        this.$refs.vuetable.updateHeader()
      }
    }
  },`
( updateHeader() is the new method provided in fix #359 #404 )
