### ISSUE TITLE
use callback to render a cell from the parent  component

### ISSUE THREAD

**Issue by gabyrusu** [ratiw/vuetable-2#407]
how can I use the callback to render a cell from the parent component? I don't want all my render functions to go on "my-vuetable" component.

user-config.js
```
...
{
    name    : 'gender',
    callback: 'renderGender'
},
...
```
UserComponent.vue

```
import UserConfig from './user-config.js';
import Datatable from './MyVuetable';
...
methods: {
    renderGender(value) {
        return value === 'M'
            ? '<span class="badge badge-info">Male</span>'
            : '<span class="badge badge-danger">Female</span>';
    },
}
...
```

This doesn't work. That function is not being called.

Any help?

**Comment by ratiw** [comment]
Vuetable only looks for the given callback function name from within its field definition and the parent instance. My guess is that your function is in the grand-parent instance, so it didn't work.

```
UserComponent.vue
 +-- MyVuetable.vue
      +-- Vuetable
```

In v2.0, the callback will only support Function, so function lookup will no longer work. I would recommend putting the callback (formatter) function directly in the field definition itself for field specific or use some kind of global instance function for reusable functionality.

**Comment by gabyrusu** [comment]
Thanks @ratiw! 

I already did. In fact I created a "utilities" file in which I have all my reusable render functions. The redenderDate function, for example,  will be used in a lot of places so it makes no sense declaring it on every grid configuration file.

**Comment by gabyrusu** [comment]
How can I pass extra arguments on the callback function if used like this?

datagrid-utils.js
```
...
renderDate(value, format = 'DD-MM-YYYY') {
    return (value === null) || moment(value, 'YYYY-MM-DD').format(format);
},

```

user-config.js
```
import Utils from './datagrid-utils';

...
{
    name    : 'birthdate',
    title   : 'Birth date',
    callback: Utils.renderDate
},
```
