### ISSUE TITLE
Table shows empty data because the backend return dictionary

### ISSUE THREAD

**Issue by sherlyseptiani** [ratiw/vuetable-2#408]
I set the header from httpOptions but apparently it still doesn't work, can you just enable sort, pagination, filter, etc on local vue data? I think it's more flexible that way; to handle the request and data manipulation by ourselves and then use your table just to display it properly.
Thanks

This is what it looks like on my code anyway:
` httpOptions: {headers: { Authorization: 'Basic YXBpOnBhc3N3b3Jk' }}`

```
  <vuetable ref="vuetable"
          api-url="https://xxx.com/civil/citizens"
          :httpOptions="httpOptions"
          :fields="fields"
          pagination-path=""
          @vuetable:pagination-data="onPaginationData">
```

**Comment by ratiw** [comment]
@sherlyseptiani Can you please explain more why it doesn't work? You didn't get the value you put in the `httpOptions` in the backend?

You could use Vuetable in "Data" mode by specifying `api-mode="false"` and feed the data you want Vuetable to display via `data` prop or `setData` function. See example [here](https://codepen.io/ratiw/pen/LyLpow?editors=1010).

**Comment by sherlyseptiani** [comment]
Sorry it's my fault. The HTTP options actually works but it returns dictionary instead of array, so the table shows empty data. I will edit this issue

**Comment by ratiw** [comment]
What is the dictionary you mentioned looks like?

**Comment by sherlyseptiani** [comment]
something like this:

> {
>     "777": {
>         "province": "DKI Jakarta",
>         "city": "Jakarta Pusat",
>         "dateOfDeath": "-",
>         "citizenId": "777",
>         "firstName": "Sherly",
>         "lastName": "Test",
>         "photoBase64": "dummybase64",
>         "dateOfBirth": "11/12/1991",
>         "streetAddress": "Sudirman",
>         "marriageStatus": "Single",
>         "gender": "Female",
>         "ICCID": "32111"
>     }, ...
> }

**Comment by ratiw** [comment]
Actually, it looks more like an object containing data. Are you sure this is correct?

If it is an array of object, it should look something like this
```javascript
[      // <-- indicating array of objects
  {
    "province": "DKI Jakarta",
    "city": "Jakarta Pusat",
    "dateOfDeath": "-",
    "citizenId": "777",
    "firstName": "Sherly",
    "lastName": "Test",
    "photoBase64": "dummybase64",
    "dateOfBirth": "11/12/1991",
    "streetAddress": "Sudirman",
    "marriageStatus": "Single",
    "gender": "Female",
    "ICCID": "32111"
  },
  //...
]
```

If it actually is correct, you will have to declare [`transform`](https://github.com/ratiw/vuetable-2/wiki/Data-Transformation) function to transform your data into the structure that Vuetable can work with. See [here](https://github.com/ratiw/vuetable-2/wiki/Data-Format-(JSON)).

**Comment by sherlyseptiani** [comment]
Thank you so much for your help and incredibly fast responses. I managed to do it thanks to your help. Much appreciated!! Thank you!!!
