### ISSUE TITLE
Is this an expected behavior of field callback?

### ISSUE THREAD

**Issue by Tarasovych** [ratiw/vuetable-2#421]
```vue
<vuetable ref="vuetable"
                  api-url="http://vuetable.ratiw.net/api/users"
                  :fields="fields"
                  pagination-path=""></vuetable>
```
and 
```js
data() {
            return {
                fields: [
                    'name', 'email',
                    {
                        // name: 'screenshot',
                        // callback: 'screenshot'
                    }
                ]
            }
        },
```
causes that no data is loaded (even no api-url is called), because of empty object after `'name', 'email',`.

**Comment by ratiw** [comment]
Passing an empty object is never an intended behavior. Vuetable also doesn't check for this, so the outcome is undetermined. It probably throws an error and stop all other functions. 

Did you see any error in the console?

**Comment by Tarasovych** [comment]
@ratiw there were no console errors. Thanks.
