### ISSUE TITLE
Error when i use '__checkbox'

### ISSUE THREAD

**Issue by boomhq** [ratiw/vuetable-2#422]
Hello Ratiw, 

Thanks for your job one more time it's always amazing . I have a probleme maybe somone can help me.

When i add on my fields definition '__checkbox'(I used track-By props with string) . The pagination break with this error : 
> this.tableData.filter is not a function
    at VueComponent.checkCheckboxesState (vuetable-2.js?f505:formatted:1978)

On detail the Vuetable component update fine : tableData with new value but no render.
If remove '__checkbox' all works fine.

On another Table instance i dont have this probleme. The fetch response have the same format just one trackBy ID and another by custom key.
Have you an idea ? 

Thank you in advance

PS: Maybe related to #80

**Comment by ratiw** [comment]
This is strange. Can you create a sample project on jsfiddle, codepen, or codesandbox to demonstrate this? It will help me go through the code and find out the problem.

**Comment by boomhq** [comment]
Hello Ratiw i have solved my problem (from my side).
The Error appear if the data representation change. If i dont use __checkbox vuetable2 negociate with no problem. But if it's used  checkstateCheckbox failed (logic)

Origin : 
I'm use Laravel 5.5 and use a paginate for collection like LengthAwarePaginator but for an unknow reason
On Page 1 the data have this presenter : 

`data:[
{obj},
{obj}
]`

But on page >1 the representation is : 

`data:[
1: {obj},
2: {obj}
]`

I (ugly) fix this with a $data->flatten()  before response.

Sorry for wasted time and thank you for your work. Your documentation and your work are crazy and really formative.
