### ISSUE TITLE
[Vue warn]: Missing required prop: "rowData"  found in <Root>

### ISSUE THREAD

**Issue by Tarasovych** [ratiw/vuetable-2#423]
I didn't found similar issue yet.
My code:
```vue
    <vuetable ...>
            <template slot="actions" slot-scope="props">
                <div>
                    <button class="btn btn-primary" @click.prevent="test"></button>
                </div>
            </template>
        </vuetable>
```
```vue
export default {
        //...
        props: {
            rowData: {
                type: Object,
                required: true
            }
        },
```
```vue
methods: {
            test() {
                console.log('this works')
            }
        }
```
I have an error `[Vue warn]: Missing required prop: "rowData"  found in <Root>`.
What may be wrong?
Another question: what for is `required` inside `rowData {}`? Still can't clarify. By the way if I remove `required: true` there is no such error.

**Comment by ratiw** [comment]
@Tarasovych See [this](https://vuejs.org/v2/guide/components-props.html#Prop-Validation). You should go through [Vue Guide](https://vuejs.org/v2/guide/) first before attempting to work on any Vue component.

**Comment by Tarasovych** [comment]
@ratiw may I ask when does `rowData` is loaded according to Vue lifecycle?
If I do so
```vue
<vuetable>
    ...
            <template slot="actions" slot-scope="props">
                <div v-if="this.rowData"> <!-- this doesn't render -->
                    <span>text</span>
                </div>
            </template>
</vuetable>
```

**Comment by Tarasovych** [comment]
I'm ready to help with documentation. If your package uses latest Vue features, it might be useful to write about that.

**Comment by ratiw** [comment]
Thanks @Tarasovych. Currently, I'm trying to finish the first draft v2.0-beta documentation. Once it is up, it will need your help to improve.
