### ISSUE TITLE
Is it possible to have separate field for sorting?

### ISSUE THREAD

**Issue by Tarasovych** [ratiw/vuetable-2#426]
I want to use `&sortBy=foo&orderBy=bar` instead `&sort=foo|bar`. Is is possible with your API?
I found only one way to hardcode: set `:query-params="{}"` and write all query inside `api-url`.

**Comment by ratiw** [comment]
You could create a function named `getSortParam` in your main Vue instance (the parent of Vuetable).

If present, it will be called by Vuetable with the current `sortOrder` array. It should return query string of the sort parameter that you want.

```
methods: 
  getSortParam(sortOrder) {
    // this example is for single sort column only
    return 'sortBy='+sortOrder[0].sortField+'&orderBy='+sortOrder[0].direction
  }
```

**Comment by Tarasovych** [comment]
This works for me now
```vue
:query-params="{ sort: 'sortBy', page: 'page', perPage: 'per_page' }"
```
and
```vue
getSortParam(sortOrder) {
                return sortOrder[0].sortField+'&orderBy='+sortOrder[0].direction
            }
```
