### ISSUE TITLE
JSON GET option

### ISSUE THREAD

**Issue by rcarmich** [ratiw/vuetable-2#429]
Aside from disabling api mode and using axios directly, is there any way to turn on a method whereby the api-url is used but instead of query parameters, a JSON object is sent? Whether or not it's agreed to be a good standard practice may be debatable but some of us have REST endpoints that do this.

Something like:
```
<template>
  <vuetable ref="vuetable"
    api-url="https://vuetable.ratiw.net/api/users"
    :fields="['name', 'email', 'birthdate']"
    :jsonGet=true
    :jsonGetOverride=myJsonMethod
  ></vuetable>
</template>

...
export default {
...
methods: {
  myJsonMethod (data) {
    // data is pre-populated with sort-order, page_number, etc. from the normal request params
    return data; // this is what's passed to the GET
  }
}
...
}
...
```

**Comment by ratiw** [comment]
Use [`http-fetch`](https://ratiw.github.io/vuetable-2/#/Vuetable-Properties?id=-http-fetch-v17) prop.

**Comment by rcarmich** [comment]
That works great for me, thank you.
