### ISSUE TITLE
Get all row data by track-id

### ISSUE THREAD

**Issue by edgarscr** [ratiw/vuetable-2#434]
Is it possible to get all the information of a row from another row? example I'm in row A and I press a button to get the next id: my current Track-id = 1 + 1. which would get all the information by track-id = 2

**Comment by ratiw** [comment]
@edgarscr It is possible, but not recommend. All the data should be available in `tableData` variable. You should be able to loop through and find a specific id and get the array index. Then, it is a matter of getting the data from the previous or next array index.
