### ISSUE TITLE
Latest version grid design effected 

### ISSUE THREAD

**Issue by navrt007** [ratiw/vuetable-2#435]
After installing the newest version it is breaking the look for the grid and we were facing issue with the scroll which you have fixed .Below is the code and can you helep ?
The code 
<vuetable ref="vuetable"
                  :api-mode="false"
                  :data="extraTextInfo.extraTexts" data-path=""
                  :fields="fields" :css="css.table">
            <template slot="extraTextTitle" scope="props">
                <div v-if="props.rowData.extraTextTitle==null || props.rowData.extraTextTitle==''" class="text-muted">{{props.rowData.defaultExtraTextTitle}}</div>
                <div>{{props.rowData.extraTextTitle}}</div>
            </template>
            <template slot="extraTextDescription" scope="props">
                <div v-if="props.rowData.extraTextDescription==null || props.rowData.extraTextDescription==''" class="text-muted">{{props.rowData.defaultExtraTextDescription}}</div>
                <div v-else>{{props.rowData.extraTextDescription}}</div>
            </template>
            <template slot="move" scope="props">
                <div>
                    <a v-on:click="movedown(props.rowIndex)"><span class="material-icons mi-downarrow"></span></a>
                    <a v-on:click="movelast(props.rowIndex)"><span class="material-icons mi-doubledownarrow"></span></a>
                    <a v-on:click="moveup(props.rowIndex)"><span class="material-icons mi-uparrow"></span></a>
                    <a v-on:click="movetop(props.rowIndex)"><span class="material-icons mi-doubleuparrow"></span></a>
                </div>
            </template>
            <template slot="actions" scope="props">
                <div>
                    <a v-b-modal.myModal @click="editExtraText(props.rowData)"><span class="material-icons mi-edit"></span></a>
                    <a v-on:click="deleteExtraText(props.rowData)"><span class="material-icons mi-delete"></span></a>
                </div>
            </template>
        </vuetable>

fields: [
                {
                    name: 'extraTextTypeName',
                    title: 'Extra Text Type'
                },
                {
                    name: '__slot:extraTextTitle',
                    title: 'Title'
                },
                {
                    name: '__slot:extraTextDescription',
                    title: 'Extra Text'
                },
                {
                    name: '__slot:move',
                    title: 'Move',
                    titleClass: 'center aligned',
                    dataClass: 'center aligned action'
                },
                {
                    name: '__slot:actions',
                    title: 'Action',
                    titleClass: 'center aligned',
                    dataClass: 'center aligned action',
                }
![gridbreaking](https://user-images.githubusercontent.com/686325/39619385-2e905e8c-4f77-11e8-8f7a-96aaeac5b095.png)

**Comment by ratiw** [comment]
@navrt007 from `next` branch or `develop` branch?

**Comment by navrt007** [comment]
from next branch

**Comment by ratiw** [comment]
@navrt007 In the `next` version, you need to set `width` option for each column in the fields definition. Also, you no longer need to prepend `__slot:` to the slot field, it is now auto-map to the scoped slot you defined inside `<vuetable>`.

**Comment by navrt007** [comment]
It is resolved thanks for the help
