### ISSUE TITLE
Can I Filter many columns simultaneously?

### ISSUE THREAD

**Issue by jpldev** [ratiw/vuetable-2#440]
Can I Filter many columns simultaneously?

So for example add two filter-bar, 

for example I have a table with clients, and i want to filter NAME: John, AGE: 20

**Comment by ratiw** [comment]
@jpldev This depends on your API backend. If it supports it, Vuetable should be able to be configure to send those filters to the backend for processing. Vuetable is just a presentation layer component, it doesn't do any processing itself unless you turn on Data mode, but you still have to write code to handle those processing yourself.
