### ISSUE TITLE
Programatically generate template slots: Property or method "props" is not defined on the instance but referenced during render

### ISSUE THREAD

**Issue by hanxue** [ratiw/vuetable-2#449]
I currently use `__slot` templates this way:

```html
<template slot="year1" slot-scope="props">
              <div class="edit-field" v-if="editMode &&
                editableRow(props.rowData.title)">
                <md-field md-inline>
                  <md-input 
                    v-model="props.rowData.year1"
                    :name="'year1' + props.rowIndex"
                    :id="'year1' + props.rowIndex">
                  </md-input>
                </md-field>
              </div>
              <div v-else>{{props.rowData.year1}}</div>
            </template>
            <template slot="year2" slot-scope="props">
              <div class="edit-field" v-if="editMode &&
                editableRow(props.rowData.title)">
                <md-field md-inline>
                  <md-input 
                    v-model="props.rowData.year2"
                    :name="'year2' + props.rowIndex"
                    :id="'year2' + props.rowIndex">
                  </md-input>
                </md-field>
              </div>
              <div v-else>{{props.rowData.year2}}</div>
            </template>
            <!-- continue until x number of years -->
```

with `fields` set to a dynamically generated json

```json
	{
		"name": "__slot:year[1]",
		"title": "1",
		"titleClass": "center aligned",
		"dataClass": "center aligned",
		"width": "40px"
	},
	{
		"name": "__slot:year[2]",
		"title": "2",
		"titleClass": "center aligned",
		"dataClass": "center aligned",
		"width": "40px"
	},
```

Full JSON available at https://api.myjson.com/bins/mt5vu

When I try to dynamically loop through the number of years and generate the slot template

```html
            <template v-for="y in totalProjectPeriod" :slot="'year-' +(y+1)">
              <div class="edit-field" v-if="editMode &&
                editableRow(props.rowData.title)">
                <md-field md-inline>
                  <md-input 
                    :v-model="'props.rowData.year[' + (y+1) + ']'"
                    :name="'year[' + (y+1) + ']'"
                    :id="'year[' + (y+1) + ']'"
                  </md-input>
                </md-field>
              </div>
              <div v-else>{{props.rowData.year[y+1]}}</div>
            </template>
```

I see this error message:

```
[Vue warn]: Property or method "props" is not defined on the instance but referenced during render. Make sure that this property is reactive,either in the data option, or for class-based components, by initializing the property.
```

From the generated sources:

```
[
              _vm._l(_vm.totalProjectPeriod, function(y) {
                return _c(
                  "template",
                  {
                    attrs: { slot: "year-" + (y + 1) },
                    slot: "year-" + (y + 1)
                  },
                  [
                    _vm.editMode && _vm.editableRow(_vm.props.rowData.title)
                      ? _c(
                          "div",
                          { staticClass: "edit-field" },
                          [_c("md-field", { attrs: { "md-inline": "" } })],
                          1
                        )
                      : _c("div", [
                          _vm._v(_vm._s(_vm.props.rowData.year[y + 1]))
                        ])
                  ]
                )
              })
```

All my code for generating the table header and data is in `created()`. 

Is it because `props.rowData` will only generated after the vue instance is mounted, and I am trying to access `props` in the template before it is available? Is there any workaround for dynamically generating table column `__slot`'s?

### Environment

Vue: 2.5.2
Vuetable: 1.7.5
Node: 9.11.1

**Comment by ratiw** [comment]
@hanxue You do not have `slot-scope="props"` defined.

You also define dynamic slot like `year-XX`, but the field definition is defined as `year[XX]`. They are never gonna match. This is the next error you will encounter.

You also do not provide the sample data record, so I'm not sure if this `:v-model="'props.rowData.year[' + (y+1) + ']'"` will work.

**Comment by ratiw** [comment]
@hanxue See [this CodeSandbox](https://codesandbox.io/s/ym4q1w5zj9)

If I could, I would reformat your JSON data to be like this, so it would be more organized and easier to work with.
```json
[
  {
    "sequence1": "1",
    "sequence2": "",
    "id": "projectIncomeTitle1",
    "title": "项目收入",
    "total": "￥2,200.00",
    "year": {
      "1": "￥88.00",
      "2": "￥88.00",
      "3": "￥88.00",
      //...
      "25": "￥88.00"
     }
  },
  //..
]
```

What I did instead is using Vuetable's [data transformation function](https://ratiw.github.io/vuetable-2/#/Data-Transformation) to transform your data into the above format.

Then the dynamic slot can be easily achieved as you've been trying to do. The name of the slot does not have to be in `year[x]` format as it would be a bit misleading. But since you've used that, I also have to use that to name the dynamic slot.

In fact, the `year` should actually be an array, but Vuetable is not yet support referencing array data in the field, it has to be an object instead.

This could actually be done a lot easier using `__component`. Unfortunately, `__component` in v1.7 does not yet support optional parameter, so the only way in v1.7 is to do it as `__slot`.

**Comment by hanxue** [comment]
Many thanks for your tip for making the `years` value as an array. I could not use transform because I load the data from an array instead of an API. I was having weird problems trying to access the `years` properties when I realized that one of the row do not have `years` property, because it is used for only display

![image](https://user-images.githubusercontent.com/760008/40289465-05877972-5ceb-11e8-8bbe-9e3e1435d318.png)


Anyway, here is my working code, in case anyone is having a similar problem

# Solution

### Fields
The `fields` JSON object is in the format of `year[1]`, `year[2]`... `year[25]`

```json
[
  {
    "name": "__slot:total",
    "title": "合计",
    "titleClass": "center aligned",
    "dataClass": "center aligned column-total",
    "width": "60px"
  },
  {
    "name": "__slot:year[1]",
    "title": "1",
    "titleClass": "center aligned",
    "dataClass": "center aligned",
    "width": "40px"
  },
  {
    "name": "__slot:year[2]",
    "title": "2",
    "titleClass": "center aligned",
    "dataClass": "center aligned",
    "width": "40px"
  },
  //...
]
```

Full JSON object here https://api.myjson.com/bins/f97re

### tableData

The tableData is in this format `{ year: 1: "￥88.00", 2: "￥88.00",...}`

```json
[
  {
    "sequence1": "1",
    "sequence2": "",
    "id": "projectIncomeTitle1",
    "title": "项目收入",
    "total": "￥2,200.00",
    "year": {
      "1": "￥88.00",
      "2": "￥88.00",
      "3": "￥88.00",
      "4": "￥88.00",
      "5": "￥88.00",
      "6": "￥88.00",
      "7": "￥88.00",
      "8": "￥88.00",
      "9": "￥88.00",
      "10": "￥88.00",
      "11": "￥88.00",
      "12": "￥88.00",
      "13": "￥88.00",
      "14": "￥88.00",
      "15": "￥88.00",
      "16": "￥88.00",
      "17": "￥88.00",
      "18": "￥88.00",
      "19": "￥88.00",
      "20": "￥88.00",
      "21": "￥88.00",
      "22": "￥88.00",
      "23": "￥88.00",
      "24": "￥88.00",
      "25": "￥88.00"
    }
  },
]
```
Full JSON object here https://api.myjson.com/bins/zhybu

### Template Slot

I will loop through every year and generate a `<template :slot="'year[25]'" slot-scope="props">` for each year. The actual value of the year is `{{props.rowData.year[y]}}`. There is some additional conditions to convert the cell into an editable input - see #364 

```html
            <template v-for="y in parseInt(totalProjectPeriod)" :slot="'year['+y+']'" slot-scope="props">
              <div v-if="props.rowData.year">
                <div class="edit-field" v-if="editMode &&
                  editableRow(props.rowData.title)">
                  <md-field md-inline>
                    <md-input 
                      :v-model="'props.rowData.year['+y+']'"
                      :name="'year['+y+']'"
                      :id="'year['+y+']'"
                    </md-input>
                  </md-field>
                </div>
                <div v-else>{{props.rowData.year[y]}}</div>
              </div>
            </template>
```
