### ISSUE TITLE
Vuetable overflowing its container

### ISSUE THREAD

**Issue by sherlyseptiani** [ratiw/vuetable-2#450]
If I have a quite large dynamic data, the vuetable will exceeds the container (the red one on pic).
How to prevent this from happening? Thanks
![screenshot from 2018-05-22 13-43-41](https://user-images.githubusercontent.com/21187404/40346324-9ea36770-5dc6-11e8-9304-c8e7098d77e0.png)

**Comment by Georgeek** [comment]
hi! You can solve it by using css attributes like
`word-break: break-all;`
also look at css `word-wrap` and `white-space`

more info => [css-tricks](https://css-tricks.com/snippets/css/prevent-long-urls-from-breaking-out-of-container/)
