### ISSUE TITLE
Computed column?

### ISSUE THREAD

**Issue by martixy** [ratiw/vuetable-2#454]
Is it possible to have a computed column?

I.e. what's already possible via the `callback` option, but with access to the rest of the data?

In my case I have an API that delivers data in "unassembled" format, containing a couple data arrays and what is essentially a join column that says Entry X = index Y in this array and index Z in that array.

Edit:
After a bit of research, it is, mostly possible via the `__component` special field. **However is there some way to access the api response object?** Reading through vuetable's API and even the code and failing to see one.

Edit2: 
Okay, so... because waiting around wasn't gonna do anything I forked and made a couple of small 
[changes](https://github.com/martixy/vuetable-2/commit/35d76848175d75e9963d3d03d7fca633bfaedf13#diff-d122f08d3989f6eff49187eb7f1c8703).

If this is worthy of a PR, I'll gladly submit one, though the documentation might need updating too.

**Comment by ratiw** [comment]
@martixy In v2.0, you can use field definition object for that as it will no longer filter out other option. That means you can define additional parameter inside field definition object as you like and you can access it via `field` object from both `__component` (which is now superseded by Field Component) and `__slot` (which is superseded by Field Slot). The underlying implementation has changed quite a bit.

**Comment by martixy** [comment]
And where is this v2.0?
Tags currently reach only till v1.7.5.

**Comment by e-abdelbasset** [comment]
well there is always a simple solution

let's say this is what you get from the server through your API : 
```json
{
  "links": {
    "pagination": {
      "total": 50,
      "per_page": 15,
      "current_page": 1,
      "last_page": 4,
      "next_page_url": "...",
      "prev_page_url": "...",
      "from": 1,
      "to": 15,
    }
  },
  "data": [
    {
      "id": 1,
      "attributes": {
        "name": "Tyrion Lannister",
        "nickname": "The imp",
        "email": "xxx@xxx.xxx",
        "birthdate": "xxxx-xx-xx",
        "gender": "Male",
        "group_id": 1
      }
    },
      .
      .
      .
  ]
}
```
you can customize the name column to look like something like this :

```html
<template>
    <vuetable 
        ref="vuetable"
        :fields="fields"></vuetable>
</template>
<script>
    export default {
        data() {
            return {
                fields: [
                    {
                        title: 'Full name',
                        name: "attributes", // instead of attributes.name => this will return the entire attributes' object 
                        sortField: 'name', // or nickname
                        callback: (attributes) => {
                            let name = attributes.name;
                            let nickname = attributes.nickname;
                            return `${name} (${nickname})` // this will return : Tyrion Lannister (The imp)
                        }
                    },
                ]
            };
        }
    }
</script>
```

**Comment by martixy** [comment]
Yea, that's one way. The callback, as noted in the old documentation is not the best option to do this(its purpose being formatting).

Since I posted here last time, we have a beta release of v2, which provides the necessary mechanisms for accomplishing this in a more structured manner.
