### ISSUE TITLE
Data transform / slot interaction

### ISSUE THREAD

**Issue by martixy** [ratiw/vuetable-2#455]
I just ran into an issue with the Data transformation option.

It requires me to define the `transform` function in vuetable's parent.

But what if the `vuetable` component is placed inside a slot? ESPECIALLY if that slot is provided by another third-party component.

You can see the issue, right? You lose access to the Data transform feature, because it is impossible to define it where vuetable expects it to be.

**Comment by ratiw** [comment]
In v2.0, Data transformation function must be assigned to the `transform` prop because of this.

**Comment by karataev** [comment]
2.5 years later...

Is there any chance for v2.0 to get out of beta?
