### ISSUE TITLE
orderBy Event when apiMode is false

### ISSUE THREAD

**Issue by ZarBoXa** [ratiw/vuetable-2#456]
Hello @ratiw 

Now I set the api-mode to false and I do my own pagination stuff, can you plz emit an event when orderBy function is called ?
`@vuetable:order-by="onOrderByClicked"`

and plz make sure to pass the field and event
`this.$emit('order-by', field, event, this.sortOrder)`

Thanks

**Comment by ratiw** [comment]
@ZarBoXa  Use the `data-manager` prop, see example [here](https://codepen.io/ratiw/project/editor/DzmJnA)

**Comment by ZarBoXa** [comment]
Thanks @ratiw this is really helpful!

**Comment by ZarBoXa** [comment]
Thanks @ratiw this is really helpful!
