### ISSUE TITLE
Fields are not reloaded if they change

### ISSUE THREAD

**Issue by carmilso** [ratiw/vuetable-2#465]
I am trying to modify the field attribute the vue-table is binded to once it has been loaded. So, at first, vue-table loads the field using: `:fields="fields"`. At first, **fields** is an empty array, but I populate it later... Anyway the columns are not updated, so the vue-table loads the field attribute and then it doesn't listen for more changes

**Comment by ratiw** [comment]
@carmilso The `fields` prop will be parsed only once during the initialization of Vuetable. So, if you change anything in `fields` prop later on, you will have to call [`normalizeFields`](https://ratiw.github.io/vuetable-2/#/Vuetable-Methods?id=-normalizefields) function to parse it again.

**Comment by carmilso** [comment]
Great. Thanks!
