### ISSUE TITLE
Getting extra value

### ISSUE THREAD

**Issue by edgarscr** [ratiw/vuetable-2#468]
Hello howdy? i have on my API the Start and End of post  ID like i show u on image.
 
![image](https://user-images.githubusercontent.com/33737821/40854244-d3869c3e-659e-11e8-9d7f-43d6659cc59d.png)

and im trying to display with vuetable like u see on the image. but he dont get value, 

![image](https://user-images.githubusercontent.com/33737821/40854285-e8755e8c-659e-11e8-9568-4573d1eb952d.png)

can u help me how i can get the value?

**Comment by ratiw** [comment]
Looks like it is part of pagination metadata. Unfortunately, what you show me is not enough to identify what's wrong. Any error in the console? More complete code?

**Comment by edgarscr** [comment]
I wanna pick up last and first row on current data example if i display 20 i need to get ID of 0 and 20. 

i search on ur Documents but i dont found that.

**Comment by ratiw** [comment]
@edgarscr I think you're trying to retrieve the data in the wrong place.

`this.from` and `this.to` mean you are trying to refer to the data that you've declared in the `data` section of the component, which do not exist. 

`from` and `to` are in the pagination meta inside the returned data object from the API endpoint. In Vuetable, the data array is stored in the `tableData` variable, and the pagination meta (if available) is stored in the `tablePagination` variable.

Based on the data given, if you declared Vuetable like so,
```html
<vuetable ref="vuetable"
  api-url="..."
  :fields="fields"
  data-path="data"
  pagination-path=""
></vuetable>
```

You could access the `from` and `to` from pagination like this.
```js
nextTicket: function(currentTicketID, next) {
  console.log(currentTicketID + " " + next);
  console.log(this.$refs.vuetable.tablePagination.from + " " + this.$refs.vuetable.tablePagination.to);
}
```

**Comment by edgarscr** [comment]
yes thanks u that helped me.

**Comment by edgarscr** [comment]
Can i add a field specific id? example 

![image](https://user-images.githubusercontent.com/33737821/40888318-7e7fe64c-6723-11e8-8303-afb9c41dfbe1.png)

**Comment by ratiw** [comment]
@edgarscr I'm sorry I really don't know what you wanted to do. You are also mixing `jquery` with Vue. This is not the way to do it. Please go through [Vue Guide](https://vuejs.org/v2/guide/) to learn the basic first. Without this basic understanding, it's impossible to guide you to this.

**Comment by edgarscr** [comment]
I made like i told u on other tickets. i make Vue + Vuetable 2 + Vuetable Modals with Modal next and previous  with ur Vuetable 2 information its working well but when i open a modal i choose and add a class in the row like u see here

![image](https://user-images.githubusercontent.com/33737821/40888468-889723aa-6725-11e8-9302-f38c843b05db.png)

but now when i change with the modal i want to change the class to current selected row.

atm i have like this:
```

                    $('.table-row-class.selected.delete').removeClass('delete')
                    $('.table-row-class.selected').removeClass('selected')

                    if ($('td.ticket_number').text() == response.data.PaginatedTicket.ticket_number) {
                        console.log("Yes")
                        $(this).parent('tr').addClass('selected')
                    } else 
                        console.log("No")  
```

removeClass work well 

but find a row with children value like (response.data.PaginatedTicket.ticket_number) not found nothing

**Comment by edgarscr** [comment]
DONE
```

$(".ticket_number").each(function() {
                        if ($(this).text() == response.data.PaginatedTicket.ticket_number)
                            $(this).parent('tr').addClass('selected')
                    }); 
```
