### ISSUE TITLE
Multiple Tables - Detail Row no longer shows

### ISSUE THREAD

**Issue by adavie1** [ratiw/vuetable-2#477]
I've looked at issue #171 , however, it doesn't quite answer my problem. I have a file-table component (based on vuetable). It works great when only one is on the page.

However, the client wants to see the table split according to workflow, for which files belong to which organisation (_long story, short version: each organisation uploads a predefined set of files in each step of the workflow_). 

See below:
![image](https://user-images.githubusercontent.com/3030402/41604723-80420f40-7412-11e8-8993-29e39b2f8fb7.png)

The URLs are different for each table. I've also given each different `refs` as well. Each detail component also has it's own unique `ref`.

Despite this, the detail row no longer shows. In single table mode- clicking on the uploaded file (in green) will show a file preview and and approval workflow.

Using vue-dev-tools, I can see the `vuetable:detail-row-clicked` event being emitted for each table.

I suspect the issue is that the event name is the same for both components, which is why the detail row doesn't appear when two vue-tables are on the same page.

What I've also noticed, is that the click event is generated by clicking anywhere in the table component, event the Category button (which is a separate component) or on the download button, which should download the file. Even the pagination component doesn't work now.
**FileTable.vue**
```
<template>
<div>
    <data-table
      :url="url"
      :table-ref="uniqueTableRef"
      :fields="fields"
     ...
      detail-component="file-detail-row">
               ....
    </data-table>
  </div>
</template>

<script>
 ....

export default {
  ...
  props: {
    ...
    tableRef: {
      type: String,
      default: 'filestable'
    }
  },

  computed: {
    uniqueTableRef: function () {
       ...   // confirmed unque ref per table instance
    },
  ...
}

</script>
```

The code below is the skeleton of **data-table** component that wraps vue-table.
```
<template>
     ....
    <vuetable
    :ref="this.tableRef"
    :name="this.tableRef"
    @vuetable:checkbox-toggled="onCheckedItem($event)"
    ...
   >
   ...
  </vuetable>
...
</div>
</template>

<script>
...
  props: {
   ...
    tableRef: {
      type: String,
      default: 'vuetable'
    },
    detailComponent: {
      type: String
    },

   ... 

  },
...
  methods: {
    getTableRef () {
      return this.tableRef
    },

    onCellClicked (data, field, event) {
      let table = this.$refs[this.tableRef]

      table.toggleDetailRow(data.id)

      if (table.isVisibleDetailRow(data.id)) {
        this.opened.push(data.id)
      } else {
        let position = this.opened.indexOf(data.id)

        if (~position) {
          this.opened.splice(position, 1)
        }
      }

    },

    isDetailOpen (id) {
      let position = this.opened.indexOf(id)

      if (~position) {
        return true
      } else {
        return false
      }

    },
 ....
}
</script>
```

**Comment by ratiw** [comment]
@adavie1 I think, something is not right here.

- I've seen no `vuetable:detail-row-clicked` event registration in the code, e.g.
  ```html
  <vuetable 
    //...
    @vuetable:detail-row-clicked="..."
  ></vuetable>
  ```

- You import VuetablePagination and VuetablePaginationInfo, but globally register other ones (but from the same source), then again locally register the ones you've imported. This is unnecessary and duplicated.

Those are what I've spotted at a glance, but the code is rather long and it's hard for me to go into detail. If possible, please create a [codesandbox](https://codesandbox.io) project to demonstrate your problem. It would also be easier for me to look into that as well.

**Comment by adavie1** [comment]
@ratiw - thanks for the feedback. Yes, the code is rather long. i coped an early demo for the data-table component. I'll look into your suggestions.

As to the detail row- that's passed as a parameter to data-table.

I'm using this to open the detail view:
```
...
   onCellClicked (data, field, event) {
      this.$refs[this.tableRef].toggleDetailRow(data.id)
    },
...
```
Like I said, this is based on the tutorial from about year ago. Your event registration might solve the problem. Let me try that.

**Comment by adavie1** [comment]
I've reduced the code to the bare bones. I can use my data-table component more than once on pages- but they are very different URLs and refs.

In relation to  ` @vuetable:detail-row-clicked` I am using `@vuetable:cell-clicked` like I said this was based on an example from about a year ago. It definately needs some refactoring.

As to pagination, yeah, removed the global ones. I was learning vue at the time, never went back to lean up code like this. Thanks for the reminder.

Just in this case, I want two tables that are almost the same data. The URLs and refs are different for each table.

I've also experimented with giving each table an ID value. Still no joy.

**Comment by ratiw** [comment]
@adavie1 Sorry to hear that, but I can't really figuring out the problem based on your description.
If you can create a project in [CodeSandbox](https://codesandbox.io) to demonstrate the problem, I can have a look at it.

**Comment by adavie1** [comment]
@ratiw figured it out. It's an elements-ui thing. For some reason if you don't have `<el-row>` followed `<el-col>` it ignores events from inside `<el-col>` without an `<el-row>` parent. This is a new "feature" previous code worked fine.

Sorry for the false alarm.
