### ISSUE TITLE
Move thead to the table together with tbody

### ISSUE THREAD

**Issue by wesley-firewalla** [ratiw/vuetable-2#478]
We need make sure the th has the same width as the td, so need to move the thead into the same table as tbody it is in.

**Comment by ratiw** [comment]
@wenbinke That's why you need to set `width` option in field definition object. If you set `tableHeight` without setting the `width` option, it will not work.  Please explain in more detail if this is not what you mean.

**Comment by wenbinke** [comment]
I don’t think it is a good design that you separated the table into different parts. And the vuetable is buggy, I am not going to suggest anything.

**Comment by ratiw** [comment]
I never claim that it is a good design. It is something that I build for myself and share to the others. If you don't like it, that's fine by me. No hard feeling at all. Life moves on.
