### ISSUE TITLE
Custom component header click handler not getting event

### ISSUE THREAD

**Issue by martixy** [ratiw/vuetable-2#482]
I wonder - what exactly is going on here:
https://github.com/ratiw/vuetable-2/blob/next/src/components/VuetableRowHeader.vue#L14

Compare to [this](https://github.com/ratiw/vuetable-2/blob/next/src/components/VuetableRowHeader.vue#L22)

I noticed this the other day and wondered when it might bite me in the butt, and today it did when I tried to enable multi-sort. The multi-sort function attempts to acquire the multi-sort key from the event, but is not something ever passed to the event handler in the case of a custom component.

The fix I believe would be rather simple:
`@click="onColumnHeaderClicked"` - let vue unpack any arguments for you
Then in your custom component you just gotta `@click="$emit('click', rowField, $event)"`

**Comment by ratiw** [comment]
@martixy The [L14](https://github.com/ratiw/vuetable-2/blob/next/src/components/VuetableRowHeader.vue#L14) is definitely incorrect. Sorry about that.

Thanks for the tip, it is useful. But I would prefer this to be explicit as it is easier to catch the bugs I've made. :)
