### ISSUE TITLE
selectedTo array contains duplicates after sort

### ISSUE THREAD

**Issue by martixy** [ratiw/vuetable-2#483]
I was doing some sorting (in data mode if relevant) and noticed that the selectedTo array on the table(which contains the indices of the selected data entries) is not properly cleared and contains a duplicate of all selections for each sort operation.

**Comment by ratiw** [comment]
@martixy Is this the same as in #481? If not, can you please fork [this codesandbox](https://codesandbox.io/s/oq9jj7l189) and demonstrate the problem so that I have more understanding on this?
