### ISSUE TITLE
Passing extra value 

### ISSUE THREAD

**Issue by edgarscr** [ratiw/vuetable-2#486]
Hello howdy? i want to add extra value from API to display on tables 

**OLD API**
{"car_number":"HU-ML 99"}
table row old setup: 
name: HU-ML 99

**NEW API**
{"car_number":"HU-ML 99"**,"license_total":"2"**}

table with new setup: 
name: HU-ML 99 **license_total**

i want to integrate the licence_total with car_number

but i dont know how to add with callback or smth? i search and not found nothing on ur documentation

**Comment by ratiw** [comment]
@edgarscr For v1.7.x, use either `__slot` or `__component` special field. For v2.0, use Field Slot or Field Component instead. Please go through the tutorial and documentation carefully, they are all there.
