### ISSUE TITLE
Possible to have a custom header for special fields?

### ISSUE THREAD

**Issue by zxc23** [ratiw/vuetable-2#488]
I have a special fields slot (https://github.com/ratiw/vuetable-2/wiki/Special-Fields#-__slotname) for actions in my table, and I wanted to customise the header for that one column by adding my own components. Is it possible to achieve this in vuetable-2 currently?

I've seen that in more recent versions it is possible to have a fully custom table header, but I'd like to keep the headers for all the other columns as they are, and alter only my special field's header.

**Comment by ratiw** [comment]
@zxc23 You can do this in v2.0 (currently in beta) of Vuetable-2. For this particular column, you just have to create Field Component, then you'll have total control over the header of the column. The rest of the columns can be Field Slot, which is not that different than the `__slot` special field. The only different is that you don't need to prefix those columns with `__slot:` anymore.

Please see [this](www.vuetable.com/guide/special-field.html) for more detail.

**Comment by zxc23** [comment]
Thank you. I will try updating and see how I go.

Edit: Fixed url above http://www.vuetable.com/guide/special-field.html

**Comment by zxc23** [comment]
It works well, thank you. I'm having more difficulty with other things breaking due to updating from 1.6.5 -> next but this may be something for a separate issue.

**Comment by ratiw** [comment]
Let me know and maybe I can help on those transitions.
