### ISSUE TITLE
this.$refs.pagination is undefined

### ISSUE THREAD

**Issue by shaprk** [ratiw/vuetable-2#490]
Hi, thanks for your great work.
But I have a problem in pagination. When I try to use render function following lesson 17 in tutorials, I face this error in browser : 

*TypeError: "this.$refs.pagination is undefined"*

When I took a look at [Vue API doc](https://vuejs.org/v2/api/#ref) I found this: 
> An important note about the ref registration timing: because the refs themselves are created as a result of the render function, **you cannot access them on the initial render - they don’t exist yet**! $refs is also non-reactive, therefore you should not attempt to use it in templates for data-binding.

I think that's the problem for me too. What should I do ?

**Comment by ratiw** [comment]
@MrProgramador Are you using v1.7 or v2.0 of Vuetable-2 when following the tutorial?

**Comment by shaprk** [comment]
@ratiw I used v2.0
I was trying not to use props and it didn't work, but when using props it worked.
However I wonder why it is possible to use $refs in render function while Vue Doc says you can't !

**Comment by ratiw** [comment]
@MrProgramador It actually does not say that you cannot use it in the render function. You just cannot use it "on the initial render". After the initial render, you can use it because Vue already make after that point.

**Comment by shaprk** [comment]
Thanks
