### ISSUE TITLE
Sortby and orderby parameters

### ISSUE THREAD

**Issue by sylvaincaillot** [ratiw/vuetable-2#491]
Hi, 
Using vuetable-2 v2, I am trying to use the sort parameters as my API endpoint does not accept to receive both the sorting order and the field into a single parameter:

This is where I am so far:

```
        <vuetable ref="vuetable"
            api-url="http://localhost:..."
            :query-params="{ sort: 'orderBy', page: 'page', perPage: 'limit' }"
            :fields="fields"
            :sort-order="sortOrder"
            :sort-params="getSortParam"
            data-path="data"
            pagination-path="count">
        </vuetable>

sortOrder: [
                {
                field: "departure",
                direction: "asc"
                }
            ],

getSortParam(sortOrder) {            
            return sortOrder[0].sortField+"&sorting="+sortOrder[0].direction
        },
```

And it keeps returning
?orderBy=departure%26sorting%3Dasc&page=1&limit=10
while I would expect:
?orderBy=departure&sorting=asc&page=1&limit=10

What am I doing wrong?
Is there a way to directly define the sort and field parameters in the query-params? 

Thnak you for your help

S.

**Comment by ratiw** [comment]
@sylvaincaillot `sort-params` is intended to be used to override `sort` key only. In your case, you'll have to use `query-params` function as demonstrated [here](http://www.vuetable.com/guide/sorting.html#overriding-default-query-string) (the last example) instead. 

If you're still having problem, please let me know.

**Comment by sylvaincaillot** [comment]
Thank you very much, this is exactly what I needed.
