### ISSUE TITLE
Reloading table data with action buttons

### ISSUE THREAD

**Issue by shaprk** [ratiw/vuetable-2#492]
Hi,
Following tutorial 17, I made some action buttons in my table such as delete button.
Now when I use it to delete a row, after deletion, I want table to reload, because if it had 10 results per page, after deletion it has 9 rows.
How can I do that?

**Comment by ratiw** [comment]
You can use the [`reload`](http://www.vuetable.com/api/vuetable/methods.html#reload) function for that purpose.

**Comment by shaprk** [comment]
How to use it in a method in App.vue component?

**Comment by ratiw** [comment]
Usually when you use special `ref` attribute to declare a reference point like so,

```html
<vuetable ref="vuetable"
  //...
></vuetable>
```

Then, you can reference it in your javascript script via `$refs` at the point relevant in your code logic.
You may or may not have to wrap it inside `nextTick` function depending on the logic in your code.

```js
  // after remove the item from the array
  this.$refs.vuetable.reload()
```

**Comment by shaprk** [comment]
Is it necessary to do it on a App.vue component?
I mean I wanted to use some blade file capabilities, so I did not use any app.vue file.
I used my components in blade files directly and my delete method is defined in app.js in Vue instance itself
```
const app = new Vue({
    el: '#app',
    methods: {
        myDeleteMethod: function () {
            //  some codes
            this.$refs.vuetable.reload()
        },
    }
})
```

but I get this error when running the method :
TypeError: this.$refs.vuetable is undefined

**Comment by ratiw** [comment]
I think you misunderstand some points. You cannot mix the front-end and back-end together. You rather make the front-end "works with" the back-end. 

Laravel Blade is in the back-end side. Vue is on the front-end side. 

So the question "is it necessary to do it on the App.vue component?" is not really correct. The `this.$refs.vuetable.reload()` call is supposed to be where you can "reference" `this.$refs.vuetable` and it should be in the component that define `<vuetable ref="vuetable">`. `$refs` is not global, but rather an instance or component scope. 

The given code is not enough for me to understand how you use Vuetable. I can only see that `myDeleteMethod` is in main Vue instance, but I don't see how your define `<vuetable>`. In this case, `this` will refer to main Vue instance and if you do not define `<vuetable>` here, it will not be able to find `$refs.vuetable`, hence it is `undefined`.

**Comment by shaprk** [comment]
This is my VueTable component:
```
<script>

    import Vuetable from 'vuetable-2/src/components/Vuetable'
    import CssConfig from './configs/VuetableCssConfig'
    import VuetablePagination from 'vuetable-2/src/components/VuetablePagination'

    export default {
        name: "VueTable",
        components: {
            Vuetable,
            CssConfig,
            VuetablePagination,
        },
        props: {
            ApiUrl: {
                type: String,
                required: true,
            },
            fields: {
                type: Array,
                required: true,
            },
        },
        data() {
            return {
                css: CssConfig
            }
        },
        methods: {
            renderVuetable(h) {
                return h(
                    'vuetable',
                    {
                        ref: 'vuetable',
                        props: {
                            apiUrl: this.ApiUrl,
                            fields: this.fields,
                            css: this.css.table,
                            paginationPath: '',
                        },
                        on: {
                            'vuetable:pagination-data': this.onPaginationData,
                        },
                        scopedSlots: this.$vnode.data.scopedSlots
                    },
                )

            },
            renderPagination(h) {
                return h(
                    'vuetable-pagination',
                    {
                        ref: 'pagination',
                        props: {
                            css: this.css.pagination,
                        },
                        on: {
                            'vuetable-pagination:change-page': this.onChangePage,
                        }
                    }
                )
            },
            onPaginationData(paginationData) {
                this.$refs.pagination.setPaginationData(paginationData)
            },
            onChangePage(page) {
                this.$refs.vuetable.changePage(page)
            },
        },
        render (h) {
            return h(
                'div',
                {
                    class: 'table-container',
                },
                [
                    this.renderVuetable(h),
                    this.renderPagination(h),
                ]
            )
        },
    }
</script>
```
and here is my page.blad.php file:
```
@section('content')

  <vue-table api-url="/api/articles/queue"
             :fields="[
              { name: 'title', title: 'Title' },
              { name: 'user.name', title: 'Author' },
              { name: 'created_at', title: 'Date' },
              { name: '__slot:actions', title: 'Manage' },
             ]"
  >
    <template slot="actions" slot-scope="props">
      <div class="table__actions">
        <a :href=`/articles/${props.rowData.slug}` class="table__icon" target="_blank">
          <i class="fa fa-search"></i>
        </a>
        <a :href=`/articles/${props.rowData.slug}/edit` class="table__icon">
          <i class="fa fa-edit"></i>
        </a>
        <a class="table__icon" @click="myDeleteMethod()">
          <i class="fa fa-trash"></i>
        </a>
      </div>
    </template>
  </vue-table>

@endsection
```
I understand what you say but I don't know what to do

**Comment by ratiw** [comment]
Hmm, I didn't think that you're using render function. At that time when I made the tutorial, I can't use `$scopeSlots` inside the template. Vue has changed and it is now allow.

Maybe you can add a method (that will be represented as a computed prop) in your `VueTable` component that would reference to the internal Vuetable.

```js
  //.. after onChangePage(page)
  vuetable() {
    this.$refs.vuetable
  }
```

and this to your blade
```html
@section('content')
    <vue-table api-url="/api/articles/queue"
             ref="myVueTable"
             :fields="[
              { name: 'title', title: 'Title' },
              { name: 'user.name', title: 'Author' },
              { name: 'created_at', title: 'Date' },
              { name: '__slot:actions', title: 'Manage' },
             ]"
    >
    //...
  >@endsection
```

Then, you should be able to do this
```js
  this.$refs.myVueTable.vuetable.reload()
```

It's a bit messy, but this is what I have off the top of my head at the moment.

**Comment by shaprk** [comment]
It doesn't work
TypeError: this.$refs.myVueTable.vuetable.reload is not a function

If I get a console.log(this.$refs.myVueTable.vuetable) It retruns :
function vuetable()

But your suggestion does not work.
Would you please show me a complete way?
I can change my whole code if needed.

**Comment by ratiw** [comment]
Have you tried this?
```js
  this.$refs.myVueTable.vuetable().reload()
```

**Comment by shaprk** [comment]
Error :
_TypeError: this.$refs.myVueTable.vuetable(...) is undefined_

**Comment by shaprk** [comment]
It worked !
```
vuetable() {
    this.$refs.vuetable
  }
```
It needed a return :
```
return this.$refs.vuetable
```

**Comment by shaprk** [comment]
Thank you very much @ratiw 
you helped me a lot today.

**Comment by ratiw** [comment]
Yep, always forgot the `return`. Sorry, my bad. Glad you've figured it out. :)

**Comment by goarun112** [comment]
`this.$refs.vuetable.refresh()` is not working for me I'm using graphql endpoint to the data table.how to `reload()` or `refresh()` the data table
