### ISSUE TITLE
Bootstrap 4 Pagination

### ISSUE THREAD

**Issue by warlord0** [ratiw/vuetable-2#502]
Thanks for what looks to be a great vuetable. I've tried a few and run into several jQuery/Bootstrap 3 issues. This one seems pretty tight and fits my Laravel 5.5 needs.

I wasn't sure on a PR for this, but I built a paginator for Bootstrap 4 that uses fontawesome (free). I thought others might like the code.

It includes first, prev, sliding window, next and last.

```vue
<template>
  <nav aria-label="Table Navigation">
    <ul class="pagination">

      <li
        :class="{'disabled': isOnFirstPage}"
        class="page-item">
        <a
          class="page-link"
          href="#"
          @click.prevent="loadPage(1)">
          <span><i class="fas fa-angle-double-left"/></span>
        </a>
      </li>

      <li
        :class="{'disabled': isOnFirstPage}"
        class="page-item">
        <a
          class="page-link"
          href="#"
          @click.prevent="loadPage('prev')">
          <span><i class="fas fa-angle-left"/></span>
        </a>
      </li>

      <template v-if="notEnoughPages">
        <li
          v-for="n in totalPage"
          :key="n"
          :class="{'active': isCurrentPage(n)}"
          class="page-item"
        >
          <a
            class="page-link"
            @click.prevent="loadPage(n)"
            v-html="n"/>
        </li>
      </template>
      <template v-else>
        <li
          v-for="n in windowSize"
          :key="n"
          :class="{'active': isCurrentPage(windowStart+n-1)}"
          class="page-item"
        >
          <a
            class="page-link"
            @click.prevent="loadPage(windowStart+n-1)"
            v-html="windowStart+n-1"/>
        </li>
      </template>

      <li
        :class="{'disabled': isOnLastPage}"
        class="page-item"
      >
        <a
          class="page-link"
          href=""
          @click.prevent="loadPage('next')">
          <span><i class="fas fa-angle-right"/></span>
        </a>
      </li>

      <li
        :class="{'disabled': isOnLastPage}"
        class="page-item"
      >
        <a
          class="page-link"
          href=""
          @click.prevent="loadPage(totalPage)">
          <span><i class="fas fa-angle-double-right"/></span>
        </a>
      </li>

    </ul>
  </nav>
</template>

<script>
import { VuetablePaginationMixin } from 'vuetable-2'
export default {
  mixins: [VuetablePaginationMixin]
}
</script>
```

**Comment by warlord0** [comment]
... and as a Dropdown for Bootstrap 4.

Include first, prev, dropdown, next and last.

## VuetablePaginationDropdownBootstrap.vue

```vue
<template>
  <nav aria-label="Table Navigation">
    <ul class="pagination">

      <li
        :class="{'disabled': isOnFirstPage}"
        class="page-item">
        <a
          class="page-link"
          href="#"
          @click.prevent="loadPage(1)">
          <span><i class="fas fa-angle-double-left"/></span>
        </a>
      </li>

      <li
        :class="{'disabled': isOnFirstPage}"
        class="page-item">
        <a
          class="page-link"
          href="#"
          @click.prevent="loadPage('prev')">
          <span><i class="fas fa-angle-left"/></span>
        </a>
      </li>

      <div class="form-group mr-1 ml-1">
        <select
          id="paginationDropdown"
          class="form-control"
          @change="loadPage($event.target.selectedIndex+1)"
        >
          <template
            v-for="k in totalPage"
          >
            <option
              :key="k"
              :value="k"
              :selected="isCurrentPage(k)"
            >
              Page {{ k }}
            </option>
          </template>
        </select>
      </div>

      <li
        :class="{'disabled': isOnLastPage}"
        class="page-item"
      >
        <a
          class="page-link"
          href=""
          @click.prevent="loadPage('next')">
          <span><i class="fas fa-angle-right"/></span>
        </a>
      </li>

      <li
        :class="{'disabled': isOnLastPage}"
        class="page-item"
      >
        <a
          class="page-link"
          href=""
          @click.prevent="loadPage(totalPage)">
          <span><i class="fas fa-angle-double-right"/></span>
        </a>
      </li>

    </ul>
  </nav>

</template>
<script>
import { VuetablePaginationMixin } from 'vuetable-2'
export default {
  mixins: [VuetablePaginationMixin]
}
</script>
```

**Comment by ratiw** [comment]
Thanks a lot @warlord0. If you could create a npm package for it, it would be more convenient for other people to pull your work in via `npm install`. You could also make a gist showing your code and I'll make a link in the documentation to your work to give you a proper credit for your work. :)

**Comment by warlord0** [comment]
You kind of read my mind. But I'm not really confident enough in pushing things into a proper npm package right now.

I'm not requiring any credit. Your work is far more worthy than my scratchings.

I have documented a few things including JWTAuth on my own blog here: https://warlord0blog.wordpress.com/2018/07/26/vuetable-2/

**Comment by warlord0** [comment]
@ratiw I'm working on getting this into a package - now I know how :) But I wonder if you could advise on something.

I've created a vue component containing many of your components, pagination etc. and from my parent component I am passing in enough details to standardise the table I want returned. eg.

```html
    <vuetable-base
      :sort-order="sortOrder"
      :fields-def="fields"
      :per-page="15"
      api-url="/admin/users"
    />
```

It works jsut great until I run into wanting to use slots in the fieldsDef.

In the child component for vuetable I don't know how to pass a template for the slots in for fieldDefs. Can you help?

I tried using `:slotTemplate="slotTemplate"`

where I put slotTemplate in my data as:

```javascript
      slotTemplate: `
        <template
          slot="roles"
          slot-scope="props"
        >
          <!-- Iterate the roles and build the buttons -->
          <button
            v-for="role in props.rowData.roles"
            :key="role.name"
            class="btn btn-sm btn-primary mr-1 mb-1"
          >
            {{ role.name }}<!--&nbsp;<i class="fas fa-times"/>-->
          </button>
          <!-- add role button fires the modal -->
          <button
            class="btn btn-sm btn-default text-dark mr-1 mb-1"
            @click="addRoles(props.rowData)"
          >
            <i class="fas fa-pencil-alt"/>
          </button>
        </template>
        `
```

Which gets it as far as into the component as a prop.

But I'm not sure that's the way to go and not sure how to pass the slotTemplate into the vuetable component. to handle the slots.

Could you give me any pointers?

**Comment by ratiw** [comment]
Are you using v1.7.x or v2.0-beta?

**Comment by warlord0** [comment]
v1.7.5 according to my dependencies.

How stable is the beta?

Edit: Ahh, I see a VuetableFieldMixin that looks like what you're pointing to in v2.0.

**Comment by ratiw** [comment]
v2.0-beta is quite stable, except for a few bug that shouldn't affect your case. Even though there are some breaking changes, I try to keep it very minimal. Please see [this release note](https://github.com/ratiw/vuetable-2/releases/tag/v2.0.0-beta.1) for more detail. The document has also been revised and you can see it at [`vuetable.com`](https://vuetable.com). If you get stuck on anything, please let me know.

**Comment by warlord0** [comment]
This worked out really well. I got around to adding v2.0 beta and added the mixin for my columns.

The example [here](https://codesandbox.io/s/7zkrn4lvz0?module=%2Fsrc%2Fcomponents%2FVuetableFieldSwitch.vue&moduleview=1&view=editor) doesn't seem to work but I was able to take enough from it to create the necessary working code.

Thanks for a great component.
