### ISSUE TITLE
Add sort event to Vuetable component

### ISSUE THREAD

**Issue by cioraneanu** [ratiw/vuetable-2#503]
I've looked through the documentation but didn't find any event that is trigger when the sorting changes. Is there a reason for this?

I'm handling the server requests myself (apiMode=false, and using :data prop) so I need to perform a new GET request when sorting changes.

Thank you.

**Comment by ratiw** [comment]
@cioraneanu You need to provide the "data manager" to handle that. See example for v1.7 [here](https://codesandbox.io/s/239v6w2vkp) and example for v2.0-beta [here](https://codesandbox.io/s/y0z80ooxk9) and an explanation [here](http://www.vuetable.com/guide/api-vs-data-mode.html#data-mode).

**Comment by cioraneanu** [comment]
@ratiw Oh I see. Apparently I was looking at the wrong docs (https://ratiw.github.io/vuetable-2/#/). The data manager will handle my needs 👍 

Thank you for your response. WIll close this issue.
