### ISSUE TITLE
Column callback does not return expected output

### ISSUE THREAD

**Issue by IvoPereira** [ratiw/vuetable-2#506]
Hello,

I have been integrating vuetable-2 successfully into my project. However, I was not able to get column callback to work.

I've reproduced the issue in a very basic example in the following snippet:
https://codesandbox.io/s/131m9o1o04

The majority of the example was rewritten from here:
https://github.com/ratiw/vuetable-2-tutorial/blob/lesson-6/src/components/MyVuetable.vue

The issue is identical to what happens in my project.

Am I missing something or is this a bug?

Thanks

**Comment by ratiw** [comment]
@IvoPereira The tutorial is for Vuetable-2 v1.7.x, but in the given codesandbox you're using v2.0.0-beta.1, which has renamed `callback` option to `formatter`.

Please see the v2.0-beta release note [here](https://github.com/ratiw/vuetable-2/releases/tag/v2.0.0-beta.1) and the official documentation for v2.0-beta is [here](https://vuetable.com)

I still don't have time to update the tutorial to v2.0, sorry for the confusion.

**Comment by IvoPereira** [comment]
Ah, I see, thanks a lot @ratiw.

Yeah, there are some versions of the repos and guides and that makes some confusion but clarified now 👍 

Just for reference for anyone that stumbles into this issue, this should be used instead:

```js
let fields = [
  {
    name: 'gender',
    sortField: 'gender',
    titleClass: 'center aligned',
    dataClass: 'center aligned',
    formatter (value) {
      return value === 'M' ? 'Male' : 'Female'
    }
  },
]
```

More in https://www.vuetable.com/guide/fields-definition.html#field-options

Thanks!
