### ISSUE TITLE
How to know if the detail row was open or closed 

### ISSUE THREAD

**Issue by chaymag** [ratiw/vuetable-2#508]
Hi, I need to show an alert when the user opens the detailrow i tried adding the code in the onCellClicked method , it works but the alert is also displayed when the user closes the detailrow , how can I fix this?

**Comment by ratiw** [comment]
@chaymag More info [here](http://www.vuetable.com/guide/detail-row.html#how-vuetable-track-the-state-of-each-detail-row).
