### ISSUE TITLE
Custom field click events

### ISSUE THREAD

**Issue by mszkb** [ratiw/vuetable-2#518]
Is it possible to make a custom click event for fields?

For example: I want to place a checkbox before each title field, like this

```
fields: [
 {
  name: 'myField',
  title: '<input type="checkbox" id="myField" /><label for="myField">myField</label>'
 }
]
```
When I click the checkbox/label a custom event should fire.
@click doesnt work, and the callback property is executed immidiatly.

**Comment by ratiw** [comment]
You need to write a component using `__component` special field (v1.7.x) or Field Component (v2.0). The `title` option normally is for displaying column title (text) only.

**Comment by mszkb** [comment]
Ok, I guessed so. I hoped i could avoid that.

Thank you, ill share the solution to my particular problem next week.
