### ISSUE TITLE
Hide header?

### ISSUE THREAD

**Issue by ghost** [ratiw/vuetable-2#523]
Would you tell me that how to hidden <th> tag?
I'd like to hidden <th> tag.

one example:

```
<table class="vuetable ui blue selectable unstackable celled table fixed">
    <colgroup>
        <col class="vuetable-col-read">
        <col class="vuetable-col-created_at">
        <col class="vuetable-col-inquire_title">
        <col class="vuetable-col-actions">
    </colgroup>
    <thead>
        <tr style="visibility:collapse">   <!--  <- one example!     -->
            <th id="_read" class="vuetable-th-read"></th>
            <th id="_created_at" class="vuetable-th-created_at"></th>
            <th id="_inquire_title" class="vuetable-th-inquire_title"></th>
            <th class="vuetable-th-slot-actions"></th>
        </tr>
    </thead>
    <tfoot></tfoot>
    <tbody class="vuetable-body">
        <tr item-index="0" class="">
            <td class="vuetable-td-read"></td>
            <td class="vuetable-td-created_at">2018/08/23</td>
            <td class="vuetable-td-inquire_title">ccc_title25</td>
            <td class="vuetable-slot"><img src="/_nuxt/img/arrow.8466214.png" alt=""></td>
        </tr>
    </tbody>
</table>
```

Thanks.

**Comment by ratiw** [comment]
@kazumi-kondo-forgevision I'm not sure if you really want to hide tag or hide the row. But if you want to hide one or more row from being displayed. You can just remove that row from the `tableData` variable. If not, please explain more.

**Comment by ghost** [comment]
@ratiw I'd like to hide `<tr>` tag. not `<td>`. But `:fields=null` is not allowed.
Now, I've used `overflow: hidden;` on css. It's working well.
Do you have correct way? If you don't have it, I'll close this issue.
Thank you.

**Comment by ratiw** [comment]
Hmm, I don't quite understand your use case why you want to hide `<tr>`. But if I were you, I would remove those "rows" from `tableData` (and put it in another array if I want to put it back in)

Basically, Vuetable will display every row in its `tableData` variable. If you do not want it to be displayed, just remove it from that variable. You can reference `tableData` via `ref` attribute, like so `this.$refs.vuetable.tableData`.

**Comment by ghost** [comment]
I'd like to create below table.
(the red mark is unread mark.)
![list](https://user-images.githubusercontent.com/19407719/45527569-5b47f080-b817-11e8-84b2-c73b4fe91266.PNG)

I know `this.$refs.vuetable.tableData` is `<td>` data but not `<tr>` data. Isn't it?

Now, I write below code. This is `fields` data.
I'd like to hide header title so to set the title is null.

```
export default [
  {
    name: 'inquire_id',
    visible: false
  },
  {
    name: 'read',
    title: '',
    formatter (value) {
      if(!value) {
        return '<span class="icon-latest"></span>'; //unread mark.
      }
    },
  },
  {
    name: 'created_at',
    title: '',
    formatter (value) {
      if(value) {
        return moment(value).format("YYYY/MM/DD");
      }
    },
  },
  {
    name: 'inquire_title',
    title: ''
  }
]
```

My issue is not important...
Thank you for using your time.

**Comment by ratiw** [comment]
`tableData` is an array containing all the rows of data currently displaying. So, it is the `<tr>`, which contains all `<td>`.

**Comment by ghost** [comment]
Wops! It's my mistake! I was really confused.
I'd like to hide `<thead>` tag.
My solution is `title: ''`.

Thanks!
