### ISSUE TITLE
Accessing values from other columns

### ISSUE THREAD

**Issue by khalwat** [ratiw/vuetable-2#524]
First of all, thank you @ratiw -- I love the way you've architected Vuetable-2, and appreciate all of your hard work.

I have a use-case where I'd like to be able to access values from other columns in a given row inside of the callback that I define in the field defs.

I want to be able to link a text field to a URL based on data in another column in the row, but it doesn't appear there's any way to do this via the callback; something like id = row['id'];

I also looked into __component: but that too appears to only pass in the data for the current column.

How might this be accomplished? I'm using Vuetable-2 1.7.x

Looking into this to see if it applies... https://github.com/ratiw/vuetable-2/issues/507

**Comment by ratiw** [comment]
@khalwat `__component` and `__slot` do get the whole row data, not just the column data. That means you can use them to solve your problem. The reason that the `callback` (renamed to `formatter` in v2.0) receives only the column value because it was meant to be used for formatting only.

**Comment by khalwat** [comment]
Roger that. I ended up doing it a bit of a kludgey way, by passing down `data|data` in a field and splitting them in the `callback`

Using my own `__component` makes sense, I'll give that a go when I refactor things.

I absolutely _love_ Vuetable-2 -- thank you for this awesome package!
