### ISSUE TITLE
Is there an easier way to populate fields data 

### ISSUE THREAD

**Issue by zcwilt** [ratiw/vuetable-2#527]
Info: 
Using v2 beta 3
Using api-mode=true

I have an api endpoint that can return table data and field data in a single call. However cannot work out a way to extract the field data to be used. Currently have to do 2 api calls.
e.g.
Automatic call to get data and a second call (using code like #149 )
Is there a simpler way. ???

I had thought about using automatic ``transform`` and extracting the fields during the ``transfrom`` code, but that seems hacky.

Thanks for the great project btw. The new v2 code has opened up a lot of possibilities for me.

**Comment by ratiw** [comment]
@zcwilt The only way possible right now is to use `transform` function, but this will has side effect as `transform` function was meant to be used to transform the data page by page, e.g. 10 rows per page of total 100 records is 10 pages. 

Including the field definition in the same payload will likely cause you to reparse it 9 more times than it needs to be. So, I would stick with 1 call for getting the field definition and the rest will be handle by Vuetable.

**Comment by zcwilt** [comment]
OK. Will stick with what I have at the moment, Thanks
