### ISSUE TITLE
New Field Component - best way to access cell value

### ISSUE THREAD

**Issue by zcwilt** [ratiw/vuetable-2#529]
My vuetable is composed of custom components for every column.
It's something I am working on to replace a jquery datatablles implementation.

As an example I have a component called __boolean-index
This is meant to take a laravel model boolean field and render it with icons rather than 0 or 1

the SFC looks like

    <template>
        <th v-if="isHeader">{{title}}</th>
        <td v-else><i :class="boolClass"></i></td>
    </template>

    <script>
        import VuetableFieldMixin from 'vuetable-2/src/components/VuetableFieldMixin.vue'

        export default {
            mixins: [VuetableFieldMixin],

            computed: {
                boolClass: function () {
                    var current = this.vuetable.tableData[this.rowIndex][this.rowField['modelField']]
                    var classOn = (this.rowField['extra']['classOn']) ? this.rowField['extra']['classOn'] : 'fa fa-check'
                    var classOff = (this.rowField['extra']['classOff']) ? this.rowField['extra']['classOff'] : 'fa fa-times'
                    var faclass = (current) ? classOn : classOff
                    return faclass
                }
            }
        }

    </script>

my question regards this line 

    var current = this.vuetable.tableData[this.rowIndex][this.rowField['modelField']]

is there a better way to get the current cell value.

apologies if code is poor. I'm a definite Vue noob.

**Comment by ratiw** [comment]
@zcwilt Other than `rowIndex` and `rowField`, Field Component also get `rowData` which is the actual row data it is processing. So, you should be able to simplify `this.vuetable.tableData[this.rowIndex]` to just `this.rowData`.

**Comment by zcwilt** [comment]
Thanks @ratiw  definitely makes it more readable.
