### ISSUE TITLE
Filterbar pass placeholder var

### ISSUE THREAD

**Issue by marekkaczkowski** [ratiw/vuetable-2#53]
Hey Rati,

I added
`<filter-bar placeholder="Search for brick">` to show correct tip in filter input. It also would be nice to add 'unit' var to `<vuetable-pagination-info units="bricks">` so it will show _Displaying 0 to 0 of 1352 bricks_
I can send you a pull req.

**Comment by ratiw** [comment]
@marekkaczkowski You can actually do that via `info-template` prop.

```html
  <vuetable-pagination-info
    info-template="Displaying {from} to {to} of {total} bricks"
  ></vuetable-pagination-info>
```

**Comment by marekkaczkowski** [comment]
Ah I missed that. :ok_hand:

Thank you for your time Rati!

**Comment by marekkaczkowski** [comment]
Ah I missed that :ok_hand:

Thank you for your comment Rati!
