### ISSUE TITLE
Cache current page, sort order and filter text

### ISSUE THREAD

**Issue by roelVerdonschot** [ratiw/vuetable-2#556]
I would like to navigate to and from the table and keep all filters (current page, sort order and filter text) so user don't have to reenter them, is this possible?

and if not, I can manually cache everything but how can I set the current page?

**Comment by roelVerdonschot** [comment]
Didn't find anything in the docs so ill implement this manually

**Comment by kushan2** [comment]
How did you do this? any clue?
