### ISSUE TITLE
Sorting with custom field component?

### ISSUE THREAD

**Issue by halws** [ratiw/vuetable-2#557]
Hello, firstly I would like to say thanks for this beautiful table, it has already saved me a lot of time).

 Sorting toggle works perfect without custom component, and I think my main problem is how to trigger the table to change sorting field manually.

Also inside my custom component I can't get how to detect by which field table is sorted now.
Thanks

**Comment by ratiw** [comment]
@halws Vuetable cannot really predict how it should sort column with custom component. But if you could explain your use case, it might have more idea on how this should be implemented. 

If you would like to manipulate the sorting manually, you could use [`sort-order`](https://www.vuetable.com/api/vuetable/properties.html#sort-order) prop to manipulate how the sort should be done.

**Comment by halws** [comment]
@ratiw Thanx for reply, my use case is next:
There is a table, which has custom fields component in its header. In each field, there should be two sortable cells.
<img width="569" alt="table" src="https://user-images.githubusercontent.com/16323637/48828353-c6f68e80-ed6f-11e8-8e63-456a2b91b54b.png">

Do you think possible solution could be use of event Bus?

**Comment by ratiw** [comment]
@halws This is not possible for Vuetable since the `@click` event was bound in the `<component>` tag outside of the Field Component.

**Comment by halws** [comment]
@ratiw Ok, now i get it). Anyway thank you.

**Comment by halws** [comment]
For me the solution was to use [sort-order](https://www.vuetable.com/api/vuetable/properties.html#sort-order) prop with required sorting params.

Firstly, I created [custom field components](https://www.vuetable.com/guide/creating-field-component.html#creating-field-component), [which i registered locally](https://www.vuetable.com/guide/creating-field-component.html#using-your-field-component-locally). 
Inside them, on click pass( sync) desired sort params throw vuex to the main table component. Then reload table with new sort params.

**vuex**
```
state: {
	sortOrder: { field: "id", sortField: "id", direction: "desc" }
	},
getters: {
	ortOrder(state) {
		return [state.sortOrder];
	}
},
mutations: {
	SET_SORT_FIELD: (state, sort) => (state.sortOrder = sort),
}
```
 **table component**

```
computed: {
	sortOrder() {
		return this.$store.getters.sortOrder;
		}
	},
watch: {
	sortOrder() {
		this.reloadTable();
	}
},
 methods: {
	  reloadTable() {
		this.$nextTick(function() {
			// this is required because vuetable uses tableFields internally, not fields
			this.vuetable.normalizeFields();
			this.vuetable.reload();
		});
	},
}

```
**custom field component**

```
<span 
    class="fields__span sortable" 
    @click="sort"> sort me</span>
```
```
methods: {
	sort() {
		this.$store.commit("SET_SORT_FIELD", {
		field: created_at,
		sortField: created_at,
		direction: this.sortOrder.direction === "desc" ? "asc" : "desc"
	  });
	}
}
```

**Comment by ratiw** [comment]
@halws I like that you can come up with a creative solution that could solve your problem. Thanks for sharing the solution. :)

**Comment by topclaudy** [comment]
You may also use the `orderBy` method of vuetable

```
methods: {
        sort() {
            this.vuetable.orderBy(this.rowField);
        }
    }
```
