### ISSUE TITLE
how to hide thead

### ISSUE THREAD

**Issue by dharmatv** [ratiw/vuetable-2#558]
In my table i don't want to show table header

is there any chance to do in vuetable2

please suggest

**Comment by dharmatv** [comment]
already we have issue in vuetable like hide header, ref link:
https://github.com/ratiw/vuetable-2/issues/523 

 i am trying this way but it is not work out in my side can you please suggest in any idea to hide in vuetable

**Comment by tarun1793** [comment]
would a `thead {display: none;}` work?

**Comment by ratiw** [comment]
@dharmatv,

@tarun1793's suggestion should work.

**Comment by dharmatv** [comment]
@ratiw and @tarun1793 

Thanks for reply

According into my project it's not recommended to add above one, is there any option available

**Comment by tarun1793** [comment]
You can try to play with tmyour table zindex and give it a negative margin
top to hide the header behind the container element. It is not a robust way
though.

**Comment by dharmatv** [comment]
Thanks for reply

i am not thinking this is not robust way but in my project without css we can complete this issue

**Comment by dharmatv** [comment]
At finally i got the answer 

I had write custom props to this table

That's the reason i am closing the task

Thanks for every one who helped me
