### ISSUE TITLE
Issue while trying to use vuetable-2 with parceljs

### ISSUE THREAD

**Issue by uka17** [ratiw/vuetable-2#564]
Hello!
Trying to use vuetable-2 with parceljs and have an error after assembling:
`vuetable-2-full.js:444 Uncaught ReferenceError: _Object$defineProperty is not defined`
Same code is working fine for webpack. Assembling of vue application with components, but without vuetable-2 is not causing any issues.
 
Here is the example which I'm trying to use:
**Project structure**
```
app
└ src
|  └ main.js
|  └ table.vue
└index.html
└package.json
```
**main.js**
```
import Vue from "vue";
import vtable from "./table";

new Vue({ 
  el: "#app",
  components: { vtable },
  render: h => h(vtable)
});
```
**table.vue**
```
<template>
  <vuetable
    ref="vuetable"
    api-url="https://vuetable.ratiw.net/api/users"
    :fields="['name', 'nickname', 'email', 'gender']"
    data-path="data"
    pagination-path=""
  ></vuetable> 
</template>

<script>
import vuetable from "vuetable-2/dist/vuetable-2-full";

export default {
  components: {
    vuetable
  }
};
</script>

```
**index.html**
```
<!DOCTYPE html> 
<html> 
  <head> 
    <meta charset="utf-8"> 
    <title>Vuetable app</title>     
  </head> 
  <body> 
    <div id="app">
    </div> 		
    <script src="src/main.js"></script> 
  </body> 
</html>
```
**package.json**
```
...
{
  "scripts": {
    "start": "parcel index.html",
    "pbuild": "parcel build index.html"
  },
  "dependencies": {
    "vue": "^2.5.17",
    "vuetable-2": "^1.7.5"
  },
  "devDependencies": {
    "css-loader": "^1.0.0",
    "parcel-bundler": "^1.10.3",
    "vue-template-compiler": "^2.5.17",
  }
}
```

**Comment by ratiw** [comment]
@uka17 I really have limited knowledge about the bundler, even with the webpack itself. But have you tryied importing from the npm package instead?

```js
  import vuetable from "vuetable-2/src/components/Vuetable.vue";
```

I think the bundler is supposed to compile from the source directly, not from the already converted code.

**Comment by uka17** [comment]
@ratiw It works. You are genius! =) Thank you! But I still don't understand why it works - quite hard for me to dive so deeply into vue code features.
