### ISSUE TITLE
Pass props to detailsRow component @next

### ISSUE THREAD

**Issue by vukadinFE** [ratiw/vuetable-2#565]
Hi,
Thanks for great work. 
I have one question related to the documentation: [https://www.vuetable.com/guide/detail-row.html#detail-row](url).
It says that  you can import and assign details row to a variable in data section and use it as a local component. That works very well, so now  I can use `:detail-row-component` attribute to assign component that sits in my parent `data()`.
My question is how can pass extra props to a `detailsRow` component?
Documentation: `options -- extra object in case you need to pass additional options to your detail row component`.

**Comment by ratiw** [comment]
@vukadinFE There is actually a [`detail-row-options`](https://github.com/ratiw/vuetable-2/blob/next/src/components/Vuetable.vue#L256-L261) prop that I forget to document it. It gets passed to the detail row component [here](https://github.com/ratiw/vuetable-2/blob/next/src/components/Vuetable.vue#L84-L88).

Sorry about that.
