### ISSUE TITLE
Plans for Vue 3

### ISSUE THREAD

**Issue by tamalsaha** [ratiw/vuetable-2#572]
Thanks for this table component. We are planning to use this with Vue 2.5 . But we are also thinking about the future. What are your plans for Vue 3? Are you planning to maintain and upgrade to new version of Vue when it is released?

Thanks.

**Comment by ratiw** [comment]
I hope so. :)

**Comment by tamalsaha** [comment]
Thank you!

**Comment by clemsontiger** [comment]
does vuetable 2 work with vue 2.6.11  (latest build) ?

**Comment by Xaelp** [comment]
Hi ratiw, do you know when can we expect Vue 3 compatibility?
