### ISSUE TITLE
All event anchors in the docs are wrong

### ISSUE THREAD

**Issue by eComEvo** [ratiw/vuetable-2#580]
https://ratiw.github.io/vuetable-2/#/Vuetable-Events

All of the event names on the page are simply `# vuetable` so they do not correspond to the index at the top making it difficult to tell what is what in the documentation.

**Comment by ratiw** [comment]
@eComEvo See [vuetable.com](https://vuetable.com) instead.

**Comment by eComEvo** [comment]
Thanks!
