### ISSUE TITLE
Removing 'fixed' CSS class from <table>

### ISSUE THREAD

**Issue by coryrose1** [ratiw/vuetable-2#598]
Hi and thanks for the great package.

I am specifying classes via the CSS prop, however it always lists "vuetable [my classes here] fixed". 

I'm wondering if the CSS class 'fixed' is default to the table and if it can be removed? Is there a reason it is a default?

Thanks again!

**Comment by coryrose1** [comment]
This was solved by overriding `tableBodyClass`

**Comment by gregg-cbs** [comment]
This is extremely confusing. Why is fixed class added as a default?
