### ISSUE TITLE
Vuepress integration/plugin

### ISSUE THREAD

**Issue by BenRoe** [ratiw/vuetable-2#599]
Hello,
i wanna use vuetable-2 with [vuepress](https://vuepress.vuejs.org), but i am vue noob.
Is can someone help me  and point to a direction, post some code examples, or even better and create a [vuepress plugin ](https://vuepress.vuejs.org/plugin/).
Many thanks.

**Comment by BenRoe** [comment]
Got it to work. Maybe this helps some other noobs. 

Install Vuetable with `npm install -D vuetable-2@next` or `yarn add -D vuetable-2@next`

Create a file `.vuepress/components/Vuetable.vue` in your root project folder.

```js
<template>
  <vuetable ref="vuetable"
    api-url="http://openlibrary.org/people/george08/lists.json"
    :fields="['name', {name: 'last_update', title: 'Last Update'}, 'edition_count']"
    data-path="entries"
    pagination-path=""
  ></vuetable>
</template>

<script>
import Vuetable from 'vuetable-2'

export default {
  components: {
    Vuetable
  }
}
</script>
```

Add `<Vuetable/>` to your .md file where the table should be displayed.

**Comment by shriaviator** [comment]
@BenRoe it works in the dev mode , were u able to deploy , it because it shows error !!
