### ISSUE TITLE
Item Actions not implemented

### ISSUE THREAD

**Issue by a-hart** [ratiw/vuetable-2#6]
Using this on a Vue 2.0+ project, I noticed that the this version does not have the item-actions implemented yet in the code. Creating this issue to keep track of implementation.

**Comment by ratiw** [comment]
@a-hart It was actually an intended deprecation. Use `__component` instead, it is much more useful with no limitation on what you can do. See [example here](https://github.com/ratiw/vuetable-2/blob/master/src/main.js#L9)

**Comment by a-hart** [comment]
Appreciate the heads up, missed it in reviewing the code. Got it working now. Thanks!
