### ISSUE TITLE
Conflicts Vee-validate

### ISSUE THREAD

**Issue by fernandoMachado92** [ratiw/vuetable-2#60]
I'm using vee-validate and I'm having a conflict problem with the 'fields' prop.

What can I do to solve it?

**Comment by fernandoMachado92** [comment]
If you using vee-validate plugin you can init it like this - Vue.use(VeeValidate, {fieldsBagName: 'formFields'})

**Comment by leonardlin** [comment]
I'm using vee-validate with typescript.
When I try the approach: Vue.use(VeeValidate, {fieldsBagName: 'formFields'});

I get the following error:
error TS2345: Argument of type 'typeof "/home/leonard/workspace/ofbiz-hot-deploy/freshmarket/frontend/partner-vue/node_modules/ve...' is not assignable to parameter of type 'PluginObject<any> | PluginFunction<any>'.

Is this a typing issue?
Thanks in advance for any help.
