### ISSUE TITLE
Pagination doesn't seem to be updating as expected

### ISSUE THREAD

**Issue by hellomikes** [ratiw/vuetable-2#611]
Hi

I've just implemented the pagination mixin for this and I seem to be getting an issue with the number of pages being returned.

I am storing a lot of the required parameters in a Vuex store (per_page, total etc.) and storing the data attribute after an axios call.  We are then filtering this data, which basically re-runs the above and updates my store values for total etc (this is returned by the api).  From what I can tell, my store and data is being updated as expected.

However, the number of page links is not being updated. For example, on initial load there are 150 results, and the per_page value is set to 10, so it returns 15 pages.  When I filter them, it then goes down to 18 results, so should be split across 2 pages.

The data filters down, and going to page 2 shows the last 8 results, however links for all 5 pages still show.  This only seems to happen in our production environment - when running in dev on my machine it works fine, when running a production build on my machine it works fine, but in our main production server it doesn't update.

Does anyone have any idea why this might happen, or where I might even begin to start debugging this?  I can send sample code tomorrow if needed

**Comment by michaelsmedley** [comment]
FYI, an update to v2.0.0.beta-4 has solved this, think it was sorted in https://github.com/ratiw/vuetable-2/pull/515
