### ISSUE TITLE
Passing slots to children 

### ISSUE THREAD

**Issue by VinceG** [ratiw/vuetable-2#626]
This has been asked before #101 was wondering if we have any solution to this problem as i am having the same use case where we have a vue-table component that we reference in some parent components and would like to pass in the scoped slots to it.

**Comment by VinceG** [comment]
Looks like it's now possible in 2.6 using scopedSlots variable. So inside the child component where vue-table resides you'll add the following code

```
<template v-for="(_, slot) of $scopedSlots" v-slot:[slot]="scope"><slot :name="slot" v-bind="scope"/></template>
```

for example:

```
<vuetable
    ref="vuetable"
    :http-options="httpOptions"
    :query-params="queryParams"
    :fields="fields"
    :api-url="url"
    data-path="data"
    pagination-path="meta"
    :css="css.table"
    event-prefix
    :no-data-template="noResultsTemplate"
    :per-page="perPage"
    :sort-order="defaultSort"
    :sort-params="sortParams"
    @loading="onLoading"
    @loaded="onLoaded"
    @pagination-data="onPaginationData"
>
    <template v-for="(_, slot) of $scopedSlots" v-slot:[slot]="scope"><slot :name="slot" v-bind="scope"/></template>
</vuetable>
```

**Comment by gabeta** [comment]
It's evening 11 at my house you just saved me from a sleepless night I recollecting you
