### ISSUE TITLE
Cannot rerender template slot

### ISSUE THREAD

**Issue by CrashLaker** [ratiw/vuetable-2#675]
Hi all,

I'm trying to add a Vue Component to make a cell editable but I can't get the column to be rerendered when I switch pages.

Can anyone help me?
here's my [codesandbox](https://codesandbox.io/s/vuetable-2-with-uikit-fork-template-wont-rerender-ev0xi?file=/src/App.vue)

```vuejs
<vuetable
      ref="vuetable"
      api-url="https://vuetable.ratiw.net/api/users"
      :fields="fields"
      data-path="data"
      pagination-path
      :per-page="5"
      :css="css.table"
      @vuetable:pagination-data="onPaginationData"
    >
      <template slot="name" slot-scope="props">
        <editable-cell :text="props.rowData.name"/>
      </template>

    </vuetable>
    <vuetable-pagination
      ref="pagination"
      :css="css.pagination"
      @vuetable-pagination:change-page="onChangePage"
    ></vuetable-pagination>
  </div>
```

I can edit the cell
![image](https://user-images.githubusercontent.com/4432491/83714488-4c176080-a601-11ea-8892-93c14e11ca1a.png)

but the column's value remains frozen after pagination change.

**Comment by loiacon** [comment]
You should have a `key` attribute inside `editable-cell` to force template rerender. In your case, you can use `props.rowData.name`:
```vue
<template slot="name" slot-scope="props">
    <editable-cell :key="props.rowData.name" :text="props.rowData.name"/>
</template>
```

**Comment by CrashLaker** [comment]
thanks a lot!
adding `:key="props.rowData.name"` worked!!
