### ISSUE TITLE
Can't work with this library

### ISSUE THREAD

**Issue by darelaurel** [ratiw/vuetable-2#682]
I am working on laravel and vue js project and i need to implements a datatable, so i choose vuetable-2
i install with npm i --save  vuetable-2
but i have a lot of errors about css loader and the components wrapped the vuetable-2 doesn't work

i want the help of someone who can tell me which dependancies the vuetable-2 need to work and the configuration of some loaders that i need

**Comment by bhaveshdaswani93** [comment]
hi 
I am looking for the same requirement to implement datatable with laravel.
Can you share how you make it work?
