### ISSUE TITLE
Can I use vuetable-2 without pagination?

### ISSUE THREAD

**Issue by bb78657** [ratiw/vuetable-2#69]
My data for vuetable-2 returned from the server has no pagination information in the json object and only consists of short lists of data. Is there a way to disable pagination - or just set pagination to use all data - or calculate pagination properties on the client side and feed into vuetable-2 data?

Currently I get a warning
 ```
"vuetable: pagination-path "links.pagination" not found. It looks like the data
returned from the server does not have pagination information or you may have
set it incorrectly."
```

**Comment by ratiw** [comment]
@bb78657 You don't have to use pagination component. You can ignore the warning or just set `pagination-data=""` to suppress the warning.

**Comment by bb78657** [comment]
Thanks, that works
