### ISSUE TITLE
Suggestion: Dynamically detect slot fields

### ISSUE THREAD

**Issue by pyrello** [ratiw/vuetable-2#73]
The ability to set a field to use a scoped slot of its template is pretty darn cool! What would make it even better is if you didn't have to add the extra "__slot:..." part. I wrote a jsfiddle demonstrating how this could be accomplished: https://jsfiddle.net/pyrello/odwag9mx/

I don't have time at the moment to create and test a pull request, but if I have some time in the next few weeks, I might go ahead and put one together. Either way, I figured I would put this here in case you are interested.

Thanks!

Sean

**Comment by ratiw** [comment]
@pyrello This is really cool and interesting. Hope to get an update from you on this. :)

**Comment by pyrello** [comment]
Closing this because it is covered by my PR.
