### ISSUE TITLE
[On Firefox]TypeError: els.forEach is not a function

### ISSUE THREAD

**Issue by larryu** [ratiw/vuetable-2#74]
I got some following error on firefox but all good on Chrome.
Any idea?
Thanks.

TypeError: els.forEach is not a function
Stack trace:
checkCheckboxesState@http://127.0.0.1:8000/js/app.js:27991:9
boundFn@http://127.0.0.1:8000/js/app.js:544:11
module.exports.render/<@http://127.0.0.1:8000/js/app.js:61148:20
renderList@http://127.0.0.1:8000/js/app.js:2738:1
module.exports.render@http://127.0.0.1:8000/js/app.js:61140:30
renderMixin/Vue.prototype._render@http://127.0.0.1:8000/js/app.js:2634:15
updateComponent@http://127.0.0.1:8000/js/app.js:3027:18
get@http://127.0.0.1:8000/js/app.js:3352:15
run@http://127.0.0.1:8000/js/app.js:3421:17
flushSchedulerQueue@http://127.0.0.1:8000/js/app.js:3225:5
queueNextTick/<@http://127.0.0.1:8000/js/app.js:891:17
nextTickHandler@http://127.0.0.1:8000/js/app.js:840:7

**Comment by bajian** [comment]
@larryu it maybe the same as this https://github.com/ratiw/vuetable-2/pull/66

**Comment by larryu** [comment]
@bajian Thanks. It works.
