### ISSUE TITLE
It's possible that web use vuikit modal inside vuetable cells ?

### ISSUE THREAD

**Issue by leonfather** [ratiw/vuetable-2#78]
I can't integrate vuikit modal inside vuetable cells to get a prompt modal to confirm my action with input that save some note?
Vuikit : https://vuikit.js.org/#/

**Comment by ratiw** [comment]
@leonfather I have no idea. But you may try using [`__slot`](https://github.com/ratiw/vuetable-2-tutorial/blob/master/doc/lesson-11.md#__slotname--v120) option and see if it works or not.

**Comment by leonfather** [comment]
Thanks
