### ISSUE TITLE
toggleCheckbox doesn't work

### ISSUE THREAD

**Issue by c0defre4k** [ratiw/vuetable-2#8]
Looks like the parameters doesn't match the function's logic anymore.

```@change="toggleCheckbox($event.target.checked, item, field.name)"```
vs
```toggleCheckbox: function(dataItem, fieldName, event) {```

However I tried to fix toggleCheckbox's arguments the values where added to the ``selectedTo`` array but the checkbox didn't stay checked.

**Comment by ratiw** [comment]
@c0defre4k Thanks. I'll check and let you know.

**Comment by ming517** [comment]
Hi, I have created a PR #9 for this issue, could you have a check?

PS: my first PR ...
