### ISSUE TITLE
How can i use vue-table with infinite scroll inside of pagination 

### ISSUE THREAD

**Issue by leonfather** [ratiw/vuetable-2#85]
Hello i realy appreciate your work, i need to use infinite scroll insite of pagination for my vuetable-2, How can i do this? Can you help me to do this with some instructions?

**Comment by ratiw** [comment]
@leonfather I have no idea really because I don't use it. You can try and if you get stuck on anything, you can try to explain your problem to me. But I have no idea at this point.

**Comment by leonfather** [comment]
Thank you so much

**Comment by SuperKiwi** [comment]
@leonfather did you manage to implement Infinite scroll inside vuetable-2 ?
And if so, which vue infinite scroll component did you use ?

**Comment by ratiw** [comment]
Please be careful when using infinite scroll though as it would always adding up data row into the table. This will definitely affect the memory usage and cause reactivity response time of the whole system.

**Comment by rodolfobubb** [comment]
@leonfather Did you have success? And can share with us?

**Comment by tarun1793** [comment]
@rodolfobubb have a look at https://github.com/ratiw/vuetable-2/pull/555
