### ISSUE TITLE
how to listen to an event emitted by the custom-action compontent ?

### ISSUE THREAD

**Issue by bajian** [ratiw/vuetable-2#89]
UserListCustomActions.vue:
```
itemAction (action, data, index) {
      console.log('custom-actions: ' + action, data, index)
        this.$emit('on-itemclick',{
            action:action,
            data:data,
            index:index,
        });
    }
```
use it in the vuetable's `fields`:
```
{
          name: '__component:custom-actions',
          title: 'action',
          titleClass: 'center aligned',
          dataClass: 'center aligned'
      }
```
how to call the `@on-itemclick` in the parent vuetable ? it doesnt work well

**Comment by larryu** [comment]
@bajian I think you should  call  
this.$parent.$emit('on-itemclick',{
            action:action,
            data:data,
            index:index,
        });

In your parent component listen the event just like the following.

        <vuetable ref="vuetable"
                  @on-itemclick="onActions"
        ></vuetable>

**Comment by bajian** [comment]
yes ,itworks well. thanks!
