### ISSUE TITLE
are next_ and prev_page_url still relevant ?

### ISSUE THREAD

**Issue by jdriesen** [ratiw/vuetable-2#95]
Hi,

I've been studying your code in depth (I like to understand what I'm doing :) 

Great piece of sofware. Thanks again !

At a certain moment, you're performing the GET call.

The JSON returned from the server, contains (beside the data,  total, per_page, last_page etc values) also a ***next_page_url*** and a ***prev_page_url*** value...

![myimage](http://www.driesen.eu/insiderclub/ratiw/vuetable.png)

My question: are these 'values' still used in your table ?

(all functionalities are still working, even when I'm returning NULL, and I can't find any 'reference' to them in your source-code, that's why I'm asking...)

Thanks in advance for your reply,

Kind regards,

Johnny driesen

(Belgium)

**Comment by ratiw** [comment]
@jdriesen Those are for pagination component and no it is not needed at the moment as all of the pagination components in Vuetable-2 package do not use it. 

It is derived from Laravel's [Pagination](https://laravel.com/docs/5.4/pagination#converting-results-to-json) data structure. So, if you're using Laravel for you backend work like mine, you don't have to change anything to make use of Vuetable.

However, it's going to be useful if you would like to build a simple pagination component for Vuetable that has only previous and next page functionality.

**Comment by jdriesen** [comment]
Very clear answer !
Thanks a lot.

I'm using CodeIgniter to 'create' my JSON objects,
CodeIgniter doesn't give me these params 'automatically', I had to do some extra programming to 'create' them. That's how I found out about them :)

Thanks again for your quick reply.
Feel free to close this issue.

Kind regards,
Johnny

**Comment by clemsontiger** [comment]
I'm a little confused regarding the pagination. does my server side process have to return a json formatted pagination data in the format below in order to properly page, sort, etc? or can i just give it the results data set withouth the page information?
~~~
{
   "total": 50,
   "per_page": 15,
   "current_page": 1,
   "last_page": 4,
   "next_page_url": "http://.../users?page=2",
   "prev_page_url": null,
   "from": 1,
   "to": 15,
   "data":[ ....
~~~

**Comment by ratiw** [comment]
Some info [here](https://github.com/ratiw/vue-table/wiki/Data-Format-(JSON)).
